# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(default=list, help_text='List of features enabled for this industry')),
                ('default_workflows', models.JSONField(default=dict, help_text='Default workflow configurations for this industry')),
                ('required_modules', models.JSONField(default=list, help_text='List of modules required for this industry')),
                ('default_product_categories', models.JSONField(default=list, help_text='Default product categories for this industry')),
                ('metadata_schema', models.JSONField(default=dict, help_text='Schema for industry-specific metadata fields')),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IndustryConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settings', models.JSONField(default=dict, help_text='Custom settings for this industry-tenant combination')),
                ('workflows', models.JSONField(default=dict, help_text='Custom workflow configurations')),
                ('custom_fields', models.JSONField(default=dict, help_text='Custom field definitions')),
                ('active_modules', models.JSONField(default=list, help_text='List of activated modules')),
                ('approval_rules', models.JSONField(default=dict, help_text='Custom approval rules')),
            ],
            options={
                'ordering': ['tenant', 'industry'],
            },
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.SlugField(help_text="Internal code, e.g. 'finance'")),
                ('label', models.CharField(help_text="Visible title, e.g. 'Finance'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.SlugField(help_text="Internal code, e.g. 'trial_balance'")),
                ('label', models.CharField(help_text="Visible title, e.g. 'Trial Balance'", max_length=100)),
                ('route', models.CharField(help_text='Frontend route or URL name', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('permission', models.CharField(blank=True, help_text="Django perm codename required to see this item, e.g. 'transactions.view_trialbalance'", max_length=100)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(db_index=True, help_text='Unique reference number for this document', max_length=50, unique=True)),
                ('module', models.CharField(choices=[('procurement', 'Procurement'), ('expenses', 'Expenses'), ('inventory', 'Inventory'), ('assets', 'Assets'), ('liabilities', 'Liabilities'), ('incomes', 'Incomes')], help_text='Module that owns this document', max_length=50)),
                ('model_name', models.CharField(help_text="Model class name (e.g., 'purchase_requisition')", max_length=100)),
                ('object_id', models.IntegerField(help_text='Primary key of the actual document')),
                ('origin_reference', models.CharField(db_index=True, help_text='First reference in chain (the originating document)', max_length=50)),
                ('parent_reference', models.CharField(blank=True, db_index=True, help_text='Immediate parent reference (empty if this is the origin)', max_length=50)),
                ('status', models.CharField(help_text='Current status of the document', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Document amount (if applicable)', max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata (department, requester, etc.)')),
            ],
            options={
                'verbose_name': 'Reference Tracking',
                'verbose_name_plural': 'Reference Tracking',
                'db_table': 'common_reference_tracking',
                'ordering': ['-created_at'],
            },
        ),
    ]
