# Generated by Django 5.2.4 on 2026-06-23 23:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_insurance_verifier_disbursement'),
        ('common', '0003_businessday_backdaterequest'),
        ('users', '0010_daily_reconciliation_and_exception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('loan_approve', 'Loan Approved'), ('loan_disburse', 'Loan Disbursed'), ('loan_repay', 'Loan Repayment'), ('savings_deposit', 'Savings Deposit'), ('savings_withdraw', 'Savings Withdrawal'), ('journal_post', 'Journal Entry Posted'), ('permission_change', 'Permission Changed'), ('user_role_change', 'User Role Changed')], db_index=True, max_length=30)),
                ('record_type', models.CharField(max_length=100)),
                ('record_id', models.CharField(db_index=True, max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='branches.branch')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='common_fina_event_t_9ff1b4_idx'), models.Index(fields=['acted_by', 'timestamp'], name='common_fina_acted_b_9741ef_idx'), models.Index(fields=['record_type', 'record_id'], name='common_fina_record__6ae44f_idx')],
            },
        ),
    ]
