# Generated by Django 5.2.4 on 2026-07-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_role_navigation_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialauditlog',
            name='event_type',
            field=models.CharField(choices=[('loan_approve', 'Loan Approved'), ('loan_disburse', 'Loan Disbursed'), ('loan_repay', 'Loan Repayment'), ('loan_balance_correction', 'Loan Balance Correction'), ('savings_deposit', 'Savings Deposit'), ('savings_withdraw', 'Savings Withdrawal'), ('journal_post', 'Journal Entry Posted'), ('permission_change', 'Permission Changed'), ('user_role_change', 'User Role Changed')], db_index=True, max_length=30),
        ),
    ]
