# Generated by Django 5.2.4 on 2026-08-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_financialauditlog_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialauditlog',
            name='event_type',
            field=models.CharField(choices=[('loan_approve', 'Loan Approved'), ('loan_disburse', 'Loan Disbursed'), ('loan_repay', 'Loan Repayment'), ('loan_balance_correction', 'Loan Balance Correction'), ('savings_deposit', 'Savings Deposit'), ('savings_withdraw', 'Savings Withdrawal'), ('savings_income_backfill', 'Savings First-Deposit-Income Backfill Correction'), ('journal_post', 'Journal Entry Posted'), ('permission_change', 'Permission Changed'), ('user_role_change', 'User Role Changed'), ('client_registration_fee', 'Client Registration Fee Collected'), ('client_reactivation_fee', 'Client Reactivation Fee Collected'), ('loan_penalty_accrual', 'Loan Penalty Accrued')], db_index=True, max_length=30),
        ),
    ]
