// Route mapping utility — access control based on rank (1–5) not hardcoded role names.
// Rank 5 = Director, 4 = Principal, 3 = Administrator, 2 = Officer-level, 1 = Basic staff

import { getRoleRank } from '../types/roles';
import { FunctionalCategory, PageId } from '../types/permissions';

export interface RouteMapping {
  path: string;
  pageId: PageId;
  title: string;
  category: FunctionalCategory;
  /** Minimum rank required to access this route. */
  minRank: number;
  component: string;
  description?: string;
  icon?: string;
  isNew?: boolean;
  isEnhanced?: boolean;
}

export const ROUTE_MAPPINGS: RouteMapping[] = [
  // ── User Management ────────────────────────────────────────────────────────
  {
    path: '/settings',
    pageId: 'users.settings',
    title: 'User Management',
    category: 'User Management',
    minRank: 3,
    component: 'UserManagementPage',
    icon: 'Users',
    description: 'Manage system users and their access',
  },
  {
    path: '/admin/users',
    pageId: 'users.add',
    title: 'User Management',
    category: 'User Management',
    minRank: 3,
    component: 'UserManagementPage',
    icon: 'Users',
    description: 'Manage system users and their access',
  },
  {
    path: '/admin/roles-matrix',
    pageId: 'users.edit_roles_permissions',
    title: 'Roles & Permissions Matrix',
    category: 'User Management',
    minRank: 4,
    component: 'RolesPermissionsMatrixPage',
    icon: 'Shield',
    description: 'Configure role-based permissions',
  },
  {
    path: '/admin/branches',
    pageId: 'users.branch_tenant_management',
    title: 'Branch Management',
    category: 'User Management',
    minRank: 3,
    component: 'BranchListPage',
    icon: 'Building',
    description: 'Manage organizational branches',
  },
  {
    path: '/admin/tenants',
    pageId: 'users.branch_tenant_management',
    title: 'Tenant Management',
    category: 'User Management',
    minRank: 3,
    component: 'TenantListPage',
    icon: 'Building2',
    description: 'Manage system tenants',
  },
  {
    path: '/admin/access-control',
    pageId: 'users.edit_roles_permissions',
    title: 'Access Control',
    category: 'User Management',
    minRank: 3,
    component: 'AccessControlPage',
    icon: 'Lock',
    description: 'Configure system access controls',
  },
  {
    path: '/settings/role-navigation',
    pageId: 'admin.system_settings',
    title: 'Navigation Configuration',
    category: 'System Administration',
    minRank: 4,
    component: 'RoleSidebarConfigPage',
    icon: 'Navigation',
    description: 'Configure sidebar navigation per role',
  },

  // ── Financial Operations ────────────────────────────────────────────────────
  {
    path: '/sales/invoices',
    pageId: 'financial.invoice_generation',
    title: 'Invoice Management',
    category: 'Financial Operations',
    minRank: 2,
    component: 'InvoicesList',
    icon: 'FileText',
    description: 'Create and manage invoices',
  },
  {
    path: '/sales/invoices/create',
    pageId: 'financial.invoice_generation',
    title: 'Create Invoice',
    category: 'Financial Operations',
    minRank: 2,
    component: 'CreateInvoice',
    icon: 'FilePlus',
    description: 'Create new invoices',
  },
  {
    path: '/sales/invoices/bulk',
    pageId: 'financial.invoice_generation',
    title: 'Bulk Invoice Creation',
    category: 'Financial Operations',
    minRank: 2,
    component: 'BulkInvoiceWizardDemo',
    icon: 'FileStack',
    description: 'Create multiple invoices at once',
  },
  {
    path: '/accounts',
    pageId: 'financial.accounts_management',
    title: 'Chart of Accounts',
    category: 'Financial Operations',
    minRank: 3,
    component: 'AccountsListPage',
    icon: 'BookOpen',
    description: 'Manage chart of accounts',
  },
  {
    path: '/accounts/new',
    pageId: 'financial.accounts_management',
    title: 'Create Account',
    category: 'Financial Operations',
    minRank: 3,
    component: 'UnifiedAccountCreationPage',
    icon: 'Plus',
    description: 'Create new accounts',
  },
  {
    path: '/receivables/dashboard',
    pageId: 'financial.receivables_dashboard',
    title: 'Receivables Dashboard',
    category: 'Financial Operations',
    minRank: 2,
    component: 'ReceivablesDashboard',
    icon: 'TrendingUp',
    description: 'Monitor accounts receivable',
  },
  {
    path: '/receivables/list',
    pageId: 'financial.receivables_dashboard',
    title: 'Receivables List',
    category: 'Financial Operations',
    minRank: 2,
    component: 'ReceivablesList',
    icon: 'List',
    description: 'View all receivables',
  },
  {
    path: '/receivables/payments/record',
    pageId: 'financial.payment_requests',
    title: 'Record Payment',
    category: 'Financial Operations',
    minRank: 2,
    component: 'RecordPayment',
    icon: 'CreditCard',
    description: 'Record customer payments',
  },
  {
    path: '/receivables/aging-report',
    pageId: 'reports.aging_reports',
    title: 'Aging Report',
    category: 'Financial Operations',
    minRank: 2,
    component: 'AgingReport',
    icon: 'Clock',
    description: 'View receivables aging analysis',
  },
  {
    path: '/sales/invoices/:invoiceId/credit-notes',
    pageId: 'financial.credit_notes',
    title: 'Credit Notes',
    category: 'Financial Operations',
    minRank: 2,
    component: 'CreditNotesList',
    icon: 'FileX',
    description: 'Manage credit notes',
  },
  {
    path: '/treasury/dashboard',
    pageId: 'financial.daily_posting',
    title: 'Treasury Dashboard',
    category: 'Financial Operations',
    minRank: 2,
    component: 'TreasuryDashboard',
    icon: 'Wallet',
    description: 'Treasury management dashboard',
  },
  {
    path: '/treasury/bank-reconciliation',
    pageId: 'financial.daily_posting',
    title: 'Bank Reconciliation',
    category: 'Financial Operations',
    minRank: 2,
    component: 'BankReconciliationPage',
    icon: 'CreditCard',
    description: 'Reconcile bank statements',
  },
  {
    path: '/treasury/petty-cash',
    pageId: 'financial.daily_posting',
    title: 'Petty Cash',
    category: 'Financial Operations',
    minRank: 2,
    component: 'PettyCashDashboard',
    icon: 'Wallet',
    description: 'Manage petty cash funds and vouchers',
  },
  {
    path: '/treasury/petty-cash/vouchers',
    pageId: 'financial.daily_posting',
    title: 'Petty Cash Vouchers',
    category: 'Financial Operations',
    minRank: 2,
    component: 'PettyCashVoucherList',
    icon: 'Receipt',
    description: 'Manage petty cash vouchers',
  },
  {
    path: '/expenses',
    pageId: 'financial.payment_requests',
    title: 'Expenses',
    category: 'Financial Operations',
    minRank: 2,
    component: 'ExpenseListPage',
    icon: 'DollarSign',
    description: 'Manage general expenses',
  },
  {
    path: '/expenses/prepaid',
    pageId: 'financial.payment_requests',
    title: 'Prepaid Expenses',
    category: 'Financial Operations',
    minRank: 2,
    component: 'PrepaidExpenseListPage',
    icon: 'CalendarDays',
    description: 'Manage prepaid expense amortization',
  },
  {
    path: '/liabilities/payables',
    pageId: 'financial.payment_requests',
    title: 'Accounts Payable',
    category: 'Financial Operations',
    minRank: 2,
    component: 'PayablesListPage',
    icon: 'Receipt',
    description: 'Manage accounts payable',
  },
  {
    path: '/banks',
    pageId: 'financial.accounts_management',
    title: 'Banks',
    category: 'Financial Operations',
    minRank: 2,
    component: 'BankListPage',
    icon: 'Building2',
    description: 'Manage banks',
  },
  {
    path: '/banks/accounts',
    pageId: 'financial.accounts_management',
    title: 'Bank Accounts',
    category: 'Financial Operations',
    minRank: 2,
    component: 'BankAccountListPage',
    icon: 'CreditCard',
    description: 'Manage bank accounts and GL links',
  },
  {
    path: '/banks/accounts/new',
    pageId: 'financial.accounts_management',
    title: 'New Bank Account',
    category: 'Financial Operations',
    minRank: 3,
    component: 'BankSetupPage',
    icon: 'CreditCard',
    description: 'Create a new bank account',
  },
  {
    path: '/banks/accounts/:id',
    pageId: 'financial.accounts_management',
    title: 'Bank Account Detail',
    category: 'Financial Operations',
    minRank: 2,
    component: 'BankAccountDetailPage',
    icon: 'CreditCard',
    description: 'View bank account detail and ledger',
  },
  {
    path: '/banks/transfers',
    pageId: 'financial.accounts_management',
    title: 'Inter-bank Transfers',
    category: 'Financial Operations',
    minRank: 2,
    component: 'BankTransferListPage',
    icon: 'ArrowLeftRight',
    description: 'Manage bank-to-bank transfers',
  },
  {
    path: '/banks/transfers/new',
    pageId: 'financial.accounts_management',
    title: 'New Inter-bank Transfer',
    category: 'Financial Operations',
    minRank: 2,
    component: 'BankTransferFormPage',
    icon: 'ArrowLeftRight',
    description: 'Create a new inter-bank transfer',
  },
  {
    path: '/banks/payments',
    pageId: 'financial.accounts_management',
    title: 'Bank Payments',
    category: 'Financial Operations',
    minRank: 2,
    component: 'BankPaymentListPage',
    icon: 'Receipt',
    description: 'Track supplier and expense bank payments',
  },
  {
    path: '/banks/payments/new',
    pageId: 'financial.accounts_management',
    title: 'New Bank Payment',
    category: 'Financial Operations',
    minRank: 2,
    component: 'BankPaymentFormPage',
    icon: 'Receipt',
    description: 'Create a bank payment for suppliers or expenses',
  },

  // ── Client Management ─────────────────────────────────────────────────────
  {
    path: '/clients',
    pageId: 'students.client_management',
    title: 'Client Management',
    category: 'Client Management',
    minRank: 1,
    component: 'ClientListPage',
    icon: 'Users',
    description: 'Manage client records',
  },
  {
    path: '/clients/create',
    pageId: 'students.registration',
    title: 'Client Registration',
    category: 'Client Management',
    minRank: 1,
    component: 'ClientFormPage',
    icon: 'UserPlus',
    description: 'Register new clients',
  },
  {
    path: '/clients/classifications',
    pageId: 'students.client_management',
    title: 'Client Classifications',
    category: 'Client Management',
    minRank: 1,
    component: 'ClientClassificationsPage',
    icon: 'Tags',
    description: 'Manage client classifications',
  },
  {
    path: '/incomes/entitlements',
    pageId: 'students.entitlements',
    title: 'Student Entitlements',
    category: 'Client Management',
    minRank: 1,
    component: 'EntitlementsList',
    icon: 'Award',
    description: 'Manage student entitlements',
  },
  {
    path: '/incomes/entitlements/dashboard',
    pageId: 'students.entitlements',
    title: 'Entitlements Dashboard',
    category: 'Client Management',
    minRank: 1,
    component: 'EntitlementDashboard',
    icon: 'BarChart3',
    description: 'Entitlements overview dashboard',
  },
  {
    path: '/incomes/fee-structures',
    pageId: 'students.fee_structures',
    title: 'Fee Structures',
    category: 'Client Management',
    minRank: 3,
    component: 'IncomeFeeStructureListPage',
    icon: 'DollarSign',
    description: 'Manage fee structures',
  },
  {
    path: '/receivables/statements',
    pageId: 'students.statements',
    title: 'Client Statements',
    category: 'Client Management',
    minRank: 1,
    component: 'CustomerStatements',
    icon: 'Receipt',
    description: 'Generate client statements',
  },
  {
    path: '/discounts/programs',
    pageId: 'students.entitlements',
    title: 'Discount Programs',
    category: 'Client Management',
    minRank: 3,
    component: 'DiscountProgramsList',
    icon: 'Percent',
    description: 'Manage discount/scholarship programs',
  },

  // ── Reports & Analytics ────────────────────────────────────────────────────
  {
    path: '/reports/financial/trial-balance',
    pageId: 'reports.trial_balance',
    title: 'Trial Balance',
    category: 'Reports & Analytics',
    minRank: 3,
    component: 'TrialBalancePage',
    icon: 'Calculator',
    description: 'Generate trial balance reports',
  },
  {
    path: '/reports/financial/profit-loss',
    pageId: 'reports.profit_loss',
    title: 'Statement of Profit or Loss',
    category: 'Reports & Analytics',
    minRank: 3,
    component: 'ProfitLossPage',
    icon: 'BarChart3',
    description: 'Statement of Profit or Loss',
  },
  {
    path: '/reports/financial/monthly-profit-loss',
    pageId: 'reports.monthly_profit_loss',
    title: 'Monthly Profit & Loss',
    category: 'Reports & Analytics',
    minRank: 3,
    component: 'MonthlyProfitLossPage',
    icon: 'BarChart3',
    description: 'Month-by-month Profit & Loss, one column per calendar month',
  },
  {
    path: '/reports/financial/balance-sheet',
    pageId: 'reports.balance_sheet',
    title: 'Statement of Financial Position',
    category: 'Reports & Analytics',
    minRank: 3,
    component: 'BalanceSheetPage',
    icon: 'Scale',
    description: 'Statement of Financial Position',
  },
  {
    path: '/reports',
    pageId: 'reports.activity_reports',
    title: 'Reports Center',
    category: 'Reports & Analytics',
    minRank: 3,
    component: 'ReportsListPage',
    icon: 'FileBarChart',
    description: 'Access all system reports',
  },
  {
    path: '/receivables/advanced-reporting',
    pageId: 'reports.aging_reports',
    title: 'Advanced Reporting',
    category: 'Reports & Analytics',
    minRank: 2,
    component: 'AdvancedReporting',
    icon: 'TrendingUp',
    description: 'Advanced receivables reporting',
  },
  {
    path: '/receivables/payment-trends',
    pageId: 'reports.financial_dashboard',
    title: 'Payment Trends',
    category: 'Reports & Analytics',
    minRank: 2,
    component: 'PaymentTrends',
    icon: 'LineChart',
    description: 'Analyze payment trends',
  },
  {
    path: '/hr/payroll',
    pageId: 'reports.payroll_reports',
    title: 'Payroll Reports',
    category: 'Reports & Analytics',
    minRank: 3,
    component: 'PayrollListPage',
    icon: 'Wallet',
    description: 'Generate payroll reports',
  },
  {
    path: '/inventory/reports/valuation',
    pageId: 'reports.inventory_reports',
    title: 'Inventory Reports',
    category: 'Reports & Analytics',
    minRank: 2,
    component: 'StockValuationReportPage',
    icon: 'Package',
    description: 'Generate inventory reports',
  },

  // ── Operations ─────────────────────────────────────────────────────────────
  {
    path: '/procurement',
    pageId: 'operations.procurement_dashboard',
    title: 'Procurement Dashboard',
    category: 'Operations',
    minRank: 2,
    component: 'ProcurementModulePage',
    icon: 'ShoppingCart',
    description: 'Procurement management dashboard',
  },
  {
    path: '/procurement/orders',
    pageId: 'operations.purchase_orders',
    title: 'Purchase Orders',
    category: 'Operations',
    minRank: 2,
    component: 'PurchaseOrderListPage',
    icon: 'ShoppingBag',
    description: 'Manage purchase orders',
  },
  {
    path: '/procurement/requisitions',
    pageId: 'operations.purchase_orders',
    title: 'Purchase Requisitions',
    category: 'Operations',
    minRank: 2,
    component: 'RequisitionListPage',
    icon: 'FileText',
    description: 'Manage purchase requisitions',
  },
  {
    path: '/procurement/suppliers',
    pageId: 'operations.supplier_management',
    title: 'Supplier Management',
    category: 'Operations',
    minRank: 2,
    component: 'SupplierListPage',
    icon: 'Truck',
    description: 'Manage suppliers',
  },
  {
    path: '/procurement/grn',
    pageId: 'operations.goods_receipt',
    title: 'Goods Receipt Notes',
    category: 'Operations',
    minRank: 2,
    component: 'GRNListPage',
    icon: 'PackageCheck',
    description: 'Manage goods receipt notes',
  },
  {
    path: '/procurement/quotes',
    pageId: 'operations.supplier_management',
    title: 'Supplier Quotes',
    category: 'Operations',
    minRank: 2,
    component: 'QuoteListPage',
    icon: 'FileSearch',
    description: 'Manage supplier quotes',
  },
  {
    path: '/inventory',
    pageId: 'operations.inventory_management',
    title: 'Inventory Management',
    category: 'Operations',
    minRank: 2,
    component: 'InventoryModulePage',
    icon: 'Warehouse',
    description: 'Inventory management dashboard',
  },
  {
    path: '/inventory/items',
    pageId: 'operations.inventory_management',
    title: 'Inventory Items',
    category: 'Operations',
    minRank: 2,
    component: 'InventoryItemsPage',
    icon: 'Package',
    description: 'Manage inventory items',
  },
  {
    path: '/inventory/movements',
    pageId: 'operations.stock_movements',
    title: 'Stock Movements',
    category: 'Operations',
    minRank: 2,
    component: 'StockMovementsPage',
    icon: 'ArrowRightLeft',
    description: 'Track stock movements',
  },
  {
    path: '/inventory/locations',
    pageId: 'operations.inventory_management',
    title: 'Stock Locations',
    category: 'Operations',
    minRank: 2,
    component: 'StockLocationsPage',
    icon: 'MapPin',
    description: 'Manage stock locations',
  },
  {
    path: '/inventory/adjustments',
    pageId: 'operations.stock_movements',
    title: 'Stock Adjustments',
    category: 'Operations',
    minRank: 2,
    component: 'StockAdjustmentsListPage',
    icon: 'Settings',
    description: 'Manage stock adjustments',
  },
  {
    path: '/hr',
    pageId: 'operations.inventory_management',
    title: 'Human Resources',
    category: 'Operations',
    minRank: 2,
    component: 'HRIndexPage',
    icon: 'Users',
    description: 'HR management dashboard',
  },
  {
    path: '/hr/staff',
    pageId: 'operations.inventory_management',
    title: 'Staff Management',
    category: 'Operations',
    minRank: 3,
    component: 'StaffListPage',
    icon: 'UserCheck',
    description: 'Manage staff records',
  },
  {
    path: '/hr/attendance',
    pageId: 'operations.inventory_management',
    title: 'Attendance Management',
    category: 'Operations',
    minRank: 2,
    component: 'AttendanceListPage',
    icon: 'Clock',
    description: 'Manage staff attendance',
  },
  {
    path: '/hr/leave-requests',
    pageId: 'operations.inventory_management',
    title: 'Leave Management',
    category: 'Operations',
    minRank: 2,
    component: 'LeaveRequestsListPage',
    icon: 'Calendar',
    description: 'Manage leave requests',
  },
  {
    path: '/expenses/resource-consumption',
    pageId: 'operations.inventory_management',
    title: 'Resource Consumption',
    category: 'Operations',
    minRank: 2,
    component: 'ResourceConsumptionListPage',
    icon: 'Zap',
    description: 'Manage resource consumption',
  },
  {
    path: '/expenses/fuel-log/create',
    pageId: 'operations.inventory_management',
    title: 'Log Fuel Receipt',
    category: 'Operations',
    minRank: 2,
    component: 'FuelLogFormPage',
    icon: 'Droplets',
    description: 'Record fuel received by a vehicle or staff member',
  },
  {
    path: '/expenses/resources',
    pageId: 'operations.inventory_management',
    title: 'Resource Management',
    category: 'Operations',
    minRank: 2,
    component: 'ResourceListPage',
    icon: 'Layers',
    description: 'Manage resources',
  },
  {
    path: '/expenses/vouchers',
    pageId: 'operations.inventory_management',
    title: 'Voucher Management',
    category: 'Operations',
    minRank: 2,
    component: 'VoucherListPage',
    icon: 'Ticket',
    description: 'Manage vouchers',
  },
  {
    path: '/assets',
    pageId: 'operations.inventory_management',
    title: 'Asset Management',
    category: 'Operations',
    minRank: 3,
    component: 'AssetListPage',
    icon: 'HardDrive',
    description: 'Manage fixed assets',
  },

  // ── System Administration ──────────────────────────────────────────────────
  {
    path: '/admin/workflows',
    pageId: 'admin.workflow_management',
    title: 'Workflow Management',
    category: 'System Administration',
    minRank: 3,
    component: 'AdminWorkflowsPage',
    icon: 'GitBranch',
    description: 'Configure system workflows',
  },
  {
    path: '/automations/templates',
    pageId: 'admin.workflow_management',
    title: 'Automation Templates',
    category: 'System Administration',
    minRank: 3,
    component: 'AutomationTemplatesPage',
    icon: 'Zap',
    description: 'Manage automation templates',
  },
  {
    path: '/automations/runs',
    pageId: 'admin.workflow_management',
    title: 'Automation Runs',
    category: 'System Administration',
    minRank: 3,
    component: 'AutomationRunsPage',
    icon: 'Play',
    description: 'Monitor automation runs',
  },
  {
    path: '/admin/forms',
    pageId: 'admin.system_settings',
    title: 'Form Management',
    category: 'System Administration',
    minRank: 3,
    component: 'AdminFormsPage',
    icon: 'FileText',
    description: 'Manage system forms',
  },
  {
    path: '/admin/submissions',
    pageId: 'admin.audit_logs',
    title: 'Form Submissions',
    category: 'System Administration',
    minRank: 3,
    component: 'AdminSubmissionsPage',
    icon: 'Send',
    description: 'View form submissions',
  },
  {
    path: '/dashboard/create',
    pageId: 'admin.dashboard_builder',
    title: 'Dashboard Builder',
    category: 'System Administration',
    minRank: 3,
    component: 'DashboardCreatePage',
    icon: 'Layout',
    description: 'Build custom dashboards',
  },
  {
    path: '/approvals',
    pageId: 'admin.audit_logs',
    title: 'Approval Management',
    category: 'System Administration',
    minRank: 3,
    component: 'ApprovalsPage',
    icon: 'CheckCircle',
    description: 'View and manage system approvals',
  },
];

// ── Helper functions ───────────────────────────────────────────────────────────

export const getRoutesByCategory = (category: FunctionalCategory): RouteMapping[] =>
  ROUTE_MAPPINGS.filter(route => route.category === category);

export const getRoutesByRole = (role: string): RouteMapping[] => {
  const rank = getRoleRank(role);
  return ROUTE_MAPPINGS.filter(route => rank >= route.minRank);
};

export const getRouteMapping = (path: string): RouteMapping | undefined =>
  ROUTE_MAPPINGS.find(route => route.path === path);

export const getRouteMappingByPageId = (pageId: PageId): RouteMapping[] =>
  ROUTE_MAPPINGS.filter(route => route.pageId === pageId);

export const getAllCategories = (): FunctionalCategory[] =>
  [...new Set(ROUTE_MAPPINGS.map(route => route.category))];

export const getNavigationStructure = (userRole: string | null) => {
  if (!userRole) return {};
  const userRoutes = getRoutesByRole(userRole);
  const structure: Record<FunctionalCategory, RouteMapping[]> = {} as Record<
    FunctionalCategory,
    RouteMapping[]
  >;
  userRoutes.forEach(route => {
    if (!structure[route.category]) structure[route.category] = [];
    structure[route.category].push(route);
  });
  return structure;
};

export const canUserAccessRoute = (path: string, userRole: string | null): boolean => {
  if (!userRole) return false;

  const route = getRouteMapping(path);
  if (!route) return true; // unmapped routes are open

  const userRank = getRoleRank(userRole);
  return userRank >= route.minRank;
};

export const getBreadcrumbs = (path: string): Array<{ label: string; path?: string }> => {
  const route = getRouteMapping(path);
  if (!route) return [{ label: 'Home', path: '/' }];
  return [{ label: 'Home', path: '/' }, { label: route.category }, { label: route.title }];
};
