# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='dashboard_templates/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='dashboard_templates/thumbnails/')),
                ('template_config', models.JSONField(default=dict, help_text='Complete dashboard configuration including widgets and theme')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Available to all branches')),
                ('usage_count', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'dashboard_templates',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('primary_color', models.CharField(default='#1a73e8', help_text='Hex color', max_length=7)),
                ('secondary_color', models.CharField(default='#34a853', max_length=7)),
                ('accent_color', models.CharField(default='#fbbc04', max_length=7)),
                ('background_color', models.CharField(default='#f5f5f5', max_length=7)),
                ('text_color', models.CharField(default='#202124', max_length=7)),
                ('font_family', models.CharField(default='Inter, system-ui, sans-serif', help_text='CSS font family', max_length=100)),
                ('font_size_base', models.IntegerField(default=14, help_text='Base font size in pixels')),
                ('widget_spacing', models.IntegerField(default=16, help_text='Gap between widgets in pixels')),
                ('widget_border_radius', models.IntegerField(default=8, help_text='Widget corner radius')),
                ('widget_shadow', models.CharField(default='0 1px 3px rgba(0,0,0,0.12)', help_text='CSS box-shadow', max_length=100)),
                ('custom_css_variables', models.JSONField(default=dict, help_text='Additional CSS variables as key-value pairs')),
                ('is_public', models.BooleanField(default=False, help_text='Available to all users')),
            ],
            options={
                'db_table': 'dashboard_themes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('widget_type', models.CharField(choices=[('kpi', 'KPI Card'), ('line_chart', 'Line Chart'), ('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('donut_chart', 'Donut Chart'), ('area_chart', 'Area Chart'), ('table', 'Data Table'), ('list', 'List Widget'), ('stat_grid', 'Statistics Grid'), ('progress', 'Progress Bar'), ('gauge', 'Gauge Chart'), ('map', 'Map Widget'), ('calendar', 'Calendar Widget'), ('timeline', 'Timeline Widget'), ('text', 'Rich Text'), ('html', 'Custom HTML'), ('iframe', 'Embedded Content'), ('navigation', 'Navigation Links'), ('quick_actions', 'Quick Action Buttons'), ('form_embed', 'Embedded Form'), ('image', 'Image Widget'), ('video', 'Video Widget')], max_length=50)),
                ('instance_key', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('config', models.JSONField(default=dict, help_text='\n        Widget-specific configuration with navigation support:\n        \n        KPI with ModulePage navigation:\n        {\n            "format": "currency",\n            "color": "#10b981",\n            "icon": "users",\n            "click_action": {\n                "type": "module_page",\n                "module_code": "students",\n                "page_code": "list",\n                "params": {"status": "active"}\n            }\n        }\n        \n        Table with row actions to module pages:\n        {\n            "columns": [...],\n            "row_actions": [\n                {\n                    "label": "View Details",\n                    "type": "module_page",\n                    "module_code": "students",\n                    "page_code": "detail",\n                    "params": {"id": "{row.id}"}\n                }\n            ]\n        }\n        \n        Navigation widget with module page links:\n        {\n            "links": [\n                {\n                    "label": "New Purchase Request",\n                    "icon": "shopping-cart",\n                    "type": "module_page",\n                    "module_code": "procurement",\n                    "page_code": "purchase-request",\n                    "color": "#f59e0b"\n                },\n                {\n                    "label": "All Requests",\n                    "icon": "list",\n                    "type": "module_page",\n                    "module_code": "procurement",\n                    "page_code": "requests"\n                }\n            ]\n        }\n        ')),
                ('click_action', models.JSONField(default=dict, help_text='\n        Primary action when widget is clicked:\n        \n        Navigate to module page:\n        {\n            "type": "module_page",\n            "module_code": "finance",\n            "page_code": "debtor-aging",\n            "params": {"period": "current"},\n            "target": "_self"\n        }\n        \n        Navigate to absolute URL:\n        {\n            "type": "navigate",\n            "url": "/custom-path",\n            "target": "_self"\n        }\n        \n        Open modal with module page:\n        {\n            "type": "modal",\n            "module_code": "students",\n            "page_code": "enrollment-form",\n            "modal_size": "large"\n        }\n        \n        Trigger workflow:\n        {\n            "type": "trigger_workflow",\n            "workflow_id": 42,\n            "params": {}\n        }\n        \n        Quick action (open form):\n        {\n            "type": "quick_action",\n            "quick_action_code": "new-purchase-request"\n        }\n        ')),
                ('auto_refresh', models.BooleanField(default=False)),
                ('refresh_interval', models.IntegerField(default=60)),
                ('layout_x', models.IntegerField(default=0)),
                ('layout_y', models.IntegerField(default=0)),
                ('layout_w', models.IntegerField(default=4)),
                ('layout_h', models.IntegerField(default=4)),
                ('layout_min_w', models.IntegerField(default=2)),
                ('layout_min_h', models.IntegerField(default=2)),
                ('layout_max_w', models.IntegerField(blank=True, null=True)),
                ('layout_max_h', models.IntegerField(blank=True, null=True)),
                ('background_color', models.CharField(blank=True, max_length=7)),
                ('border_color', models.CharField(blank=True, max_length=7)),
                ('text_color', models.CharField(blank=True, max_length=7)),
                ('custom_style', models.JSONField(default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('visibility_conditions', models.JSONField(default=dict)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'ordering': ['display_order', 'layout_y', 'layout_x'],
            },
        ),
        migrations.CreateModel(
            name='WidgetDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('identifier', models.CharField(help_text='Unique identifier (e.g., "student-count", "monthly-income")', max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('api', 'API Endpoint'), ('workflow', 'Workflow Execution'), ('query', 'Database Query'), ('calculation', 'Calculated Value'), ('static', 'Static Data')], max_length=20)),
                ('source_config', models.JSONField(default=dict, help_text='\n        Configuration varies by source_type:\n        \n        API:\n        {\n            "endpoint": "/api/widgets/students/count/",\n            "method": "GET",\n            "headers": {},\n            "params": {},\n            "response_path": "data.value"  // JSONPath to extract value\n        }\n        \n        Workflow:\n        {\n            "workflow_template_id": 123,\n            "input_params": {"period": "current_month"},\n            "output_field": "total"  // Which workflow output to use\n        }\n        \n        Query:\n        {\n            "model": "Client",\n            "filters": {"classification__code": "STUDENT", "status": "ACTIVE"},\n            "aggregation": {"count": "id"}\n        }\n        \n        Calculation:\n        {\n            "formula": "{{income}} - {{expenses}}",\n            "variables": {\n                "income": {"source": "monthly-income"},\n                "expenses": {"source": "monthly-expenses"}\n            }\n        }\n        \n        Static:\n        {\n            "value": 450,\n            "last_updated": "2025-01-15"\n        }\n        ')),
                ('cache_enabled', models.BooleanField(default=True)),
                ('cache_duration', models.IntegerField(default=300, help_text='Cache duration in seconds (0 = no cache)')),
                ('required_permission', models.CharField(blank=True, help_text='Permission required to access this data source', max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(default=list, help_text='Search tags')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'widget_data_sources',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Accessible by all users in branch')),
                ('logo', models.ImageField(blank=True, help_text='Dashboard logo (recommended: 200x60px)', null=True, upload_to='dashboards/logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])])),
                ('background_image', models.ImageField(blank=True, help_text='Background image (optional)', null=True, upload_to='dashboards/backgrounds/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
                ('background_opacity', models.FloatField(default=1.0, help_text='Background image opacity (0.0 to 1.0)')),
                ('grid_columns', models.IntegerField(default=12, help_text='Number of columns in grid (default: 12)')),
                ('layout_mode', models.CharField(choices=[('grid', 'Grid Layout'), ('masonry', 'Masonry Layout'), ('flex', 'Flexible Layout')], default='grid', max_length=20)),
                ('show_navigation', models.BooleanField(default=True, help_text='Show navigation bar on dashboard')),
                ('navigation_config', models.JSONField(default=dict, help_text='Navigation links and quick actions')),
                ('auto_refresh', models.BooleanField(default=False, help_text='Enable auto-refresh for all widgets')),
                ('refresh_interval', models.IntegerField(default=60, help_text='Auto-refresh interval in seconds')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for this dashboard')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
            ],
            options={
                'db_table': 'dashboards',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
