# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('assets', '0003_initial'),
        ('automations', '0002_initial'),
        ('branches', '0002_initial'),
        ('clients', '0002_initial'),
        ('inventory', '0001_initial'),
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='allocationredemption',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='assets.fixedasset'),
        ),
        migrations.AddField(
            model_name='allocationredemption',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_redemptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationredemption',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='allocationredemption',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationredemption',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allocationredemption',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='allocationredemption',
            name='transaction_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='transactions.transactionentry'),
        ),
        migrations.AddField(
            model_name='assetusagelog',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='assets.fixedasset'),
        ),
        migrations.AddField(
            model_name='assetusagelog',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='assetusagelog',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetusagelog',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetusagelog',
            name='redemption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='inventory.allocationredemption'),
        ),
        migrations.AddField(
            model_name='assetusagelog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='costlayerconsumption',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='costlayerconsumption',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costlayerconsumption',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costlayerconsumption',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='applied_by',
            field=models.ForeignKey(blank=True, help_text='User who applied the credit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_credit_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='client',
            field=models.ForeignKey(help_text='Customer receiving the credit', on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='clients.client'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_credit_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='reversed_by',
            field=models.ForeignKey(blank=True, help_text='User who reversed the credit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_credit_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='credit_note',
            field=models.ForeignKey(help_text='Parent credit note', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.creditnote'),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='inventoryallocation',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='inventoryallocation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_allocations', to='clients.client'),
        ),
        migrations.AddField(
            model_name='inventoryallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryallocation',
            name='linked_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='assets.fixedasset'),
        ),
        migrations.AddField(
            model_name='inventoryallocation',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryallocation',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='allocationredemption',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='inventory.inventoryallocation'),
        ),
        migrations.AddField(
            model_name='allocationitem',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventoryallocation'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='cogs_account',
            field=models.ForeignKey(help_text='Expense account for cost of goods sold', on_delete=django.db.models.deletion.PROTECT, related_name='cogs_categories', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='inventory_account',
            field=models.ForeignKey(help_text='Asset account for inventory valuation', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_categories', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='sales_account',
            field=models.ForeignKey(help_text='Income account for sales', on_delete=django.db.models.deletion.PROTECT, related_name='sales_categories', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='inventoryconfig',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='inventoryconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryconfig',
            name='default_adjustment_workflow',
            field=models.ForeignKey(blank=True, help_text='Default workflow for stock adjustments', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_configs', to='automations.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='inventoryconfig',
            name='default_delivery_workflow',
            field=models.ForeignKey(blank=True, help_text='Default workflow for deliveries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_configs', to='automations.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='inventoryconfig',
            name='default_sales_order_workflow',
            field=models.ForeignKey(blank=True, help_text='Default workflow for sales orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_configs', to='automations.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='inventoryconfig',
            name='default_transfer_workflow',
            field=models.ForeignKey(blank=True, help_text='Default workflow for stock transfers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_configs', to='automations.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='inventoryconfig',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='costlayerconsumption',
            name='cost_layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='inventory.inventorycostlayer'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventorycategory'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Inventory item (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='allocationitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this invoice belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_invoices_branch', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_invoices', to='clients.client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Invoice owner (tenant)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_invoices_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='inventoryallocation',
            name='invoice',
            field=models.ForeignKey(help_text='Invoice that funded this allocation', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_allocations', to='inventory.invoice'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='original_invoice',
            field=models.ForeignKey(help_text='Invoice being credited', on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='inventory.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='creditnoteitem',
            name='original_invoice_item',
            field=models.ForeignKey(blank=True, help_text='Original invoice item being credited', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_items', to='inventory.invoiceitem'),
        ),
        migrations.AddField(
            model_name='location',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='inventorycostlayer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='allocationredemption',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='redemptionitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemptionitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemption_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='redemptionitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redemptionitem',
            name='redemption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.allocationredemption'),
        ),
        migrations.AddField(
            model_name='redemptionitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sales_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='clients.client'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='inventory.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_adjustment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_requests', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_requests', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stockadjustmentrequest',
            name='stock_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_request', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='costlayerconsumption',
            name='movement',
            field=models.ForeignKey(help_text='The stock movement (sale/issue) that consumed this layer', on_delete=django.db.models.deletion.PROTECT, related_name='cost_consumptions', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_transfer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests_out', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests_in', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='transfer_in_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_in_request', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='transfer_out_movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_out_request', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='writeoffrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_writeoff_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writeoffrequest',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='writeoffrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writeoffrequest',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoff_requests', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='writeoffrequest',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoff_requests', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='writeoffrequest',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writeoffrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writeoff_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='writeoffrequest',
            name='stock_movement',
            field=models.ForeignKey(blank=True, help_text='Link to executed stock movement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writeoff_request', to='inventory.stockmovement'),
        ),
        migrations.AddField(
            model_name='writeoffrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddIndex(
            model_name='assetusagelog',
            index=models.Index(fields=['asset', 'log_date'], name='inventory_a_asset_i_132de6_idx'),
        ),
        migrations.AddIndex(
            model_name='assetusagelog',
            index=models.Index(fields=['is_anomaly'], name='inventory_a_is_anom_335fe4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorycategory',
            unique_together={('branch', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryconfig',
            unique_together={('owner', 'branch')},
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['sku'], name='inventory_i_sku_e27286_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['barcode'], name='inventory_i_barcode_c7bf0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('branch', 'sku')},
        ),
        migrations.AlterUniqueTogether(
            name='allocationitem',
            unique_together={('allocation', 'item')},
        ),
        migrations.AddIndex(
            model_name='inventoryallocation',
            index=models.Index(fields=['client', 'status'], name='inventory_i_client__4cfb68_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryallocation',
            index=models.Index(fields=['allocation_number'], name='inventory_i_allocat_cdead9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryallocation',
            index=models.Index(fields=['linked_asset', 'status'], name='inventory_i_linked__e1a69e_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['credit_note_number'], name='inventory_c_credit__824ff4_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['status'], name='inventory_c_status_86e223_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['issue_date'], name='inventory_c_issue_d_e30ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='creditnote',
            index=models.Index(fields=['applied_to_account'], name='inventory_c_applied_5f35e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False), models.Q(('code', ''), _negated=True)), fields=('branch', 'code'), name='unique_location_code_per_branch'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('branch', 'code')},
        ),
        migrations.AddIndex(
            model_name='inventorystock',
            index=models.Index(fields=['item', 'location'], name='inventory_i_item_id_cfab49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorystock',
            unique_together={('item', 'location')},
        ),
        migrations.AddIndex(
            model_name='inventorycostlayer',
            index=models.Index(fields=['item', 'location', 'is_depleted'], name='inventory_i_item_id_a90a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycostlayer',
            index=models.Index(fields=['transaction_reference'], name='inventory_i_transac_72e2cf_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycostlayer',
            index=models.Index(fields=['transaction_date'], name='inventory_i_transac_1ea13c_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationredemption',
            index=models.Index(fields=['allocation', 'redemption_date'], name='inventory_a_allocat_84fe32_idx'),
        ),
        migrations.AddIndex(
            model_name='allocationredemption',
            index=models.Index(fields=['asset', 'redemption_date'], name='inventory_a_asset_i_366b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['status', 'order_date'], name='inventory_s_status_d1a94a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['client', 'status'], name='inventory_s_client__fb6e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['item', 'movement_date'], name='inventory_s_item_id_c55b35_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reference_number'], name='inventory_s_referen_79719e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustmentrequest',
            index=models.Index(fields=['status', 'created_at'], name='inventory_s_status_73ff38_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustmentrequest',
            index=models.Index(fields=['requested_by'], name='inventory_s_request_144c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='costlayerconsumption',
            index=models.Index(fields=['movement'], name='inventory_c_movemen_dc3cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='costlayerconsumption',
            index=models.Index(fields=['cost_layer'], name='inventory_c_cost_la_f498ec_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransferrequest',
            index=models.Index(fields=['status', 'created_at'], name='inventory_s_status_aa96eb_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransferrequest',
            index=models.Index(fields=['requested_by'], name='inventory_s_request_44a2fe_idx'),
        ),
        migrations.AddIndex(
            model_name='writeoffrequest',
            index=models.Index(fields=['status', 'created_at'], name='inventory_w_status_8dbdac_idx'),
        ),
        migrations.AddIndex(
            model_name='writeoffrequest',
            index=models.Index(fields=['requested_by'], name='inventory_w_request_67cdc9_idx'),
        ),
    ]
