# Generated by Django 5.2.4 on 2026-02-01 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_add_posted_by_to_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='is_reservation_released',
            field=models.BooleanField(default=False, help_text='True if reservation has been released (posted or cancelled)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='reserved_from_location',
            field=models.ForeignKey(blank=True, help_text='Location where stock is reserved from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_invoice_items', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Quantity of stock reserved for this invoice item', max_digits=18),
        ),
    ]
