# Generated by Django 5.2.4 on 2026-02-04 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
        ('inventory', '0004_add_stock_reservation_to_invoice_item'),
        ('users', '0002_setup_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('count_number', models.CharField(db_index=True, help_text='Unique count reference number', max_length=50, unique=True)),
                ('count_date', models.DateField(help_text='Date when physical count was performed')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the count was reviewed', null=True)),
                ('total_lines', models.IntegerField(default=0, help_text='Total number of items counted')),
                ('total_variance_value', models.DecimalField(decimal_places=2, default=0, help_text='Total value of all variances', max_digits=18)),
                ('notes', models.TextField(blank=True, help_text='General notes about the count')),
                ('review_notes', models.TextField(blank=True, help_text='Notes from reviewer')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('counted_by', models.ForeignKey(help_text='User who performed the count', on_delete=django.db.models.deletion.PROTECT, related_name='physical_counts_performed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Location where count was performed', on_delete=django.db.models.deletion.PROTECT, related_name='physical_counts', to='inventory.location')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed and approved the count', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_counts_reviewed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['-count_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('system_quantity', models.DecimalField(decimal_places=2, help_text='Quantity per system at count date', max_digits=18)),
                ('counted_quantity', models.DecimalField(decimal_places=2, help_text='Actual physical count', max_digits=18)),
                ('variance', models.DecimalField(decimal_places=2, help_text='Counted - System (positive = surplus, negative = shortage)', max_digits=18)),
                ('variance_percent', models.DecimalField(decimal_places=2, default=0, help_text='Variance as percentage of system quantity', max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit at count date', max_digits=18)),
                ('variance_value', models.DecimalField(decimal_places=2, help_text='Variance quantity * unit cost', max_digits=18)),
                ('variance_reason', models.CharField(blank=True, choices=[('shrinkage', 'Shrinkage/Loss'), ('damage', 'Damage'), ('obsolete', 'Obsolete'), ('theft', 'Theft'), ('counting_error', 'Counting Error'), ('system_error', 'System Error'), ('surplus', 'Surplus/Found'), ('other', 'Other')], help_text='Reason for variance', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes about this count line')),
                ('adjustment_posted', models.BooleanField(default=False, help_text='Whether variance adjustment has been posted')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physical_count_lines', to='inventory.inventoryitem')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('physical_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_lines', to='inventory.physicalcount')),
                ('stock_movement', models.ForeignKey(blank=True, help_text='Link to stock adjustment if posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical_count_line', to='inventory.stockmovement')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='physicalcount',
            index=models.Index(fields=['count_date', 'location'], name='inventory_p_count_d_e8c498_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalcount',
            index=models.Index(fields=['status', 'count_date'], name='inventory_p_status_efd8d8_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalcount',
            index=models.Index(fields=['counted_by'], name='inventory_p_counted_351bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalcountline',
            index=models.Index(fields=['physical_count', 'item'], name='inventory_p_physica_8890de_idx'),
        ),
        migrations.AddIndex(
            model_name='physicalcountline',
            index=models.Index(fields=['variance_reason'], name='inventory_p_varianc_a88269_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='physicalcountline',
            unique_together={('physical_count', 'item')},
        ),
    ]
