# Generated by Django 5.2.4 on 2026-03-01 09:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_latitude_branch_longitude'),
        ('clients', '0005_client_lga_client_previous_school_name_and_more'),
        ('incomes', '0007_add_service_type_to_serviceitem'),
        ('inventory', '0005_physicalcount_physicalcountline_and_more'),
        ('users', '0003_role_permission_codes_user_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycategory',
            name='item_type',
            field=models.CharField(blank=True, default='', help_text="Broad item-type label for this category, e.g. 'Book', 'Uniform', 'Stationery'. Used to authorise material requests by type rather than by individual category code.", max_length=100),
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('request_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('purpose', models.TextField(help_text='Purpose/reason for requesting these items')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('client', models.ForeignKey(help_text='Client requesting the items', on_delete=django.db.models.deletion.PROTECT, related_name='material_requests', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('delivery_location', models.ForeignKey(help_text='Location where items will be delivered/collected', on_delete=django.db.models.deletion.PROTECT, related_name='material_requests', to='inventory.location')),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests_fulfilled', to=settings.AUTH_USER_MODEL)),
                ('inventory_invoice', models.ForeignKey(blank=True, help_text='Inventory invoice generated when request is fulfilled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests', to='inventory.invoice')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='Staff who created this material request', on_delete=django.db.models.deletion.PROTECT, related_name='material_requests_created', to=settings.AUTH_USER_MODEL)),
                ('service_invoice', models.ForeignKey(blank=True, help_text='Service invoice that authorizes this material request', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_requests', to='incomes.invoice')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity requested', max_digits=18)),
                ('approved_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity approved (may differ from requested)', max_digits=18, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_request_items', to='inventory.inventoryitem')),
                ('material_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.materialrequest')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['request_number'], name='inventory_m_request_926f87_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['status'], name='inventory_m_status_a8edfb_idx'),
        ),
        migrations.AddIndex(
            model_name='materialrequest',
            index=models.Index(fields=['client'], name='inventory_m_client__aa2e47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialrequestitem',
            unique_together={('material_request', 'item')},
        ),
    ]
