# Generated by Django 5.2.4 on 2026-03-20 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_make_inventory_category_sales_account_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='request_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
