# Generated by Django 5.2.4 on 2026-03-30 09:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bank_account_fk_on_expense_and_replenishment'),
        ('branches', '0004_add_contact_fields_and_invoice_bank_flag'),
        ('inventory', '0008_alter_materialrequest_request_date'),
        ('transactions', '0005_remove_workflow_reference_unique_together'),
        ('users', '0007_tenant_domainconfig_customlabels_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeUseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('request_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('department', models.CharField(blank=True, help_text='Department or cost centre requesting the items', max_length=120)),
                ('purpose', models.TextField(help_text='Purpose / reason for this request')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_use_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('delivery_location', models.ForeignKey(help_text='Inventory location where items will be issued from', on_delete=django.db.models.deletion.PROTECT, related_name='office_use_requests', to='inventory.location')),
                ('expense_account', models.ForeignKey(help_text='GL expense account to debit when this request is fulfilled', on_delete=django.db.models.deletion.PROTECT, related_name='office_use_requests', to='accounts.account')),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_use_requests_fulfilled', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry generated when request is fulfilled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_use_requests', to='transactions.transaction')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_use_requests_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='Staff member who created/submitted this request', on_delete=django.db.models.deletion.PROTECT, related_name='office_use_requests_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeUseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_use_request_items', to='inventory.inventoryitem')),
                ('office_use_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.officeuserequest')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='officeuserequest',
            index=models.Index(fields=['request_number'], name='inventory_o_request_4e500e_idx'),
        ),
        migrations.AddIndex(
            model_name='officeuserequest',
            index=models.Index(fields=['status'], name='inventory_o_status_f5c749_idx'),
        ),
        migrations.AddIndex(
            model_name='officeuserequest',
            index=models.Index(fields=['requested_by'], name='inventory_o_request_db3d27_idx'),
        ),
    ]
