# Generated by Django 5.2.4 on 2026-04-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_officeuserrequest_cancel_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase Receipt'), ('sale', 'Sales Delivery'), ('adjustment', 'Stock Adjustment'), ('transfer', 'Transfer'), ('return_in', 'Purchase Return'), ('return_out', 'Sales Return'), ('write_off', 'Write Off'), ('production_in', 'Production Receipt'), ('production_out', 'Production Issue'), ('office_use', 'Office Use Issue')], max_length=20),
        ),
    ]
