# Generated by Django 5.2.4 on 2026-07-30 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_code'),
        ('inventory', '0011_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeuserequest',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text="Deprecated. Expense account is now derived from each item's category.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='office_use_requests', to='accounts.account'),
        ),
    ]
