# Generated by Django 5.2.4 on 2026-07-31 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_insurance_verifier_disbursement'),
        ('inventory', '0012_office_use_request_expense_account_optional'),
        ('transactions', '0006_fix_empty_sequence_names'),
        ('users', '0011_alter_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransferrequest',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_transfer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='acknowledgment_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_acknowledgments', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='acknowledgment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='actual_quantity_received',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='destination_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests_received', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='dispatch_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_dispatches', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='dispatch_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='dispatched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_transfer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='disputed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputed_transfer_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='from_branch',
            field=models.ForeignKey(blank=True, help_text='Denormalized from from_location.branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='to_branch',
            field=models.ForeignKey(blank=True, help_text='Denormalized from to_location.branch', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='variance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='variance_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='quantity - actual_quantity_received; positive = shortfall', max_digits=18),
        ),
        migrations.AlterField(
            model_name='stocktransferrequest',
            name='item',
            field=models.ForeignKey(help_text="The source branch's item record being sent", on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='stocktransferrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched / In Transit'), ('acknowledged', 'Acknowledged / Completed'), ('short_received', 'Short Received (Variance)'), ('disputed', 'Disputed'), ('executed', 'Executed (Legacy)')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='stocktransferrequest',
            index=models.Index(fields=['from_branch', 'status'], name='inventory_s_from_br_cf8028_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransferrequest',
            index=models.Index(fields=['to_branch', 'status'], name='inventory_s_to_bran_00b24d_idx'),
        ),
    ]
