# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_number', models.CharField(db_index=True, help_text='Unique identifier for this cash account', max_length=50, unique=True)),
                ('name', models.CharField(help_text="Descriptive name (e.g., 'Main Cashier', 'Agent A', 'Till 1')", max_length=200)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current cash on hand - must be zero at day end', max_digits=18)),
                ('daily_collection_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount this cashier can collect per day', max_digits=18, null=True)),
                ('requires_dual_approval', models.BooleanField(default=False, help_text='Requires two approvers for cash transfers')),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False, help_text='Temporarily suspended from collecting cash')),
                ('last_reconciled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cashier Account',
                'verbose_name_plural': 'Cashier Accounts',
            },
        ),
        migrations.CreateModel(
            name='CashReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reconciliation_date', models.DateField(default=django.utils.timezone.now)),
                ('system_balance', models.DecimalField(decimal_places=2, help_text='Balance according to system', max_digits=18)),
                ('physical_count', models.DecimalField(decimal_places=2, help_text='Actual cash counted', max_digits=18)),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Difference between system and physical count', max_digits=18)),
                ('denomination_details', models.JSONField(blank=True, default=dict, help_text='Breakdown by currency denomination')),
                ('total_collections', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_transfers', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('status', models.CharField(choices=[('balanced', 'Balanced'), ('variance', 'Has Variance'), ('resolved', 'Variance Resolved')], default='balanced', max_length=20)),
                ('variance_explanation', models.TextField(blank=True, help_text='Explanation for any variance')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-reconciliation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('transfer_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount being transferred', max_digits=18)),
                ('bank_deposit_slip', models.CharField(blank=True, help_text='Bank deposit slip/teller number', max_length=100)),
                ('bank_reference', models.CharField(blank=True, help_text='Bank transaction reference', max_length=100)),
                ('deposit_proof', models.FileField(blank=True, help_text='Upload bank deposit slip/receipt', null=True, upload_to='cash_transfers/deposits/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted to Accounts')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('second_approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('receipt_number', models.CharField(db_index=True, help_text='Official receipt number', max_length=50, unique=True)),
                ('collection_date', models.DateField(default=django.utils.timezone.now, help_text='Date cash was collected')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Amount that was supposed to be paid', max_digits=18)),
                ('amount_collected', models.DecimalField(decimal_places=2, help_text='Actual amount collected from client', max_digits=18)),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Difference between due and collected (can be overpayment or underpayment)', max_digits=18)),
                ('variance_action', models.CharField(choices=[('none', 'No Variance'), ('savings', 'Credit to Client Savings'), ('debt', 'Add to Client Debt'), ('waive', 'Waive Difference'), ('refund', 'Refund to Client')], default='none', max_length=20)),
                ('payment_purpose', models.CharField(help_text="Purpose of payment (e.g., 'Loan Payment', 'Tuition Fee', 'Product Purchase')", max_length=200)),
                ('reference_number', models.CharField(blank=True, help_text='Reference to the actual transaction/invoice', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('collection_mode', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_deposit', 'Bank Deposit'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('is_posted', models.BooleanField(default=False, help_text='Whether this collection has been posted to accounts')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
            ],
            options={
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
    ]
