# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash_management', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    def add_client_field(apps, schema_editor):
        """
        Add the client FK column only if it doesn't already exist in the table.
        This guards against databases where the column was created out-of-band.
        """
        connection = schema_editor.connection
        table_name = 'cash_management_cashcollection'

        try:
            with connection.cursor() as cursor:
                existing = [col.name for col in connection.introspection.get_table_description(cursor, table_name)]
        except Exception:
            # If introspection fails, re-raise so migration fails loudly
            raise

        if 'client_id' in existing:
            # Already present - nothing to do
            return

        # Use the historical models from apps to construct the field
        CashCollection = apps.get_model('cash_management', 'CashCollection')
        Client = apps.get_model('clients', 'Client')

        # Create a ForeignKey field instance and attach it to the model
        field = models.ForeignKey(
            Client,
            on_delete=django.db.models.deletion.PROTECT,
            related_name='cash_collections'
        )
        field.set_attributes_from_name('client')

        # Add the field via the schema editor
        schema_editor.add_field(CashCollection, field)


    operations = [
        migrations.RunPython(add_client_field, migrations.RunPython.noop),
    ]
