# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('branches', '0002_initial'),
        ('cash_management', '0002_initial'),
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def add_missing_fk_columns(apps, schema_editor):
        connection = schema_editor.connection

        # Helper to check if a table has a column
        def has_column(table_name, column_name):
            try:
                with connection.cursor() as cursor:
                    cols = [c.name for c in connection.introspection.get_table_description(cursor, table_name)]
                return column_name in cols
            except Exception:
                # If introspection fails, be conservative and return False
                return False

        # Map of (table_name, field_name) -> (model_label, target_app_label, target_model_name, field_kwargs)
        checks = [
            ('cash_management_cashcollection', 'created_by', ('cash_management', 'CashCollection'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': '%(class)s_created', 'help_text': 'User who created this record', 'on_delete': django.db.models.deletion.PROTECT}),
            ('cash_management_cashcollection', 'journal_entry', ('cash_management', 'CashCollection'), ('transactions', 'Transaction'), {'null': True, 'blank': True, 'related_name': 'cash_collections', 'on_delete': django.db.models.deletion.PROTECT}),
            ('cash_management_cashcollection', 'owner', ('cash_management', 'CashCollection'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': '%(class)s_owned', 'help_text': 'User who owns/manages this record', 'on_delete': django.db.models.deletion.CASCADE}),
            ('cash_management_cashcollection', 'posted_by', ('cash_management', 'CashCollection'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': 'posted_cash_collections', 'on_delete': django.db.models.deletion.SET_NULL}),
            ('cash_management_cashcollection', 'tenant', ('cash_management', 'CashCollection'), ('users', 'Tenant'), {'null': True, 'blank': True, 'related_name': '%(app_label)s_%(class)s_set', 'help_text': 'Tenant (organization) this record belongs to', 'on_delete': django.db.models.deletion.CASCADE}),
            ('cash_management_cashieraccount', 'account', ('cash_management', 'CashierAccount'), ('accounts', 'Account'), {'related_name': 'cashier_accounts', 'help_text': "GL account for this cashier's collections (must be ASSET or LIABILITY type)", 'on_delete': django.db.models.deletion.PROTECT}),
            ('cash_management_cashieraccount', 'branch', ('cash_management', 'CashierAccount'), ('branches', 'Branch'), {'null': True, 'blank': True, 'help_text': 'Branch this record belongs to', 'on_delete': django.db.models.deletion.SET_NULL}),
            ('cash_management_cashieraccount', 'cashier', ('cash_management', 'CashierAccount'), (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': 'cashier_accounts', 'help_text': 'User responsible for this cash collection point', 'on_delete': django.db.models.deletion.PROTECT}),
            ('cash_management_cashieraccount', 'created_by', ('cash_management', 'CashierAccount'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': '%(class)s_created', 'help_text': 'User who created this record', 'on_delete': django.db.models.deletion.PROTECT}),
            ('cash_management_cashieraccount', 'last_reconciled_by', ('cash_management', 'CashierAccount'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': 'reconciled_cashier_accounts', 'on_delete': django.db.models.deletion.SET_NULL}),
            ('cash_management_cashieraccount', 'owner', ('cash_management', 'CashierAccount'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': '%(class)s_owned', 'on_delete': django.db.models.deletion.CASCADE}),
            ('cash_management_cashieraccount', 'tenant', ('cash_management', 'CashierAccount'), ('users', 'Tenant'), {'null': True, 'blank': True, 'related_name': '%(app_label)s_%(class)s_set', 'on_delete': django.db.models.deletion.CASCADE}),
            ('cash_management_cashcollection', 'cashier_account', ('cash_management', 'CashCollection'), ('cash_management', 'CashierAccount'), {'related_name': 'cash_collections', 'on_delete': django.db.models.deletion.PROTECT}),
            ('cash_management_cashreconciliation', 'branch', ('cash_management', 'CashReconciliation'), ('branches', 'Branch'), {'null': True, 'blank': True, 'help_text': 'Branch this record belongs to', 'on_delete': django.db.models.deletion.SET_NULL}),
            ('cash_management_cashreconciliation', 'cashier_account', ('cash_management', 'CashReconciliation'), ('cash_management', 'CashierAccount'), {'related_name': 'reconciliations', 'on_delete': django.db.models.deletion.PROTECT}),
            ('cash_management_cashreconciliation', 'created_by', ('cash_management', 'CashReconciliation'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': '%(class)s_created', 'help_text': 'User who created this record', 'on_delete': django.db.models.deletion.PROTECT}),
            ('cash_management_cashreconciliation', 'owner', ('cash_management', 'CashReconciliation'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': '%(class)s_owned', 'on_delete': django.db.models.deletion.CASCADE}),
            ('cash_management_cashreconciliation', 'reconciled_by', ('cash_management', 'CashReconciliation'), ('users', 'User'), {'related_name': 'performed_reconciliations', 'on_delete': django.db.models.deletion.PROTECT}),
            ('cash_management_cashreconciliation', 'tenant', ('cash_management', 'CashReconciliation'), ('users', 'Tenant'), {'null': True, 'blank': True, 'related_name': '%(app_label)s_%(class)s_set', 'on_delete': django.db.models.deletion.CASCADE}),
            ('cash_management_cashreconciliation', 'verified_by', ('cash_management', 'CashReconciliation'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': 'verified_reconciliations', 'on_delete': django.db.models.deletion.SET_NULL}),
            ('cash_management_cashtransfer', 'approved_by', ('cash_management', 'CashTransfer'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': 'approved_cash_transfers', 'on_delete': django.db.models.deletion.SET_NULL}),
            ('cash_management_cashtransfer', 'branch', ('cash_management', 'CashTransfer'), ('branches', 'Branch'), {'null': True, 'blank': True, 'help_text': 'Branch this record belongs to', 'on_delete': django.db.models.deletion.SET_NULL}),
            ('cash_management_cashtransfer', 'cashier_account', ('cash_management', 'CashTransfer'), ('cash_management', 'CashierAccount'), {'related_name': 'cash_transfers', 'on_delete': django.db.models.deletion.PROTECT}),
            ('cash_management_cashtransfer', 'created_by', ('cash_management', 'CashTransfer'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': '%(class)s_created', 'help_text': 'User who created this record', 'on_delete': django.db.models.deletion.PROTECT}),
            ('cash_management_cashtransfer', 'destination_account', ('cash_management', 'CashTransfer'), ('accounts', 'Account'), {'help_text': 'Main bank account receiving the cash', 'on_delete': django.db.models.deletion.PROTECT}),
            ('cash_management_cashtransfer', 'journal_entry', ('cash_management', 'CashTransfer'), ('transactions', 'Transaction'), {'null': True, 'blank': True, 'related_name': 'cash_transfers', 'on_delete': django.db.models.deletion.PROTECT}),
            ('cash_management_cashtransfer', 'owner', ('cash_management', 'CashTransfer'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': '%(class)s_owned', 'on_delete': django.db.models.deletion.CASCADE}),
            ('cash_management_cashtransfer', 'posted_by', ('cash_management', 'CashTransfer'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': 'posted_cash_transfers', 'on_delete': django.db.models.deletion.SET_NULL}),
            ('cash_management_cashtransfer', 'rejected_by', ('cash_management', 'CashTransfer'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': 'rejected_cash_transfers', 'on_delete': django.db.models.deletion.SET_NULL}),
            ('cash_management_cashtransfer', 'second_approved_by', ('cash_management', 'CashTransfer'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': 'second_approved_cash_transfers', 'on_delete': django.db.models.deletion.SET_NULL}),
            ('cash_management_cashtransfer', 'submitted_by', ('cash_management', 'CashTransfer'), ('users', 'User'), {'null': True, 'blank': True, 'related_name': 'submitted_cash_transfers', 'on_delete': django.db.models.deletion.SET_NULL}),
            ('cash_management_cashtransfer', 'tenant', ('cash_management', 'CashTransfer'), ('users', 'Tenant'), {'null': True, 'blank': True, 'related_name': '%(app_label)s_%(class)s_set', 'on_delete': django.db.models.deletion.CASCADE}),
        ]

        for table_name, column_name, model_label, target_model, fk_kwargs in checks:
            if has_column(table_name, column_name):
                continue

            # model_label: (app_label, model_name)
            app_label, model_name = model_label
            target_app, target_model_name = target_model
            Model = apps.get_model(app_label, model_name)
            Target = apps.get_model(target_app, target_model_name)

            # Build ForeignKey field, ensure `on_delete` is passed to constructor
            on_delete = fk_kwargs.get('on_delete', django.db.models.deletion.PROTECT)
            field_kwargs = {k: v for k, v in fk_kwargs.items() if k != 'on_delete'}
            field = models.ForeignKey(Target, on_delete=on_delete, **field_kwargs)

            field.set_attributes_from_name(column_name)

            # Add field to the model table
            try:
                schema_editor.add_field(Model, field)
            except Exception:
                # If we cannot add the field programmatically, skip and continue
                continue

    def create_indexes_and_uniques(apps, schema_editor):
        # Create indexes and unique constraints only when all referenced fields exist
        def model_has_fields(model, field_names):
            for fname in field_names:
                try:
                    model._meta.get_field(fname)
                except Exception:
                    return False
            return True

        # Define index/unique specs: (app_label, model_name, kind, spec)
        # kind: 'index' -> spec = {'fields': [...], 'name': '...'}
        # kind: 'unique' -> spec = {'fields': [...], 'name': '...'}
        specs = [
            ('cash_management', 'CashierAccount', 'index', {'fields': ['account_number'], 'name': 'cash_manage_account_699a1f_idx'}),
            ('cash_management', 'CashierAccount', 'index', {'fields': ['cashier', 'is_active'], 'name': 'cash_manage_cashier_d817cf_idx'}),
            ('cash_management', 'CashierAccount', 'index', {'fields': ['current_balance'], 'name': 'cash_manage_current_8448b2_idx'}),
            ('cash_management', 'CashierAccount', 'unique', {'fields': ['branch', 'cashier', 'account_number'], 'name': 'cash_manage_branch_cashier_acc_uq'}),
            ('cash_management', 'CashCollection', 'index', {'fields': ['receipt_number'], 'name': 'cash_manage_receipt_3ee633_idx'}),
            ('cash_management', 'CashCollection', 'index', {'fields': ['collection_date', 'cashier_account'], 'name': 'cash_manage_collect_252d3f_idx'}),
            ('cash_management', 'CashCollection', 'index', {'fields': ['client', 'collection_date'], 'name': 'cash_manage_client__3da805_idx'}),
            ('cash_management', 'CashCollection', 'index', {'fields': ['is_posted'], 'name': 'cash_manage_is_post_94a1df_idx'}),
            ('cash_management', 'CashReconciliation', 'index', {'fields': ['reconciliation_date', 'cashier_account'], 'name': 'cash_manage_reconci_3cd0a6_idx'}),
            ('cash_management', 'CashReconciliation', 'index', {'fields': ['status'], 'name': 'cash_manage_status_8b3ac4_idx'}),
            ('cash_management', 'CashTransfer', 'index', {'fields': ['transfer_number'], 'name': 'cash_manage_transfe_bd22ef_idx'}),
            ('cash_management', 'CashTransfer', 'index', {'fields': ['transfer_date', 'status'], 'name': 'cash_manage_transfe_b4e2d2_idx'}),
            ('cash_management', 'CashTransfer', 'index', {'fields': ['cashier_account', 'status'], 'name': 'cash_manage_cashier_05a923_idx'}),
        ]

        for app_label, model_name, kind, spec in specs:
            try:
                Model = apps.get_model(app_label, model_name)
            except LookupError:
                continue

            if not model_has_fields(Model, spec['fields']):
                # skip creating this index/constraint if any field is missing
                continue

            try:
                if kind == 'index':
                    idx = models.Index(fields=spec['fields'], name=spec['name'])
                    schema_editor.add_index(Model, idx)
                elif kind == 'unique':
                    constraint = models.UniqueConstraint(fields=spec['fields'], name=spec['name'])
                    schema_editor.add_constraint(Model, constraint)
            except Exception:
                # best-effort: skip failures to avoid aborting migration
                continue

    operations = [
        migrations.RunPython(add_missing_fk_columns, migrations.RunPython.noop),
        migrations.RunPython(create_indexes_and_uniques, migrations.RunPython.noop),
    ]
