# Generated by Django 5.2.4 on 2026-02-16 12:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.db.migrations.operations.special import SeparateDatabaseAndState


def add_cashier_account_if_missing(apps, schema_editor):
    connection = schema_editor.connection

    def has_column(table_name, column_name):
        try:
            with connection.cursor() as cursor:
                cols = [c.name for c in connection.introspection.get_table_description(cursor, table_name)]
            return column_name in cols
        except Exception:
            return False

    # Postgres uses column name with _id for FK fields
    if has_column('cash_management_cashcollection', 'cashier_account_id'):
        return

    Model = apps.get_model('cash_management', 'CashCollection')
    Target = apps.get_model('cash_management', 'CashierAccount')

    field = models.ForeignKey(Target, on_delete=django.db.models.deletion.PROTECT, related_name='cash_collections', null=True, blank=True)
    field.set_attributes_from_name('cashier_account')

    try:
        schema_editor.add_field(Model, field)
    except Exception:
        # Best-effort: if adding fails (e.g., column exists race), skip
        pass


def add_client_if_missing(apps, schema_editor):
    connection = schema_editor.connection

    def has_column(table_name, column_name):
        try:
            with connection.cursor() as cursor:
                cols = [c.name for c in connection.introspection.get_table_description(cursor, table_name)]
            return column_name in cols
        except Exception:
            return False

    if has_column('cash_management_cashcollection', 'client_id'):
        return

    Model = apps.get_model('cash_management', 'CashCollection')
    Target = apps.get_model('clients', 'Client')

    field = models.ForeignKey(Target, on_delete=django.db.models.deletion.PROTECT, related_name='cash_collections', null=True, blank=True)
    field.set_attributes_from_name('client')

    try:
        schema_editor.add_field(Model, field)
    except Exception:
        pass


def add_missing_cashcollection_fks(apps, schema_editor):
    connection = schema_editor.connection

    def has_column(table_name, column_name):
        try:
            with connection.cursor() as cursor:
                cols = [c.name for c in connection.introspection.get_table_description(cursor, table_name)]
            return column_name in cols
        except Exception:
            return False

    table = 'cash_management_cashcollection'
    specs = [
        ('cashier_account', ('cash_management', 'CashierAccount'), {'related_name': 'cash_collections', 'on_delete': django.db.models.deletion.PROTECT}),
        ('client', ('clients', 'Client'), {'related_name': 'cash_collections', 'on_delete': django.db.models.deletion.PROTECT}),
        ('created_by', ('users', 'User'), {'related_name': '%(class)s_created', 'on_delete': django.db.models.deletion.PROTECT}),
        ('journal_entry', ('transactions', 'Transaction'), {'related_name': 'cash_collections', 'on_delete': django.db.models.deletion.PROTECT}),
        ('owner', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': '%(class)s_owned', 'on_delete': django.db.models.deletion.CASCADE}),
        ('posted_by', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': 'posted_cash_collections', 'on_delete': django.db.models.deletion.SET_NULL}),
        ('tenant', ('users', 'Tenant'), {'related_name': '%(app_label)s_%(class)s_set', 'on_delete': django.db.models.deletion.CASCADE}),
    ]

    Model = apps.get_model('cash_management', 'CashCollection')

    for field_name, target, fk_kwargs in specs:
        col = f"{field_name}_id"
        if has_column(table, col):
            continue

        # resolve target model
        if isinstance(target, tuple):
            target_app, target_model = target
        else:
            target_app, target_model = target

        try:
            Target = apps.get_model(target_app, target_model)
        except Exception:
            # if target model can't be resolved, skip
            continue

        on_delete = fk_kwargs.get('on_delete', django.db.models.deletion.PROTECT)
        field_kwargs = {k: v for k, v in fk_kwargs.items() if k != 'on_delete'}
        field = models.ForeignKey(Target, on_delete=on_delete, null=True, blank=True, **field_kwargs)
        field.set_attributes_from_name(field_name)

        try:
            schema_editor.add_field(Model, field)
        except Exception:
            # skip failures to avoid aborting migration
            continue


def add_missing_cashtransfer_fks(apps, schema_editor):
    connection = schema_editor.connection

    def has_column(table_name, column_name):
        try:
            with connection.cursor() as cursor:
                cols = [c.name for c in connection.introspection.get_table_description(cursor, table_name)]
            return column_name in cols
        except Exception:
            return False

    table = 'cash_management_cashtransfer'
    specs = [
        ('approved_by', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': 'approved_cash_transfers', 'on_delete': django.db.models.deletion.SET_NULL}),
        ('branch', ('branches', 'Branch'), {'on_delete': django.db.models.deletion.SET_NULL}),
        ('cashier_account', ('cash_management', 'CashierAccount'), {'related_name': 'cash_transfers', 'on_delete': django.db.models.deletion.PROTECT}),
        ('created_by', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': '%(class)s_created', 'on_delete': django.db.models.deletion.PROTECT}),
        ('destination_account', ('accounts', 'Account'), {'related_name': 'cash_transfers_received', 'on_delete': django.db.models.deletion.PROTECT}),
        ('journal_entry', ('transactions', 'Transaction'), {'related_name': 'cash_transfers', 'on_delete': django.db.models.deletion.PROTECT}),
        ('owner', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': '%(class)s_owned', 'on_delete': django.db.models.deletion.CASCADE}),
        ('posted_by', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': 'posted_cash_transfers', 'on_delete': django.db.models.deletion.SET_NULL}),
        ('rejected_by', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': 'rejected_cash_transfers', 'on_delete': django.db.models.deletion.SET_NULL}),
        ('second_approved_by', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': 'second_approved_cash_transfers', 'on_delete': django.db.models.deletion.SET_NULL}),
        ('submitted_by', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': 'submitted_cash_transfers', 'on_delete': django.db.models.deletion.SET_NULL}),
        ('tenant', ('users', 'Tenant'), {'related_name': '%(app_label)s_%(class)s_set', 'on_delete': django.db.models.deletion.CASCADE}),
    ]

    Model = apps.get_model('cash_management', 'CashTransfer')

    for field_name, target, fk_kwargs in specs:
        col = f"{field_name}_id"
        if has_column(table, col):
            continue

        try:
            target_app, target_model = target
        except Exception:
            continue

        try:
            Target = apps.get_model(target_app, target_model)
        except Exception:
            continue

        on_delete = fk_kwargs.get('on_delete', django.db.models.deletion.PROTECT)
        field_kwargs = {k: v for k, v in fk_kwargs.items() if k != 'on_delete'}
        field = models.ForeignKey(Target, on_delete=on_delete, null=True, blank=True, **field_kwargs)
        field.set_attributes_from_name(field_name)

        try:
            schema_editor.add_field(Model, field)
        except Exception:
            continue


def add_missing_cashieraccount_fks(apps, schema_editor):
    connection = schema_editor.connection

    def has_column(table_name, column_name):
        try:
            with connection.cursor() as cursor:
                cols = [c.name for c in connection.introspection.get_table_description(cursor, table_name)]
            return column_name in cols
        except Exception:
            return False

    table = 'cash_management_cashieraccount'
    specs = [
        ('account', ('accounts', 'Account'), {'related_name': 'cashier_accounts', 'on_delete': django.db.models.deletion.PROTECT}),
        ('branch', ('branches', 'Branch'), {'on_delete': django.db.models.deletion.SET_NULL}),
        ('cashier', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': 'cashier_accounts', 'on_delete': django.db.models.deletion.PROTECT}),
        ('created_by', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': '%(class)s_created', 'on_delete': django.db.models.deletion.PROTECT}),
        ('last_reconciled_by', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': 'reconciled_cashier_accounts', 'on_delete': django.db.models.deletion.SET_NULL}),
        ('owner', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': '%(class)s_owned', 'on_delete': django.db.models.deletion.CASCADE}),
        ('tenant', ('users', 'Tenant'), {'related_name': '%(app_label)s_%(class)s_set', 'on_delete': django.db.models.deletion.CASCADE}),
    ]

    Model = apps.get_model('cash_management', 'CashierAccount')

    for field_name, target, fk_kwargs in specs:
        col = f"{field_name}_id"
        if has_column(table, col):
            continue

        try:
            target_app, target_model = target
        except Exception:
            continue

        try:
            Target = apps.get_model(target_app, target_model)
        except Exception:
            continue

        on_delete = fk_kwargs.get('on_delete', django.db.models.deletion.PROTECT)
        field_kwargs = {k: v for k, v in fk_kwargs.items() if k != 'on_delete'}
        field = models.ForeignKey(Target, on_delete=on_delete, null=True, blank=True, **field_kwargs)
        field.set_attributes_from_name(field_name)

        try:
            schema_editor.add_field(Model, field)
        except Exception:
            continue


def add_branch_to_cashreconciliation_if_missing(apps, schema_editor):
    connection = schema_editor.connection

    def has_column(table_name, column_name):
        try:
            with connection.cursor() as cursor:
                cols = [c.name for c in connection.introspection.get_table_description(cursor, table_name)]
            return column_name in cols
        except Exception:
            return False

    table = 'cash_management_cashreconciliation'
    if has_column(table, 'branch_id'):
        return

    Model = apps.get_model('cash_management', 'CashReconciliation')
    try:
        Target = apps.get_model('branches', 'Branch')
    except Exception:
        return

    field = models.ForeignKey(Target, on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, help_text='Branch this record belongs to')
    field.set_attributes_from_name('branch')

    try:
        schema_editor.add_field(Model, field)
    except Exception:
        # best-effort: skip if unable to add (column exists or race)
        pass


def add_cashier_account_to_cashreconciliation_if_missing(apps, schema_editor):
    connection = schema_editor.connection

    def has_column(table_name, column_name):
        try:
            with connection.cursor() as cursor:
                cols = [c.name for c in connection.introspection.get_table_description(cursor, table_name)]
            return column_name in cols
        except Exception:
            return False

    table = 'cash_management_cashreconciliation'
    if has_column(table, 'cashier_account_id'):
        return

    Model = apps.get_model('cash_management', 'CashReconciliation')
    try:
        Target = apps.get_model('cash_management', 'CashierAccount')
    except Exception:
        return

    field = models.ForeignKey(Target, on_delete=django.db.models.deletion.PROTECT, null=True, blank=True, related_name='reconciliations')
    field.set_attributes_from_name('cashier_account')

    try:
        schema_editor.add_field(Model, field)
    except Exception:
        # best-effort: skip if unable to add (column exists or race)
        pass


def add_missing_cashreconciliation_fks(apps, schema_editor):
    connection = schema_editor.connection

    def has_column(table_name, column_name):
        try:
            with connection.cursor() as cursor:
                cols = [c.name for c in connection.introspection.get_table_description(cursor, table_name)]
            return column_name in cols
        except Exception:
            return False

    table = 'cash_management_cashreconciliation'
    specs = [
        ('cashier_account', ('cash_management', 'CashierAccount'), {'related_name': 'reconciliations', 'on_delete': django.db.models.deletion.PROTECT}),
        ('created_by', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': '%(class)s_created', 'on_delete': django.db.models.deletion.PROTECT}),
        ('owner', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': '%(class)s_owned', 'on_delete': django.db.models.deletion.CASCADE}),
        ('reconciled_by', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': 'performed_reconciliations', 'on_delete': django.db.models.deletion.PROTECT}),
        ('tenant', ('users', 'Tenant'), {'related_name': '%(app_label)s_%(class)s_set', 'on_delete': django.db.models.deletion.CASCADE}),
        ('verified_by', (settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1]), {'related_name': 'verified_reconciliations', 'on_delete': django.db.models.deletion.SET_NULL}),
    ]

    Model = apps.get_model('cash_management', 'CashReconciliation')

    for field_name, target, fk_kwargs in specs:
        col = f"{field_name}_id"
        if has_column(table, col):
            continue

        # resolve target model
        try:
            target_app, target_model = target
        except Exception:
            continue

        try:
            Target = apps.get_model(target_app, target_model)
        except Exception:
            continue

        on_delete = fk_kwargs.get('on_delete', django.db.models.deletion.PROTECT)
        field_kwargs = {k: v for k, v in fk_kwargs.items() if k != 'on_delete'}
        field = models.ForeignKey(Target, on_delete=on_delete, null=True, blank=True, **field_kwargs)
        field.set_attributes_from_name(field_name)

        try:
            schema_editor.add_field(Model, field)
        except Exception:
            # skip failures to avoid aborting migration
            continue


def add_indexes_if_missing(apps, schema_editor):
    """
    Add all indexes, but skip if they already exist.
    This prevents DuplicateTable errors when indexes were already created.
    """
    connection = schema_editor.connection
    
    def index_exists(table_name, index_name):
        """Check if an index exists in the database"""
        try:
            with connection.cursor() as cursor:
                # For PostgreSQL
                cursor.execute("""
                    SELECT 1 
                    FROM pg_indexes 
                    WHERE tablename = %s AND indexname = %s
                """, [table_name, index_name])
                return cursor.fetchone() is not None
        except Exception:
            # If we can't check, assume it doesn't exist
            return False
    
    # Define all indexes to add: (model_name, table_name, index)
    indexes_to_add = [
        ('BankReconciliation', 'cash_management_bankreconciliation', 
         models.Index(fields=['status', 'reconciliation_date'], name='cash_manage_status_39433b_idx')),
        ('BankReconciliation', 'cash_management_bankreconciliation',
         models.Index(fields=['prepared_by'], name='cash_manage_prepare_b15224_idx')),
        ('CashCollection', 'cash_management_cashcollection',
         models.Index(fields=['receipt_number'], name='cash_manage_receipt_3ee633_idx')),
        ('CashCollection', 'cash_management_cashcollection',
         models.Index(fields=['collection_date', 'cashier_account'], name='cash_manage_collect_252d3f_idx')),
        ('CashCollection', 'cash_management_cashcollection',
         models.Index(fields=['client', 'collection_date'], name='cash_manage_client__3da805_idx')),
        ('CashCollection', 'cash_management_cashcollection',
         models.Index(fields=['is_posted'], name='cash_manage_is_post_94a1df_idx')),
        ('CashierAccount', 'cash_management_cashieraccount',
         models.Index(fields=['account_number'], name='cash_manage_account_699a1f_idx')),
        ('CashierAccount', 'cash_management_cashieraccount',
         models.Index(fields=['cashier', 'is_active'], name='cash_manage_cashier_d817cf_idx')),
        ('CashierAccount', 'cash_management_cashieraccount',
         models.Index(fields=['current_balance'], name='cash_manage_current_8448b2_idx')),
        ('CashReconciliation', 'cash_management_cashreconciliation',
         models.Index(fields=['reconciliation_date', 'cashier_account'], name='cash_manage_reconci_3cd0a6_idx')),
        ('CashReconciliation', 'cash_management_cashreconciliation',
         models.Index(fields=['status'], name='cash_manage_status_8b3ac4_idx')),
        ('CashTransfer', 'cash_management_cashtransfer',
         models.Index(fields=['transfer_number'], name='cash_manage_transfe_bd22ef_idx')),
        ('CashTransfer', 'cash_management_cashtransfer',
         models.Index(fields=['transfer_date', 'status'], name='cash_manage_transfe_b4e2d2_idx')),
        ('CashTransfer', 'cash_management_cashtransfer',
         models.Index(fields=['cashier_account', 'status'], name='cash_manage_cashier_05a923_idx')),
        ('PettyCashFund', 'cash_management_pettycashfund',
         models.Index(fields=['fund_code'], name='cash_manage_fund_co_32d24b_idx')),
        ('PettyCashFund', 'cash_management_pettycashfund',
         models.Index(fields=['custodian', 'status'], name='cash_manage_custodi_3366c0_idx')),
        ('PettyCashFund', 'cash_management_pettycashfund',
         models.Index(fields=['status'], name='cash_manage_status_4e7d63_idx')),
        ('PettyCashReplenishment', 'cash_management_pettycashreplenishment',
         models.Index(fields=['replenishment_number'], name='cash_manage_repleni_29d560_idx')),
        ('PettyCashReplenishment', 'cash_management_pettycashreplenishment',
         models.Index(fields=['fund', 'status'], name='cash_manage_fund_id_44a688_idx')),
        ('PettyCashReplenishment', 'cash_management_pettycashreplenishment',
         models.Index(fields=['replenishment_date', 'status'], name='cash_manage_repleni_724760_idx')),
        ('PettyCashVoucher', 'cash_management_pettycashvoucher',
         models.Index(fields=['voucher_number'], name='cash_manage_voucher_f1f31f_idx')),
        ('PettyCashVoucher', 'cash_management_pettycashvoucher',
         models.Index(fields=['fund', 'status'], name='cash_manage_fund_id_9fe99d_idx')),
        ('PettyCashVoucher', 'cash_management_pettycashvoucher',
         models.Index(fields=['voucher_date', 'status'], name='cash_manage_voucher_44a136_idx')),
        ('PettyCashVoucher', 'cash_management_pettycashvoucher',
         models.Index(fields=['requested_by'], name='cash_manage_request_1d3837_idx')),
    ]
    
    # Add each index if it doesn't exist
    for model_name, table_name, index in indexes_to_add:
        if index_exists(table_name, index.name):
            # Index already exists, skip
            continue
        
        try:
            Model = apps.get_model('cash_management', model_name)
            schema_editor.add_index(Model, index)
        except Exception:
            # Best-effort: skip if unable to add index
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_is_cashier_bank'),
        ('branches', '0003_branch_latitude_branch_longitude'),
        ('cash_management', '0006_add_receivable_to_cashcollection'),
        ('clients', '0003_add_student_fields'),
        ('expenses', '0003_prepaidexpense_supplier_and_more'),
        ('receivables', '0002_initial'),
        ('transactions', '0003_add_financial_report_indexes'),
        ('users', '0002_setup_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('fund_name', models.CharField(help_text="Name of petty cash fund (e.g., 'Main Office Petty Cash', 'Admin Department')", max_length=200)),
                ('fund_code', models.CharField(db_index=True, help_text="Unique code for this fund (e.g., 'PC-001')", max_length=50, unique=True)),
                ('float_amount', models.DecimalField(decimal_places=2, help_text='Fixed float amount for this fund (Imprest amount)', max_digits=18)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current cash in fund', max_digits=18)),
                ('replenishment_threshold', models.DecimalField(decimal_places=2, help_text='When balance falls below this, trigger replenishment', max_digits=18)),
                ('single_transaction_limit', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Maximum amount for a single petty cash transaction', max_digits=18)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20)),
                ('established_date', models.DateField(default=django.utils.timezone.now, help_text='Date fund was established')),
                ('last_replenishment_date', models.DateField(blank=True, null=True)),
                ('last_audit_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['fund_name'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashReplenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('replenishment_number', models.CharField(db_index=True, help_text="Replenishment reference (e.g., 'PCR-2026-001')", max_length=50, unique=True)),
                ('replenishment_date', models.DateField(default=django.utils.timezone.now, help_text='Date replenishment was requested')),
                ('period_start', models.DateField(help_text='Start of period being replenished')),
                ('period_end', models.DateField(help_text='End of period being replenished')),
                ('total_vouchers_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total of all retired vouchers', max_digits=18)),
                ('total_receipts_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total of all receipts submitted', max_digits=18)),
                ('total_variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total shortage/overage', max_digits=18)),
                ('replenishment_amount', models.DecimalField(decimal_places=2, help_text='Amount to replenish fund (usually = total_receipts_amount)', max_digits=18)),
                ('fund_balance_before', models.DecimalField(decimal_places=2, help_text='Fund balance before replenishment', max_digits=18)),
                ('fund_balance_after', models.DecimalField(blank=True, decimal_places=2, help_text='Fund balance after replenishment (should = float_amount)', max_digits=18, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted to GL')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('expense_breakdown', models.JSONField(blank=True, default=dict, help_text="Breakdown by expense category:\n        {\n            'Office Supplies': {'amount': 5000, 'vouchers': ['PCV-001', 'PCV-005']},\n            'Transportation': {'amount': 3000, 'vouchers': ['PCV-002']}\n        }\n        ")),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-replenishment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('voucher_number', models.CharField(db_index=True, help_text="PCV number (e.g., 'PCV-2026-001')", max_length=50, unique=True)),
                ('voucher_date', models.DateField(default=django.utils.timezone.now, help_text='Date voucher was created')),
                ('purpose', models.CharField(help_text="Purpose of expenditure (e.g., 'Office supplies purchase', 'Courier service')", max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount requested', max_digits=18)),
                ('payee_name', models.CharField(help_text='Who is receiving the money', max_length=200)),
                ('payee_phone', models.CharField(blank=True, help_text='Payee contact', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Cash Disbursed'), ('retired', 'Retired (Receipt Submitted)'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_amount_disbursed', models.DecimalField(blank=True, decimal_places=2, help_text='Actual amount given (may differ slightly from requested)', max_digits=18, null=True)),
                ('receipt_submitted', models.BooleanField(default=False)),
                ('receipt_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount on submitted receipt', max_digits=18, null=True)),
                ('receipt_date', models.DateField(blank=True, help_text='Date on receipt', null=True)),
                ('receipt_reference', models.CharField(blank=True, help_text='Receipt/invoice number', max_length=100)),
                ('receipt_attachment', models.FileField(blank=True, help_text='Upload receipt/invoice', null=True, upload_to='petty_cash/receipts/')),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Difference between disbursed and receipt (shortage/overage)', max_digits=18)),
                ('variance_explanation', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-voucher_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='bankreconciliation',
            options={'ordering': ['-reconciliation_period_end', '-reconciliation_date']},
        ),
        migrations.RemoveIndex(
            model_name='bankreconciliation',
            name='cash_manage_reconci_num_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankreconciliation',
            name='cash_manage_bank_status_idx',
        ),
        migrations.RenameIndex(
            model_name='bankreconciliation',
            new_name='cash_manage_bank_ac_f04d01_idx',
            old_name='cash_manage_bank_period_idx',
        ),
        # Add FK fields conditionally before AlterUniqueTogether references them
        migrations.RunPython(add_cashier_account_if_missing, migrations.RunPython.noop),
        migrations.RunPython(add_client_if_missing, migrations.RunPython.noop),
        migrations.RunPython(add_missing_cashcollection_fks, migrations.RunPython.noop),
        migrations.RunPython(add_missing_cashieraccount_fks, migrations.RunPython.noop),
        migrations.RunPython(add_branch_to_cashreconciliation_if_missing, migrations.RunPython.noop),
        migrations.RunPython(add_cashier_account_to_cashreconciliation_if_missing, migrations.RunPython.noop),
        migrations.RunPython(add_missing_cashreconciliation_fks, migrations.RunPython.noop),
        migrations.RunPython(add_missing_cashtransfer_fks, migrations.RunPython.noop),
        # Temporarily comment out AlterUniqueTogether - will be added post-deployment
        # migrations.AlterUniqueTogether(
        #     name='bankreconciliation',
        #     unique_together={('bank_account', 'reconciliation_period_start', 'reconciliation_period_end', 'branch')},
        # ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='prepared_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='reconciliation_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date reconciliation was performed'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='variance_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Finance manager approval notes'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Finance Manager who approved the reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bank_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='bank_account',
            field=models.ForeignKey(help_text='Bank account (GL Account) being reconciled', on_delete=django.db.models.deletion.PROTECT, related_name='bank_reconciliations', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='bank_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bank charges not yet recorded in GL', max_digits=18),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='bank_closing_balance',
            field=models.DecimalField(decimal_places=2, help_text='Closing balance per bank statement', max_digits=18),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='bank_errors',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bank errors (+ or -)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='bank_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bank interest not yet recorded in GL', max_digits=18),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='bank_opening_balance',
            field=models.DecimalField(decimal_places=2, help_text='Opening balance per bank statement', max_digits=18),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='bank_statement',
            field=models.FileField(blank=True, help_text='Upload bank statement PDF', null=True, upload_to='bank_reconciliations/statements/'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='deposits_in_transit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deposits made but not yet reflected in bank statement', max_digits=18),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='gl_closing_balance',
            field=models.DecimalField(decimal_places=2, help_text='Closing balance per general ledger', max_digits=18),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='gl_errors',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='GL errors (+ or -)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='gl_opening_balance',
            field=models.DecimalField(decimal_places=2, help_text='Opening balance per general ledger', max_digits=18),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='outstanding_checks',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Checks issued but not yet cleared by bank', max_digits=18),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='prepared_by',
            field=models.ForeignKey(help_text='Staff who prepared the reconciliation (independent of cash receipt process)', on_delete=django.db.models.deletion.PROTECT, related_name='prepared_bank_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='reconciled_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated reconciled balance', max_digits=18),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='reconciliation_period_end',
            field=models.DateField(help_text='End date of reconciliation period'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='reconciliation_period_start',
            field=models.DateField(help_text='Start date of reconciliation period'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='reconciling_items',
            field=models.JSONField(blank=True, default=dict, help_text="Detailed reconciling items:\n        {\n            'deposits_in_transit': [{'date': '2026-01-31', 'ref': 'DEP-001', 'amount': 100000}],\n            'outstanding_checks': [{'check_no': 'CHK-001', 'payee': 'ABC', 'amount': 50000}],\n            'bank_charges': [{'date': '2026-01-31', 'description': 'Service charge', 'amount': 500}]\n        }\n        "),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('balanced', 'Balanced'), ('variance_pending', 'Variance Under Investigation'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='supporting_documents',
            field=models.FileField(blank=True, help_text='Supporting documents for reconciling items', null=True, upload_to='bank_reconciliations/supporting/'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='variance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unexplained variance after all adjustments', max_digits=18),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='variance_explanation',
            field=models.TextField(blank=True, help_text='Explanation for any variance and investigation details'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='variance_resolved',
            field=models.BooleanField(default=False, help_text='Whether variance has been resolved'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='variance_resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_bank_variances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashreconciliation',
            name='deposit_completed',
            field=models.BooleanField(default=False, help_text='Whether cash has been deposited to bank'),
        ),
        migrations.AlterField(
            model_name='cashreconciliation',
            name='deposit_required',
            field=models.BooleanField(default=True, help_text='Whether daily deposit to bank is required (should always be True per policy)'),
        ),
        migrations.AlterField(
            model_name='cashreconciliation',
            name='deposit_slip_number',
            field=models.CharField(blank=True, help_text='Bank deposit slip number', max_length=100),
        ),
        migrations.AlterField(
            model_name='cashreconciliation',
            name='deposit_timestamp',
            field=models.DateTimeField(blank=True, help_text='When deposit was made (from bank slip)', null=True),
        ),
        migrations.AlterField(
            model_name='cashreconciliation',
            name='finance_officer_notes',
            field=models.TextField(blank=True, help_text="Finance officer's verification notes"),
        ),
        migrations.AlterField(
            model_name='cashreconciliation',
            name='finance_officer_signoff',
            field=models.ForeignKey(blank=True, help_text='Finance Officer who verified and signed off on reconciliation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_off_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        # Temporarily comment out AlterUniqueTogether - will be added post-deployment
        # migrations.AlterUniqueTogether(
        #     name='cashieraccount',
        #     unique_together={('branch', 'cashier', 'account_number')},
        # ),
        # Add all indexes using guarded helper to avoid DuplicateTable errors
        migrations.RunPython(add_indexes_if_missing, migrations.RunPython.noop),
        migrations.AddField(
            model_name='pettycashfund',
            name='alternate_custodian',
            field=models.ForeignKey(blank=True, help_text='Alternate custodian when primary is unavailable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_funds_alternate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='custodian',
            field=models.ForeignKey(help_text='Person responsible for managing this fund', on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_funds_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='established_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='established_petty_cash_funds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='petty_cash_account',
            field=models.ForeignKey(help_text='Petty Cash GL Account (ASSET account - typically 110-xxx)', on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_funds', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='setup_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_fund_setups', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='pettycashfund',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_petty_cash_replenishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replenishments', to='cash_management.pettycashfund'),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_replenishments', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_petty_cash_replenishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_petty_cash_replenishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='replenishment_source',
            field=models.ForeignKey(help_text='Cash/Bank account to replenish from', on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_replenishments', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='submitted_by',
            field=models.ForeignKey(help_text='Custodian submitting for replenishment', on_delete=django.db.models.deletion.PROTECT, related_name='submitted_petty_cash_replenishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Finance officer who verified receipts', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_petty_cash_replenishments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_petty_cash_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, help_text='Custodian who disbursed the cash', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_petty_cash_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='expense_category',
            field=models.ForeignKey(blank=True, help_text='Expense category for accounting', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_vouchers', to='expenses.expensecategory'),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='cash_management.pettycashfund'),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_petty_cash_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='replenishment',
            field=models.ForeignKey(blank=True, help_text='Replenishment request this voucher is part of', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='cash_management.pettycashreplenishment'),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='requested_by',
            field=models.ForeignKey(help_text='Person requesting petty cash', on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_vouchers_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='retired_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_petty_cash_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.RemoveField(
            model_name='bankreconciliation',
            name='bank_statement_date',
        ),
        migrations.RemoveField(
            model_name='bankreconciliation',
            name='other_adjustments',
        ),
        migrations.RemoveField(
            model_name='bankreconciliation',
            name='reconciliation_number',
        ),
        migrations.RemoveField(
            model_name='bankreconciliation',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='bankreconciliation',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='bankreconciliation',
            name='rejection_reason',
        ),
        # PettyCash indexes already added by add_indexes_if_missing above
        migrations.AlterUniqueTogether(
            name='pettycashfund',
            unique_together={('branch', 'fund_code')},
        ),
    ]
