# Generated by Django 5.2.4 on 2026-02-16 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0007_pettycashfund_pettycashreplenishment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Receipt image or PDF', upload_to='petty_cash_receipts/%Y/%m/')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text="MIME type (e.g., 'application/pdf', 'image/jpeg')", max_length=50)),
                ('description', models.CharField(blank=True, help_text='Optional description of the receipt', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_petty_cash_receipts', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='cash_management.pettycashvoucher')),
            ],
            options={
                'verbose_name': 'Petty Cash Receipt',
                'verbose_name_plural': 'Petty Cash Receipts',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
