# Generated by Django 5.2.4 on 2026-02-28 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_is_cashier_bank'),
        ('branches', '0003_branch_latitude_branch_longitude'),
        ('cash_management', '0008_pettycashreceipt'),
        ('clients', '0005_client_lga_client_previous_school_name_and_more'),
        ('expenses', '0003_prepaidexpense_supplier_and_more'),
        ('receivables', '0002_initial'),
        ('transactions', '0003_add_financial_report_indexes'),
        ('users', '0003_role_permission_codes_user_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Migration 0007 already applied all FK columns and indexes via RunPython
        # conditional helpers (add_cashier_account_if_missing, add_missing_cashcollection_fks,
        # add_missing_cashieraccount_fks, etc.).  Wrapping all operations here in
        # SeparateDatabaseAndState keeps Django's migration state in sync without re-running
        # DDL that already succeeded — preventing "column already exists" errors on fresh DBs.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='cashcollection',
                    name='cashier_account',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_collections', to='cash_management.cashieraccount'),
                ),
                migrations.AddField(
                    model_name='cashcollection',
                    name='client',
                    field=models.ForeignKey(blank=True, help_text='Client who made the payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_collections', to='clients.client'),
                ),
                migrations.AddField(
                    model_name='cashcollection',
                    name='created_by',
                    field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashcollection',
                    name='journal_entry',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_collections', to='transactions.transaction'),
                ),
                migrations.AddField(
                    model_name='cashcollection',
                    name='owner',
                    field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashcollection',
                    name='posted_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_cash_collections', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashcollection',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
                ),
                migrations.AddField(
                    model_name='cashieraccount',
                    name='account',
                    field=models.ForeignKey(blank=True, help_text="GL CHILD account for this cashier's collections. Must be: (1) CHILD level account, (2) ASSET type, (3) Under a Cash/Bank parent account. This enables balanced transactions when cashier collects cash.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_accounts', to='accounts.account'),
                ),
                migrations.AddField(
                    model_name='cashieraccount',
                    name='branch',
                    field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
                ),
                migrations.AddField(
                    model_name='cashieraccount',
                    name='cashier',
                    field=models.ForeignKey(blank=True, help_text='User responsible for this cash collection point', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_accounts', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashieraccount',
                    name='created_by',
                    field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashieraccount',
                    name='last_reconciled_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_cashier_accounts', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashieraccount',
                    name='owner',
                    field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashieraccount',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
                ),
                migrations.AddField(
                    model_name='cashreconciliation',
                    name='branch',
                    field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
                ),
                migrations.AddField(
                    model_name='cashreconciliation',
                    name='cashier_account',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='cash_management.cashieraccount'),
                ),
                migrations.AddField(
                    model_name='cashreconciliation',
                    name='created_by',
                    field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashreconciliation',
                    name='owner',
                    field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashreconciliation',
                    name='reconciled_by',
                    field=models.ForeignKey(blank=True, help_text='Cashier who performed the reconciliation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed_reconciliations', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashreconciliation',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
                ),
                migrations.AddField(
                    model_name='cashreconciliation',
                    name='verified_by',
                    field=models.ForeignKey(blank=True, help_text='Supervisor who verified the reconciliation (deprecated - use finance_officer_signoff)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_reconciliations', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashtransfer',
                    name='approved_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cash_transfers', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashtransfer',
                    name='branch',
                    field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
                ),
                migrations.AddField(
                    model_name='cashtransfer',
                    name='cashier_account',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transfers', to='cash_management.cashieraccount'),
                ),
                migrations.AddField(
                    model_name='cashtransfer',
                    name='created_by',
                    field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashtransfer',
                    name='destination_account',
                    field=models.ForeignKey(blank=True, help_text='Main bank account receiving the cash', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transfers_received', to='accounts.account'),
                ),
                migrations.AddField(
                    model_name='cashtransfer',
                    name='journal_entry',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_transfers', to='transactions.transaction'),
                ),
                migrations.AddField(
                    model_name='cashtransfer',
                    name='owner',
                    field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashtransfer',
                    name='posted_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_cash_transfers', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashtransfer',
                    name='rejected_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_cash_transfers', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashtransfer',
                    name='second_approved_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approved_cash_transfers', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashtransfer',
                    name='submitted_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cash_transfers', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='cashtransfer',
                    name='tenant',
                    field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
                ),
                migrations.AlterUniqueTogether(
                    name='bankreconciliation',
                    unique_together={('bank_account', 'reconciliation_period_start', 'reconciliation_period_end', 'branch')},
                ),
                migrations.AlterUniqueTogether(
                    name='cashieraccount',
                    unique_together={('branch', 'cashier', 'account_number')},
                ),
                migrations.AddIndex(
                    model_name='bankreconciliation',
                    index=models.Index(fields=['status', 'reconciliation_date'], name='cash_manage_status_39433b_idx'),
                ),
                migrations.AddIndex(
                    model_name='bankreconciliation',
                    index=models.Index(fields=['prepared_by'], name='cash_manage_prepare_b15224_idx'),
                ),
                migrations.AddIndex(
                    model_name='cashcollection',
                    index=models.Index(fields=['receipt_number'], name='cash_manage_receipt_3ee633_idx'),
                ),
                migrations.AddIndex(
                    model_name='cashcollection',
                    index=models.Index(fields=['collection_date', 'cashier_account'], name='cash_manage_collect_252d3f_idx'),
                ),
                migrations.AddIndex(
                    model_name='cashcollection',
                    index=models.Index(fields=['client', 'collection_date'], name='cash_manage_client__3da805_idx'),
                ),
                migrations.AddIndex(
                    model_name='cashcollection',
                    index=models.Index(fields=['is_posted'], name='cash_manage_is_post_94a1df_idx'),
                ),
                migrations.AddIndex(
                    model_name='cashieraccount',
                    index=models.Index(fields=['account_number'], name='cash_manage_account_699a1f_idx'),
                ),
                migrations.AddIndex(
                    model_name='cashieraccount',
                    index=models.Index(fields=['cashier', 'is_active'], name='cash_manage_cashier_d817cf_idx'),
                ),
                migrations.AddIndex(
                    model_name='cashieraccount',
                    index=models.Index(fields=['current_balance'], name='cash_manage_current_8448b2_idx'),
                ),
                migrations.AddIndex(
                    model_name='cashreconciliation',
                    index=models.Index(fields=['reconciliation_date', 'cashier_account'], name='cash_manage_reconci_3cd0a6_idx'),
                ),
                migrations.AddIndex(
                    model_name='cashreconciliation',
                    index=models.Index(fields=['status'], name='cash_manage_status_8b3ac4_idx'),
                ),
                migrations.AddIndex(
                    model_name='cashtransfer',
                    index=models.Index(fields=['transfer_number'], name='cash_manage_transfe_bd22ef_idx'),
                ),
                migrations.AddIndex(
                    model_name='cashtransfer',
                    index=models.Index(fields=['transfer_date', 'status'], name='cash_manage_transfe_b4e2d2_idx'),
                ),
                migrations.AddIndex(
                    model_name='cashtransfer',
                    index=models.Index(fields=['cashier_account', 'status'], name='cash_manage_cashier_05a923_idx'),
                ),
                migrations.AddIndex(
                    model_name='pettycashfund',
                    index=models.Index(fields=['fund_code'], name='cash_manage_fund_co_32d24b_idx'),
                ),
                migrations.AddIndex(
                    model_name='pettycashfund',
                    index=models.Index(fields=['custodian', 'status'], name='cash_manage_custodi_3366c0_idx'),
                ),
                migrations.AddIndex(
                    model_name='pettycashfund',
                    index=models.Index(fields=['status'], name='cash_manage_status_4e7d63_idx'),
                ),
                migrations.AddIndex(
                    model_name='pettycashreplenishment',
                    index=models.Index(fields=['replenishment_number'], name='cash_manage_repleni_29d560_idx'),
                ),
                migrations.AddIndex(
                    model_name='pettycashreplenishment',
                    index=models.Index(fields=['fund', 'status'], name='cash_manage_fund_id_44a688_idx'),
                ),
                migrations.AddIndex(
                    model_name='pettycashreplenishment',
                    index=models.Index(fields=['replenishment_date', 'status'], name='cash_manage_repleni_724760_idx'),
                ),
                migrations.AddIndex(
                    model_name='pettycashvoucher',
                    index=models.Index(fields=['voucher_number'], name='cash_manage_voucher_f1f31f_idx'),
                ),
                migrations.AddIndex(
                    model_name='pettycashvoucher',
                    index=models.Index(fields=['fund', 'status'], name='cash_manage_fund_id_9fe99d_idx'),
                ),
                migrations.AddIndex(
                    model_name='pettycashvoucher',
                    index=models.Index(fields=['voucher_date', 'status'], name='cash_manage_voucher_44a136_idx'),
                ),
                migrations.AddIndex(
                    model_name='pettycashvoucher',
                    index=models.Index(fields=['requested_by'], name='cash_manage_request_1d3837_idx'),
                ),
            ],
        ),
    ]
