# Generated by Django 5.2.4 on 2026-03-17 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bank_account_fk_on_expense_and_replenishment'),
        ('banks', '0003_bankaccount_gl_account_nullable'),
        ('cash_management', '0009_cashcollection_cashier_account_cashcollection_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text="Bank account the replenishment funds are drawn from. When set, the bank account's GL account is used for the posting entry (Dr. Expenses / Cr. Bank Account) instead of the generic replenishment_source account.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_replenishments', to='banks.bankaccount'),
        ),
        migrations.AlterField(
            model_name='pettycashreplenishment',
            name='replenishment_source',
            field=models.ForeignKey(help_text='Cash/Bank GL account to replenish from', on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_replenishments', to='accounts.account'),
        ),
    ]
