# Generated by Django 5.2.4 on 2026-03-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0011_pettycashvoucher_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved (may be less than requested_amount)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='pettycashreplenishment',
            name='requested_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount explicitly requested by the custodian for replenishment', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='pettycashreplenishment',
            name='replenishment_amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount to replenish fund (auto-calculated from vouchers)', max_digits=18),
        ),
    ]
