# Generated by Django 5.2.4 on 2026-05-20 21:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_add_bank_feed_consent'),
        ('branches', '0004_add_contact_fields_and_invoice_bank_flag'),
        ('cash_management', '0012_add_requested_approved_amount_to_replenishment'),
        ('clients', '0007_client_assigned_officer'),
        ('hr', '0022_staff_role_level_reports_to'),
        ('loans', '0004_ktil_microfinance_fields'),
        ('savings', '0002_initial'),
        ('transactions', '0006_fix_empty_sequence_names'),
        ('users', '0008_role_excluded_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCollectionSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('collection_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date on which collections are being made')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('submitted', 'Submitted'), ('reconciled', 'Reconciled')], db_index=True, default='draft', max_length=20)),
                ('total_expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of amount_expected across all items', max_digits=18)),
                ('total_collected_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of posted cash collections', max_digits=18)),
                ('total_confirmed_transfers', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of confirmed direct bank transfers', max_digits=18)),
                ('total_unconfirmed_transfers', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of bank transfers still awaiting confirmation', max_digits=18)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_notified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('credit_officer', models.ForeignKey(help_text='Credit officer responsible for this sheet', on_delete=django.db.models.deletion.PROTECT, related_name='collection_sheets', to='hr.staff')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_sheets', to=settings.AUTH_USER_MODEL)),
                ('submitted_to', models.ForeignKey(blank=True, help_text='Superior the sheet was handed to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_collection_sheets', to='hr.staff')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['-collection_date'],
            },
        ),
        migrations.CreateModel(
            name='CollectionSheetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('collection_type', models.CharField(choices=[('loan_repayment', 'Loan Repayment'), ('savings_deposit', 'Savings / Thrift Deposit'), ('processing_fee', 'Loan Processing Fee')], db_index=True, max_length=20)),
                ('amount_expected', models.DecimalField(decimal_places=2, help_text='Amount due per schedule / expected contribution', max_digits=18)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount actually received from the client', max_digits=18)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Direct Bank Transfer'), ('mobile_money', 'Mobile Money / USSD')], default='cash', max_length=20)),
                ('bank_reference', models.CharField(blank=True, help_text='Reference number / teller number provided by the client', max_length=100)),
                ('transfer_confirmation_status', models.CharField(choices=[('na', 'Not Applicable'), ('pending', 'Awaiting Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Not Found / Rejected')], db_index=True, default='na', max_length=20)),
                ('transfer_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('collected', 'Collected / Paid'), ('partial', 'Partial Payment'), ('missed', 'Missed / Not Paid')], db_index=True, default='pending', max_length=20)),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('bank_account_credited', models.ForeignKey(blank=True, help_text='Which of our bank accounts the client transferred into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_items_received', to='banks.bankaccount')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_sheet_items', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_sheet_items', to='transactions.transaction')),
                ('loan_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_items', to='loans.loanaccount')),
                ('loan_installment', models.ForeignKey(blank=True, help_text='The specific schedule instalment being settled (for loan_repayment)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_items', to='loans.loanrepaymentschedule')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('savings_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collection_items', to='savings.savingsaccount')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
                ('transfer_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_transfer_items', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cash_management.dailycollectionsheet')),
            ],
            options={
                'ordering': ['sheet__collection_date', 'client__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='dailycollectionsheet',
            index=models.Index(fields=['credit_officer', 'collection_date'], name='cash_manage_credit__adfc60_idx'),
        ),
        migrations.AddIndex(
            model_name='dailycollectionsheet',
            index=models.Index(fields=['status', 'collection_date'], name='cash_manage_status_31e944_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailycollectionsheet',
            unique_together={('credit_officer', 'collection_date')},
        ),
        migrations.AddIndex(
            model_name='collectionsheetitem',
            index=models.Index(fields=['sheet', 'status'], name='cash_manage_sheet_i_7b1960_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionsheetitem',
            index=models.Index(fields=['transfer_confirmation_status'], name='cash_manage_transfe_5e0db8_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionsheetitem',
            index=models.Index(fields=['is_posted'], name='cash_manage_is_post_cd5355_idx'),
        ),
    ]
