# Generated by Django 5.2.4 on 2026-08-05 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0013_daily_collection_sheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashvoucher',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_petty_cash_vouchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
