# Generated by Django 5.2.4 on 2026-08-05 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0013_daily_collection_sheet'),
        ('expenses', '0009_expensecategory_budget_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashVoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('line_order', models.PositiveIntegerField(default=0)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_voucher_lines', to='expenses.expensecategory')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cash_management.pettycashvoucher')),
            ],
            options={
                'ordering': ['line_order', 'id'],
            },
        ),
    ]
