# Generated by Django 5.2.4 on 2026-08-05 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0014_pettycashvoucher_reversal_reason_and_more'),
        ('cash_management', '0015_pettycashvoucherline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashvoucher',
            name='reversal_previous_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='reversal_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='reversal_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_petty_cash_voucher_reversals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='reversal_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='reversal_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='reversal_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_petty_cash_voucher_reversals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pettycashvoucher',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Cash Disbursed'), ('retired', 'Retired (Receipt Submitted)'), ('reversal_pending', 'Reversal Pending Approval'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
