# Generated by Django 5.2.4 on 2026-09-06 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_code'),
        ('cash_management', '0016_pettycashvoucher_reversal_previous_status_and_more'),
        ('hr', '0028_staff_salary_advance_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashfund',
            name='disbursement_mode',
            field=models.CharField(choices=[('cash', 'Cash (physical till)'), ('bank_transfer', 'Bank Transfer')], default='cash', help_text="'cash' = physical-till workflow (disburse() credits petty_cash_account and decrements current_balance). 'bank_transfer' = maker-checker bank transfer to the payee (disburse() credits the chosen BankAccount's GL account instead and does not touch current_balance). Change any time — no redeploy needed.", max_length=20),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='disbursement_account',
            field=models.ForeignKey(blank=True, help_text='Bank GL account the transfer was executed from (bank_transfer mode only).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_voucher_disbursements', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='payee_bank_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='payee_bank_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='payee_bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pettycashvoucher',
            name='payee_staff',
            field=models.ForeignKey(blank=True, help_text='Optional HR Staff link — auto-fills bank details for bank-transfer disbursement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_vouchers_as_payee', to='hr.staff'),
        ),
    ]
