# Generated by Django 5.2.4 on 2026-09-20 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0018_pettycashfund_petty_cash_account_nullable'),
        ('hr', '0030_alter_leaverequest_medical_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashvoucherline',
            name='staff',
            field=models.ForeignKey(blank=True, help_text="Staff member being reimbursed for this specific line, when a voucher covers several people's expenses at once. Auto-fills bank details for bank-transfer disbursement, same as voucher.payee_staff.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_voucher_lines_as_payee', to='hr.staff'),
        ),
    ]
