# Generated by Django 5.2.4 on 2026-02-01 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liabilities', '0002_initial'),
        ('procurement', '0003_add_vendor_invoice_to_pr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountspayable',
            name='posted_at',
            field=models.DateTimeField(blank=True, help_text='When payment was posted', null=True),
        ),
        migrations.AddField(
            model_name='accountspayable',
            name='posted_by',
            field=models.ForeignKey(blank=True, help_text='User who posted/approved the payment (responsible party)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountspayable',
            name='posting_notes',
            field=models.TextField(blank=True, help_text='Notes from the person posting the payment'),
        ),
        migrations.AddField(
            model_name='accountspayable',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Purchase Order reference (required for vendor invoice validation)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='accountspayable',
            name='three_way_match_result',
            field=models.JSONField(blank=True, help_text='Detailed 3-way matching results from validation', null=True),
        ),
        migrations.AddField(
            model_name='accountspayable',
            name='three_way_match_status',
            field=models.CharField(choices=[('not_validated', 'Not Validated'), ('passed', 'Match Passed'), ('warning', 'Match Warning'), ('failed', 'Match Failed')], default='not_validated', help_text='Result of 3-way matching validation', max_length=20),
        ),
        migrations.AddField(
            model_name='accountspayable',
            name='validated_at',
            field=models.DateTimeField(blank=True, help_text='When 3-way match validation was performed', null=True),
        ),
        migrations.AddField(
            model_name='accountspayable',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text='User who validated the invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payables', to=settings.AUTH_USER_MODEL),
        ),
    ]
