# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('priority_level', models.PositiveIntegerField(default=0)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Default credit limit for clients in this classification', max_digits=18, null=True)),
                ('special_rates', models.JSONField(blank=True, default=dict, help_text='Special interest rates or fees for this classification')),
            ],
            options={
                'ordering': ['priority_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('id_card', 'ID Card'), ('passport', 'Passport'), ('utility_bill', 'Utility Bill'), ('bank_statement', 'Bank Statement'), ('employment_letter', 'Employment Letter'), ('salary_slip', 'Salary Slip'), ('tax_id', 'Tax ID'), ('business_reg', 'Business Registration'), ('other', 'Other Document')], max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('issuing_authority', models.CharField(blank=True, max_length=200)),
                ('document_file', models.FileField(upload_to='clients/documents/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('meeting', 'Meeting Note'), ('call', 'Call Note'), ('complaint', 'Complaint'), ('followup', 'Follow-up'), ('warning', 'Warning'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('relationship_type', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('business_partner', 'Business Partner'), ('employer', 'Employer'), ('employee', 'Employee'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_guarantor', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('client_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(blank=True, choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('miss', 'Miss'), ('dr', 'Dr'), ('chief', 'Chief')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('blacklisted', 'Blacklisted')], default='active', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='low', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20, null=True)),
                ('address_street', models.CharField(blank=True, max_length=200, null=True)),
                ('address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('address_state', models.CharField(blank=True, max_length=100, null=True)),
                ('address_postal_code', models.CharField(blank=True, max_length=20)),
                ('address_country', models.CharField(blank=True, default='Nigeria', max_length=100, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('national_id', 'National ID'), ('drivers_license', "Driver's License"), ('passport', 'International Passport'), ('voters_card', "Voter's Card")], max_length=50, null=True)),
                ('id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('id_issue_date', models.DateField(blank=True, null=True)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('employer_address', models.TextField(blank=True, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self Employed'), ('unemployed', 'Unemployed'), ('retired', 'Retired'), ('student', 'Student')], max_length=50, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('income_source', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('none', 'None'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('tertiary', 'Tertiary'), ('graduate', 'Graduate'), ('post_graduate', 'Post Graduate')], max_length=50, null=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200, null=True)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('next_of_kin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('next_of_kin_address', models.TextField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_verification_number', models.CharField(blank=True, max_length=100, null=True)),
                ('preferred_language', models.CharField(default='English', max_length=50)),
                ('communication_preference', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('call', 'Phone Call')], default='sms', max_length=20)),
                ('marketing_consent', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clients/images/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='clients/signatures/')),
                ('referral_source', models.CharField(blank=True, max_length=100, null=True)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('kyc_last_update', models.DateTimeField(blank=True, null=True)),
                ('last_kyc_check', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Domain-specific additional data')),
                ('usage_context', models.CharField(choices=[('financial', 'Financial Client'), ('student', 'Student'), ('patient', 'Patient'), ('customer', 'Customer')], db_index=True, default='financial', max_length=50)),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID from previous/external system', max_length=100, null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
