# Generated by Django 5.2.4 on 2026-02-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_add_student_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='previous_school_class',
            field=models.CharField(blank=True, help_text='Last class attended at previous school', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_guardian_home_address',
            field=models.TextField(blank=True, help_text='Home address of primary guardian', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_guardian_office_address',
            field=models.TextField(blank=True, help_text='Office address of primary guardian', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='school_house',
            field=models.CharField(blank=True, help_text="Student's house (e.g., 'Blue', 'Green', 'Red', 'Yellow')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='secondary_guardian_home_address',
            field=models.TextField(blank=True, help_text='Home address of secondary guardian', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='secondary_guardian_office_address',
            field=models.TextField(blank=True, help_text='Office address of secondary guardian', null=True),
        ),
    ]
