# Generated by Django 5.2.4 on 2026-02-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_previous_school_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lga',
            field=models.CharField(blank=True, help_text='Local Government Area (LGA) of origin', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='previous_school_name',
            field=models.CharField(blank=True, help_text='Name of the previous school attended', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='proposed_entry_month',
            field=models.CharField(blank=True, help_text="Proposed month of entry (e.g., 'September')", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='state_of_origin',
            field=models.CharField(blank=True, help_text='State of origin for the student', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='who_pays_fees',
            field=models.CharField(blank=True, help_text="Who is responsible for paying the student's fees", max_length=100, null=True),
        ),
    ]
