# Generated by Django 5.2.4 on 2026-05-20 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_add_contact_fields_and_invoice_bank_flag'),
        ('clients', '0005_client_lga_client_previous_school_name_and_more'),
        ('users', '0008_role_excluded_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(blank=True, choices=[('dc', 'Daily/Ajo'), ('wl', 'Weekly Loan'), ('ml', 'Monthly Loan'), ('pr', 'Premium')], db_index=True, help_text='Primary loan product type (DC=Daily/Ajo, WL=Weekly, ML=Monthly, PR=Premium)', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='guarantor_home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='guarantor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='guarantor_occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='guarantor_office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='guarantor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='guarantor_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='usage_context',
            field=models.CharField(choices=[('client', 'Client'), ('financial', 'Financial Client'), ('student', 'Student'), ('patient', 'Patient'), ('customer', 'Customer')], db_index=True, default='client', max_length=50),
        ),
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('meeting_day', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week on which the group meets', max_length=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('leader', models.ForeignKey(blank=True, help_text='Group leader — must be a registered client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to='clients.client')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Ajo/group savings group this client belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='clients.clientgroup'),
        ),
        migrations.AddIndex(
            model_name='clientgroup',
            index=models.Index(fields=['is_active'], name='clients_cli_is_acti_402ea1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientgroup',
            unique_together={('owner', 'code')},
        ),
    ]
