# Generated by Django 5.2.4 on 2026-05-20 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_ktil_microfinance_fields'),
        ('hr', '0022_staff_role_level_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, help_text="Credit officer responsible for this client. Officers only see clients assigned to them; supervisors see their team's clients too.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to='hr.staff'),
        ),
    ]
