# Generated by Django 5.2.4 on 2026-05-21 14:11

import clients.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_add_contact_fields_and_invoice_bank_flag'),
        ('clients', '0007_client_assigned_officer'),
        ('hr', '0022_staff_role_level_reports_to'),
        ('users', '0008_role_excluded_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user at the time of the action.', null=True)),
                ('action', models.CharField(choices=[('created', 'Profile Created'), ('updated', 'Profile Updated'), ('status_changed', 'Status Changed'), ('kyc_updated', 'KYC Status Updated'), ('loan_created', 'Loan Created'), ('loan_status_changed', 'Loan Status Changed'), ('savings_deposit', 'Savings Deposit'), ('savings_withdrawal', 'Savings Withdrawal'), ('assigned_officer_changed', 'Assigned Officer Changed'), ('account_manager_changed', 'Account Manager Changed'), ('document_uploaded', 'Document Uploaded'), ('note_added', 'Note Added'), ('deleted', 'Profile Soft-Deleted'), ('restored', 'Profile Restored'), ('other', 'Other')], db_index=True, max_length=50)),
                ('changed_fields', models.JSONField(default=list, help_text='List of field names that were changed.')),
                ('old_values', models.JSONField(default=dict, help_text='Field values BEFORE the change.')),
                ('new_values', models.JSONField(default=dict, help_text='Field values AFTER the change.')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action.')),
            ],
            options={
                'ordering': ['-timestamp'],
                'default_permissions': ('view',),
            },
        ),
        migrations.AddField(
            model_name='client',
            name='account_manager',
            field=models.ForeignKey(blank=True, help_text='Account / relationship manager responsible for this client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clients', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='client',
            name='nin',
            field=models.CharField(blank=True, db_index=True, help_text='National Identification Number (11 digits). Must be globally unique.', max_length=11, null=True, unique=True, validators=[clients.models.validate_nin]),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_type',
            field=models.CharField(blank=True, choices=[('national_id', 'National ID'), ('nin', 'NIN (National Identification Number)'), ('drivers_license', "Driver's License"), ('passport', 'International Passport'), ('voters_card', "Voter's Card")], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['nin'], name='clients_cli_nin_698c15_idx'),
        ),
        migrations.AddField(
            model_name='customerauditlog',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='clients.client'),
        ),
        migrations.AddField(
            model_name='customerauditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the action (null = system/automated).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customerauditlog',
            index=models.Index(fields=['client', '-timestamp'], name='clients_cus_client__d51be8_idx'),
        ),
        migrations.AddIndex(
            model_name='customerauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='clients_cus_user_id_c6e4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='customerauditlog',
            index=models.Index(fields=['action'], name='clients_cus_action_a5797a_idx'),
        ),
    ]
