# Generated by Django 5.2.4 on 2026-05-26 11:39

import clients.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_nin_account_manager_audit_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bvn',
            field=models.CharField(blank=True, db_index=True, help_text='CBN Bank Verification Number (11 digits). Globally unique across all clients.', max_length=11, null=True, unique=True, validators=[clients.models.validate_bvn]),
        ),
        migrations.AddField(
            model_name='client',
            name='kyc_verified_by',
            field=models.ForeignKey(blank=True, help_text="Staff member who verified this client's KYC documents.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications_performed', to=settings.AUTH_USER_MODEL),
        ),
    ]
