# Generated by Django 5.2.4 on 2026-06-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_remove_guarantor_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientgroup',
            new_name='clients_cli_assigne_a98ebc_idx',
            old_name='clients_clientgroup_officer_idx',
        ),
    ]
