# Generated by Django 5.2.4 on 2026-07-17 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_guarantor_model'),
        ('hr', '0023_staffiou_deduction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientgroup',
            name='member_officers',
            field=models.ManyToManyField(blank=True, help_text="Full roster of officers who can view/manage this group and its clients (e.g. a supervisor covering for the primary officer). Does not by itself change any client's assigned_officer — only assigned_officer cascades to clients.", related_name='member_of_groups', to='hr.staff'),
        ),
        migrations.AlterField(
            model_name='clientgroup',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, help_text='Primary credit officer for this group — cascades to Client.assigned_officer on every member client, driving data-access scoping. Always kept as a member of member_officers (see assign_officer action).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to='hr.staff'),
        ),
    ]
