# Generated by Django 5.2.4 on 2026-08-04 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_code'),
        ('clients', '0015_clientgroup_member_officers'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientregistrationconfig',
            name='reactivation_fee',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=18),
        ),
        migrations.AddField(
            model_name='clientregistrationconfig',
            name='reactivation_income_account',
            field=models.ForeignKey(blank=True, limit_choices_to={'account_type': 'INCOME'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_reactivation_income_configs', to='accounts.account'),
        ),
    ]
