# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automations', '0002_initial'),
        ('branches', '0002_initial'),
        ('inventory', '0002_initial'),
        ('procurement', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednote',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_goods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_grns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_goods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='received_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='goodsreceivednoteitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivednoteitem',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.goodsreceivednote'),
        ),
        migrations.AddField(
            model_name='goodsreceivednoteitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='goodsreceivednoteitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivednoteitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='procurementconfig',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='procurementconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementconfig',
            name='default_grn_workflow',
            field=models.ForeignKey(blank=True, help_text='Default workflow for GRN processing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_configs', to='automations.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='procurementconfig',
            name='default_po_workflow',
            field=models.ForeignKey(blank=True, help_text='Default workflow for Purchase Orders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_configs', to='automations.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='procurementconfig',
            name='default_pr_workflow',
            field=models.ForeignKey(blank=True, help_text='Default workflow for Purchase Requisitions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_configs', to='automations.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='procurementconfig',
            name='high_value_po_workflow',
            field=models.ForeignKey(blank=True, help_text='Workflow for high-value POs (if threshold exceeded)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='high_value_po_configs', to='automations.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='procurementconfig',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procurementconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='automations.workflowrun'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='goodsreceivednoteitem',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_items', to='procurement.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requisitions', to='automations.workflowrun'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.purchaserequisition'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisition_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='po_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_items', to='procurement.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaserequisition'),
        ),
        migrations.AddField(
            model_name='purchaserequisitionitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='procurement.goodsreceivednote'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='grn_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='procurement.goodsreceivednoteitem'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='purchase_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchasereturn'),
        ),
        migrations.AddField(
            model_name='purchasereturnitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='procurement.purchaserequisition'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='supplierquote',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='selected_quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.supplierquote'),
        ),
        migrations.AddField(
            model_name='supplierquoteitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierquoteitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='supplierquoteitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierquoteitem',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.supplierquote'),
        ),
        migrations.AddField(
            model_name='supplierquoteitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddIndex(
            model_name='purchaserequisition',
            index=models.Index(fields=['status', 'request_date'], name='procurement_status_620491_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['supplier_code'], name='procurement_supplie_332f00_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='procurement_name_04b689_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('owner', 'branch', 'supplier_code')},
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['received_date', 'is_posted'], name='procurement_receive_d83d16_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceivednote',
            index=models.Index(fields=['supplier', 'received_date'], name='procurement_supplie_fd092b_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', 'order_date'], name='procurement_status_10bf44_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', 'status'], name='procurement_supplie_b6d45e_idx'),
        ),
    ]
