# Generated by Django 5.2.4 on 2026-02-01 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequisition',
            name='invoice_verified_at',
            field=models.DateTimeField(blank=True, help_text='When invoice was verified', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='invoice_verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified the invoice details', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_pr_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='vendor_invoice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Total amount on vendor's invoice", max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='vendor_invoice_date',
            field=models.DateField(blank=True, help_text="Date on vendor's invoice", null=True),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='vendor_invoice_file',
            field=models.FileField(blank=True, help_text='Upload vendor invoice (PDF/Image)', null=True, upload_to='procurement/vendor_invoices/'),
        ),
        migrations.AddField(
            model_name='purchaserequisition',
            name='vendor_invoice_number',
            field=models.CharField(blank=True, help_text="Vendor's invoice number (required for approval)", max_length=100),
        ),
    ]
