# Generated by Django 5.2.4 on 2026-04-01 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_add_contact_fields_and_invoice_bank_flag'),
        ('procurement', '0003_add_vendor_invoice_to_pr'),
        ('transactions', '0006_fix_empty_sequence_names'),
        ('users', '0007_tenant_domainconfig_customlabels_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceivednoteitem',
            name='quality_data',
            field=models.JSONField(blank=True, default=dict, help_text='Extended quality inspection fields: condition_rating, visual_inspection, packaging_condition, expiry_check, batch_verification, temperature_check'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry created when return is posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='transactions.transaction'),
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('contract', 'Contract / Agreement'), ('certificate', 'Registration Certificate'), ('tax_document', 'Tax Registration (TIN)'), ('insurance', 'Insurance Certificate'), ('license', 'Business License'), ('bank_details', 'Bank Account Details'), ('nda', 'NDA / Confidentiality'), ('quality', 'Quality Certification'), ('other', 'Other')], default='other', max_length=30)),
                ('file', models.FileField(upload_to='supplier_documents/')),
                ('description', models.TextField(blank=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='procurement.supplier')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_supplier_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
