# Generated by Django 5.2.4 on 2026-08-03 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_code'),
        ('procurement', '0004_goodsreceivednoteitem_quality_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='account',
            field=models.OneToOneField(blank=True, help_text="Dedicated LIABILITY subledger account for this supplier's payables/advances.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_detail', to='accounts.account'),
        ),
    ]
