# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('enable_leave_approval', models.BooleanField(default=True, help_text='Require approval for leave requests')),
                ('max_consecutive_leave_days', models.PositiveIntegerField(default=14, help_text='Maximum consecutive days of leave without special approval')),
                ('annual_leave_days', models.PositiveIntegerField(default=20, help_text='Default annual leave entitlement in days')),
                ('sick_leave_days', models.PositiveIntegerField(default=10, help_text='Default sick leave entitlement in days')),
                ('enable_attendance_tracking', models.BooleanField(default=True, help_text='Track employee attendance')),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Standard working hours per day', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('late_arrival_grace_minutes', models.PositiveIntegerField(default=15, help_text='Grace period for late arrivals in minutes')),
                ('payroll_currency', models.CharField(default='USD', help_text='Currency code for payroll (e.g., USD, NGN, GBP)', max_length=3)),
                ('payroll_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('bi_weekly', 'Bi-Weekly'), ('weekly', 'Weekly')], default='monthly', help_text='Default payroll frequency', max_length=20)),
                ('tax_rate_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default tax rate percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('enable_overtime_calculation', models.BooleanField(default=True, help_text='Calculate overtime pay')),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Overtime pay multiplier (e.g., 1.5 for time-and-a-half)', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('payslip_prefix', models.CharField(default='PAY', help_text='Prefix for payslip numbers', max_length=10)),
                ('payslip_current_number', models.PositiveIntegerField(default=1, help_text='Current payslip number for auto-generation')),
            ],
            options={
                'verbose_name': 'HR Configuration',
                'verbose_name_plural': 'HR Configurations',
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField(help_text='Year for this balance')),
                ('entitled_days', models.DecimalField(decimal_places=2, help_text='Total days entitled for this year', max_digits=6)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, help_text='Days already used', max_digits=6)),
                ('pending_days', models.DecimalField(decimal_places=2, default=0, help_text='Days in pending requests', max_digits=6)),
                ('carried_over_days', models.DecimalField(decimal_places=2, default=0, help_text='Days carried over from previous year', max_digits=6)),
            ],
            options={
                'ordering': ['-year', 'staff'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_days', models.DecimalField(decimal_places=2, help_text='Number of leave days (can be fractional for half-days)', max_digits=6)),
                ('reason', models.TextField()),
                ('medical_certificate', models.FileField(blank=True, help_text='Medical certificate (for sick leave)', null=True, upload_to='hr/medical_certificates/')),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='hr/leave_documents/')),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('contact_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('taken', 'Taken')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approval_chain', models.JSONField(blank=True, default=list, help_text='Track all approvers and decisions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_paid', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('requires_medical_certificate', models.BooleanField(default=False, help_text='Requires medical certificate (for sick leave)')),
                ('default_days_per_year', models.PositiveIntegerField(default=0, help_text='Default number of days per year (0 = unlimited)')),
                ('allow_carryover', models.BooleanField(default=False, help_text='Allow unused days to carry over to next year')),
                ('max_carryover_days', models.PositiveIntegerField(default=0, help_text='Maximum days that can be carried over')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pay_date', models.DateField(help_text='Date when payment will be made')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='PayrollSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly')], max_length=10)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='For monthly freq: day (1–28)', null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='For weekly freq: 0=Monday–6=Sunday', null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('payslip_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=18)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('allowances', models.JSONField(default=dict, help_text='Dict of allowance_name: amount')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('deductions', models.JSONField(default=dict, help_text='Dict of deduction_name: amount')),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=18)),
                ('days_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('days_absent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('days_on_leave', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF payslip', null=True, upload_to='hr/payslips/')),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-payroll__period_end', 'staff'],
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=10)),
                ('default_amount', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='staff_photos/')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffPayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Override default amount if needed', max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(db_index=True)),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('public_holiday', 'Public Holiday'), ('weekend', 'Weekend')], default='present', max_length=20)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, help_text='Actual hours worked', max_digits=5)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, help_text='Overtime hours', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
            ],
            options={
                'ordering': ['-date', 'staff'],
            },
        ),
    ]
