# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('automations', '0002_initial'),
        ('branches', '0002_initial'),
        ('hr', '0001_initial'),
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='default_leave_workflow',
            field=models.ForeignKey(blank=True, help_text='Default workflow for leave requests', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_leave_configs', to='automations.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='extended_leave_workflow',
            field=models.ForeignKey(blank=True, help_text='Workflow for extended leave requests (> max_consecutive_leave_days)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_extended_leave_configs', to='automations.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='payroll_approval_workflow',
            field=models.ForeignKey(blank=True, help_text='Workflow for payroll approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_payroll_configs', to='automations.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='automations.workflowrun'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='leave_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hr.leaverequest'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.leavetype'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.leavetype'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='calculated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Accounting journal entry for payroll payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_entries', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_account',
            field=models.ForeignKey(blank=True, help_text='Bank/Cash account used for payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payments', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='automations.workflowrun'),
        ),
        migrations.AddField(
            model_name='payrollschedule',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='payrollschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollschedule',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payrollschedule',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.payroll'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salarycomponent',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='staff',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='staff',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Optional link to a login user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payslip',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='relief_officer',
            field=models.ForeignKey(blank=True, help_text='Staff member covering duties', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relief_assignments', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='staffpayinfo',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='staffpayinfo',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hr.salarycomponent'),
        ),
        migrations.AddField(
            model_name='staffpayinfo',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffpayinfo',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffpayinfo',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_info', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='staffpayinfo',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='hrconfig',
            unique_together={('branch',)},
        ),
        migrations.AlterUniqueTogether(
            name='leavetype',
            unique_together={('branch', 'code')},
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['period_start', 'period_end'], name='hr_payroll_period__f77b32_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='hr_payroll_status_fd827d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payrollschedule',
            unique_together={('branch', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='salarycomponent',
            unique_together={('branch', 'name')},
        ),
        migrations.AddIndex(
            model_name='payslip',
            index=models.Index(fields=['staff', 'payroll'], name='hr_payslip_staff_i_35a754_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together={('payroll', 'staff')},
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['staff', 'status'], name='hr_leavereq_staff_i_bbe821_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['start_date', 'end_date'], name='hr_leavereq_start_d_9e9e54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('staff', 'leave_type', 'year')},
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'status'], name='hr_attendan_date_36f853_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('staff', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='staffpayinfo',
            unique_together={('staff', 'component')},
        ),
    ]
