# Generated by Django 5.2.4 on 2026-02-04 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_fix_hrconfig_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='first_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='first_approver',
            field=models.ForeignKey(blank=True, help_text='First approver (e.g., Finance Manager)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_first_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payroll',
            name='second_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='second_approver',
            field=models.ForeignKey(blank=True, help_text='Second approver (e.g., Principal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_second_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
