# Generated by Django 5.2.4 on 2026-02-08 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_latitude_branch_longitude'),
        ('hr', '0004_payroll_first_approved_at_payroll_first_approver_and_more'),
        ('transactions', '0003_add_financial_report_indexes'),
        ('users', '0002_setup_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='liabilities_journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry created on approval: DR Salary Expense, CR Salary Payable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_liability_entries', to='transactions.transaction'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry created on disbursement: DR Salary Payable, CR Cash/Bank', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payment_entries', to='transactions.transaction'),
        ),
        migrations.CreateModel(
            name='BonusDeductionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this one-time adjustment', max_digits=18)),
                ('reason', models.TextField(help_text='Justification for this bonus/deduction')),
                ('for_month', models.DateField(help_text='Month and year this should be applied (YYYY-MM-01)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason if rejected')),
                ('applied_in_payroll', models.ForeignKey(blank=True, help_text='Payroll where this was applied (set after processing)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_deduction_requests', to='hr.payroll')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_deduction_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('component', models.ForeignKey(help_text='Salary component (bonus or deduction)', on_delete=django.db.models.deletion.PROTECT, to='hr.salarycomponent')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bonus_deduction_requests_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_deduction_requests', to='hr.staff')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['-requested_date'],
                'indexes': [models.Index(fields=['status', 'for_month'], name='hr_bonusded_status_40ca80_idx'), models.Index(fields=['staff', 'status'], name='hr_bonusded_staff_i_316844_idx')],
            },
        ),
    ]
