# Generated by Django 5.2.4 on 2026-03-04 08:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_is_cashier_bank'),
        ('branches', '0003_branch_latitude_branch_longitude'),
        ('hr', '0005_payroll_liabilities_journal_entry_and_more'),
        ('transactions', '0003_add_financial_report_indexes'),
        ('users', '0003_role_permission_codes_user_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hrconfig',
            name='employee_pension_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Employee pension contribution rate as % of gross salary (standard: 8%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='employer_pension_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Employer pension contribution rate as % of gross salary (standard: 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='enable_pension',
            field=models.BooleanField(default=False, help_text='Enable pension deduction and employer contribution for this branch'),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='pension_provider_name',
            field=models.CharField(blank=True, help_text='Name of the pension fund / provider', max_length=200),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='staff_id_current_number',
            field=models.PositiveIntegerField(default=1, help_text='Next sequential number to issue; incremented on each staff creation'),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='staff_id_padding',
            field=models.PositiveSmallIntegerField(default=3, help_text='Zero-pad width for the numeric part (3 → 001, 4 → 0001)'),
        ),
        migrations.AddField(
            model_name='hrconfig',
            name='staff_id_prefix',
            field=models.CharField(default='STF', help_text='Branch-specific prefix for staff IDs (e.g. MML → MML001)', max_length=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='pension_expense_journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry: DR Pension Expense, CR Employer Pension Payable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_pension_expense_entries', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_employee_pension',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all employee pension contributions (8% per payslip)', max_digits=18),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_employer_pension',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all employer pension contributions (10% per payslip)', max_digits=18),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employee_pension',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employee pension contribution deducted from salary (e.g. 8% of gross)', max_digits=18),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employer_pension',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employer pension contribution (e.g. 10% of gross) — expensed separately', max_digits=18),
        ),
        migrations.AddField(
            model_name='staff',
            name='pension_number',
            field=models.CharField(blank=True, help_text='Pension fund membership / registration number', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='pension_provider',
            field=models.CharField(blank=True, help_text='Pension fund / provider name for this staff member', max_length=200),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated staff ID based on branch prefix (e.g. MML001)', max_length=30),
        ),
        migrations.CreateModel(
            name='PensionRemittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('remittance_date', models.DateField(help_text='Date pension was actually transferred to the fund')),
                ('total_employee_pension', models.DecimalField(decimal_places=2, help_text='Sum of employee pension contributions remitted', max_digits=18)),
                ('total_employer_pension', models.DecimalField(decimal_places=2, help_text='Sum of employer pension contributions remitted', max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Grand total remitted (employee + employer)', max_digits=18)),
                ('pension_provider', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('remitted', 'Remitted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry: DR Employee+Employer Pension Payable, CR Cash/Bank', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pension_remittance_entries', to='transactions.transaction')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('payment_account', models.ForeignKey(blank=True, help_text='Bank/Cash account used for remittance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pension_remittance_payments', to='accounts.account')),
                ('payrolls', models.ManyToManyField(blank=True, help_text='Payrolls whose pension has been included in this remittance', related_name='pension_remittances', to='hr.payroll')),
                ('remitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pension_remittances_processed', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['-remittance_date'],
                'indexes': [models.Index(fields=['status', 'remittance_date'], name='hr_pensionr_status_06fc13_idx')],
            },
        ),
    ]
