# Generated by Django 5.2.4 on 2026-03-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_hrconfig_paye_development_levy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='employee_pension',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Employee pension contribution deducted from salary (8% of gross)', max_digits=18),
        ),
    ]
