# Generated by Django 5.2.4 on 2026-04-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_salarycomponent_is_pensionable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarycomponent',
            name='is_taxable',
            field=models.BooleanField(default=True, help_text='For EARNING components: include in PAYE taxable income. Set False for statutory non-taxable allowances (e.g. Leave Allowance). DEDUCTION components ignore this flag.'),
        ),
    ]
