# Generated by Django 5.2.4 on 2026-04-30 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_add_contact_fields_and_invoice_bank_flag'),
        ('hr', '0018_paycomponentremovalrequest'),
        ('transactions', '0006_fix_empty_sequence_names'),
        ('users', '0008_role_excluded_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffIOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total cash advance given to the staff member', max_digits=18)),
                ('monthly_installment', models.DecimalField(decimal_places=2, help_text='Fixed amount deducted from salary each month until repaid', max_digits=18)),
                ('balance_remaining', models.DecimalField(decimal_places=2, help_text='Outstanding balance to be recovered', max_digits=18)),
                ('start_month', models.DateField(help_text='First payroll month the deduction should be applied (YYYY-MM-01)')),
                ('reason', models.TextField(help_text='Reason / purpose of the IOU')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='paycomponentremovalrequest',
            new_name='hr_paycompo_status_20b142_idx',
            old_name='hr_pcr_status_idx',
        ),
        migrations.RenameIndex(
            model_name='paycomponentremovalrequest',
            new_name='hr_paycompo_staff_p_5388b0_idx',
            old_name='hr_pcr_spi_status_idx',
        ),
        migrations.RemoveField(
            model_name='paycomponentremovalrequest',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='paycomponentremovalrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paycomponentremovalrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AlterField(
            model_name='paycomponentremovalrequest',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='paycomponentremovalrequest',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salarycomponent',
            name='is_advance',
            field=models.BooleanField(default=False, help_text='For DEDUCTION components only. Set True when this deduction represents a cash advance physically disbursed to the staff member (e.g. Salary Advance, Staff Loan). On approval a journal entry is posted: Dr gl_account / Cr Cash/Bank. Set False for pure salary-reduction deductions (e.g. Development Levy, cooperative dues) where no cash leaves the organisation at the time of approval.'),
        ),
        migrations.AddField(
            model_name='staffiou',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ious_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffiou',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='staffiou',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ious_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffiou',
            name='disbursement_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iou_disbursements', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='staffiou',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffiou',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ious', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='staffiou',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddIndex(
            model_name='staffiou',
            index=models.Index(fields=['staff', 'status'], name='hr_staffiou_staff_i_d0d688_idx'),
        ),
        migrations.AddIndex(
            model_name='staffiou',
            index=models.Index(fields=['status', 'start_month'], name='hr_staffiou_status_c0dffc_idx'),
        ),
    ]
