# Generated by Django 5.2.4 on 2026-05-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_staff_iou'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffiou',
            name='cash_disbursed',
            field=models.BooleanField(blank=True, help_text='True if cash was disbursed; False if payroll-deduction only; None until decided', null=True),
        ),
        migrations.AlterField(
            model_name='staffiou',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
