# Generated by Django 5.2.4 on 2026-05-20 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bank_account_fk_on_expense_and_replenishment'),
        ('branches', '0004_add_contact_fields_and_invoice_bank_flag'),
        ('hr', '0020_staff_iou_pending_approved_cash_disbursed'),
        ('transactions', '0006_fix_empty_sequence_names'),
        ('users', '0008_role_excluded_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='total_nhf',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all NHF deductions for this payroll run (employee 2.5% of basic)', max_digits=18),
        ),
        migrations.AddField(
            model_name='payroll',
            name='total_nsitf',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all NSITF contributions for this payroll run (employer 1% of emolument)', max_digits=18),
        ),
        migrations.AddField(
            model_name='payslip',
            name='nhf',
            field=models.DecimalField(decimal_places=2, default=0, help_text='National Housing Fund deduction: 2.5% of basic salary', max_digits=18),
        ),
        migrations.AddField(
            model_name='payslip',
            name='nsitf',
            field=models.DecimalField(decimal_places=2, default=0, help_text='NSITF contribution: 1% of total emolument (employer cost, not deducted from employee)', max_digits=18),
        ),
        migrations.CreateModel(
            name='PayrollStatutoryFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('filing_type', models.CharField(choices=[('nhf', 'NHF (National Housing Fund)'), ('nsitf', 'NSITF (Social Insurance Trust Fund)')], db_index=True, max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('filing_date', models.DateField(blank=True, help_text='Date submitted to the agency', null=True)),
                ('remittance_date', models.DateField(blank=True, help_text='Date payment was made', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total NHF or NSITF amount for this filing period', max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Agency'), ('remitted', 'Remitted / Paid'), ('rejected', 'Rejected by Agency'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('agency_reference', models.CharField(blank=True, help_text='Transaction/acknowledgement reference from FMBN or NSITF portal', max_length=100)),
                ('last_submission_payload', models.JSONField(blank=True, help_text='Last JSON payload submitted by Java App 2 (StatutoryComplianceService)', null=True)),
                ('last_submission_response', models.JSONField(blank=True, help_text='Last response body received from the agency API', null=True)),
                ('last_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry created on remittance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statutory_filing_entries', to='transactions.transaction')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statutory_filing_payments', to='accounts.account')),
                ('payrolls', models.ManyToManyField(blank=True, help_text='Payrolls included in this filing', related_name='statutory_filings', to='hr.payroll')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statutory_filings_submitted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['-period_end', 'filing_type'],
                'indexes': [models.Index(fields=['filing_type', 'status'], name='hr_payrolls_filing__d2acfd_idx'), models.Index(fields=['period_start', 'period_end'], name='hr_payrolls_period__c10388_idx')],
            },
        ),
    ]
