# Generated by Django 5.2.4 on 2026-05-20 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_ktil_nhf_nsitf_statutory'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='reports_to',
            field=models.ForeignKey(blank=True, help_text='Immediate supervisor. Used for hierarchical client-data access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='role_level',
            field=models.CharField(choices=[('credit_officer', 'Credit Officer'), ('supervisor', 'Supervisor'), ('branch_manager', 'Branch Manager'), ('director', 'Director'), ('operations', 'Operations'), ('admin', 'Admin')], db_index=True, default='operations', help_text='Determines data-access tier for client/loan scoping.', max_length=20),
        ),
    ]
