# Generated by Django 5.2.4 on 2026-06-23 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0013_daily_collection_sheet'),
        ('hr', '0022_staff_role_level_reports_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffiou',
            name='cashier_reconciliation',
            field=models.ForeignKey(blank=True, help_text='Reconciliation record that created this deduction (for shortfall type)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_deductions', to='cash_management.cashreconciliation'),
        ),
        migrations.AddField(
            model_name='staffiou',
            name='deduction_type',
            field=models.CharField(choices=[('advance', 'Cash Advance / IOU'), ('reconciliation', 'Cashier Reconciliation Shortfall')], db_index=True, default='advance', help_text='advance = normal cash advance; reconciliation = salary deduction for cashier shortfall', max_length=20),
        ),
    ]
