# Generated by Django 5.2.4 on 2026-07-28 19:04

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_staffiou_deduction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='allowances',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Dict of allowance_name: {amount, is_taxable}. Example: {"Housing Allowance": {"amount": 50000, "is_taxable": true}}'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='deductions',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Dict of deduction_name: amount'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='paye_breakdown',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='List of PAYE band details for audit. Each item: {band, rate, amount_in_band, tax_in_band, cumulative_balance}'),
        ),
    ]
