# Generated by Django 5.2.4 on 2026-07-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_alter_payslip_allowances_alter_payslip_deductions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrconfig',
            name='enable_development_levy',
            field=models.BooleanField(default=False, help_text='Deduct the annual Development Levy per employee (NTA 2024)'),
        ),
        migrations.AlterField(
            model_name='hrconfig',
            name='enable_pension',
            field=models.BooleanField(default=False, help_text='Enable pension deduction and employer contribution for this branch'),
        ),
    ]
