# Generated by Django 5.2.4 on 2026-07-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_disable_pension_and_dev_levy_existing_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrconfig',
            name='enable_nhf',
            field=models.BooleanField(default=False, help_text='Deduct National Housing Fund contribution (2.5% of basic salary)'),
        ),
    ]
