# Generated by Django 5.2.4 on 2026-07-30 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_code'),
        ('hr', '0027_hrconfig_enable_nhf'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='salary_advance_account',
            field=models.ForeignKey(blank=True, help_text="This staff member's individual Salary Advance sub-account", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_salary_advance_holders', to='accounts.account'),
        ),
    ]
