# Generated by Django 5.2.4 on 2026-09-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0029_staffguarantor_guarantordocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='medical_certificate',
            field=models.URLField(blank=True, help_text='Link to medical certificate (for sick leave)', max_length=500, null=True),
        ),
    ]
