# Generated by Django 5.2.4 on 2026-02-28 12:09

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_account_is_cashier_bank'),
        ('branches', '0003_branch_latitude_branch_longitude'),
        ('cash_management', '0008_pettycashreceipt'),
        ('transactions', '0003_add_financial_report_indexes'),
        ('users', '0003_role_permission_codes_user_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bank_name', models.CharField(help_text='Official name of the bank (e.g., First Bank of Nigeria)', max_length=200)),
                ('bank_code', models.CharField(blank=True, help_text='Bank code (e.g., CBN code, SWIFT code)', max_length=20)),
                ('branch_name', models.CharField(blank=True, help_text='Bank branch name (e.g., Ikeja Branch)', max_length=200)),
                ('address', models.TextField(blank=True, help_text='Physical address of the bank branch')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('account_manager_name', models.CharField(blank=True, help_text="Name of bank's account manager", max_length=200)),
                ('account_manager_phone', models.CharField(blank=True, max_length=50)),
                ('account_manager_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this bank is currently active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this bank')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['bank_name', 'branch_name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_number', models.CharField(db_index=True, help_text='Bank account number', max_length=50, unique=True)),
                ('account_name', models.CharField(help_text='Name on the bank account', max_length=200)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account'), ('fixed_deposit', 'Fixed Deposit'), ('domiciliary', 'Domiciliary Account')], default='current', help_text='Type of bank account', max_length=50)),
                ('currency', models.CharField(default='NGN', help_text='Currency code (e.g., NGN, USD, GBP)', max_length=3)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current balance (should match GL account balance)', max_digits=18)),
                ('daily_withdrawal_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum daily withdrawal limit', max_digits=18, null=True)),
                ('monthly_transaction_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum monthly transaction limit', max_digits=18, null=True)),
                ('requires_dual_approval', models.BooleanField(default=False, help_text='Require two approvers for large transactions')),
                ('dual_approval_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Amount above which dual approval is required', max_digits=18, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this account is active')),
                ('is_suspended', models.BooleanField(default=False, help_text='Whether transactions are temporarily suspended')),
                ('is_cashier_collection_account', models.BooleanField(default=False, help_text='Whether cashiers can transfer to this account (intermediate approval account)')),
                ('iban', models.CharField(blank=True, help_text='International Bank Account Number', max_length=50)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code', max_length=20)),
                ('date_opened', models.DateField(blank=True, help_text='Date when account was opened', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('account_manager', models.ForeignKey(help_text='User responsible for approving transactions on this account', on_delete=django.db.models.deletion.PROTECT, related_name='managed_bank_accounts', to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(help_text='The bank where this account is held', on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='banks.bank')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('gl_account', models.OneToOneField(help_text='General Ledger account (MUST be ASSET type, CHILD level) for this bank account', on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='accounts.account')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'ordering': ['bank__bank_name', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccountBalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('change_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_type', models.CharField(help_text='Type of transaction causing balance change', max_length=50)),
                ('reference_number', models.CharField(max_length=100)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_logs', to='banks.bankaccount')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('transfer_number', models.CharField(db_index=True, help_text='Auto-generated transfer reference number', max_length=50, unique=True)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now, help_text='Date of transfer')),
                ('source_type', models.CharField(choices=[('cashier', 'Cashier Account'), ('bank', 'Bank Account')], help_text='Type of source account', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transfer amount', max_digits=18)),
                ('description', models.TextField(help_text='Purpose of transfer')),
                ('reference_number', models.CharField(blank=True, help_text='External reference number (e.g., bank slip number)', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('second_approved_at', models.DateTimeField(blank=True, null=True)),
                ('second_approval_notes', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, help_text='Supporting document (e.g., bank slip, receipt)', null=True, upload_to='bank_transfers/%Y/%m/')),
                ('approved_by', models.ForeignKey(blank=True, help_text='First approver (account manager)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bank_transfers', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_bank_transfers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_bank_account', models.ForeignKey(help_text='Destination bank account', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='banks.bankaccount')),
                ('initiated_by', models.ForeignKey(help_text='User who initiated the transfer', on_delete=django.db.models.deletion.PROTECT, related_name='initiated_bank_transfers', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry created for this transfer', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transfers', to='transactions.transaction')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_bank_transfers', to=settings.AUTH_USER_MODEL)),
                ('second_approved_by', models.ForeignKey(blank=True, help_text='Second approver (for dual approval)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approved_bank_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_bank_account', models.ForeignKey(blank=True, help_text='Source bank account (if transferring from bank)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='banks.bankaccount')),
                ('source_cashier_account', models.ForeignKey(blank=True, help_text='Source cashier account (if transferring from cashier)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='cash_management.cashieraccount')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Bank Transfer',
                'verbose_name_plural': 'Bank Transfers',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['bank_name'], name='banks_bank_bank_na_15a0db_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['bank_code'], name='banks_bank_bank_co_ae71a0_idx'),
        ),
        migrations.AddIndex(
            model_name='bank',
            index=models.Index(fields=['is_active'], name='banks_bank_is_acti_aa8e36_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together={('bank_name', 'branch_name', 'branch')},
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_number'], name='banks_banka_account_7bdbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_active'], name='banks_banka_is_acti_f823db_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['account_manager'], name='banks_banka_account_c55476_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_cashier_collection_account'], name='banks_banka_is_cash_3caf75_idx'),
        ),
        migrations.AddIndex(
            model_name='bankaccountbalancelog',
            index=models.Index(fields=['bank_account', '-created_at'], name='banks_banka_bank_ac_c0d8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['transfer_number'], name='banks_bankt_transfe_7d9c26_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['transfer_date', 'status'], name='banks_bankt_transfe_b2dbab_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['status'], name='banks_bankt_status_b27f80_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransfer',
            index=models.Index(fields=['initiated_by'], name='banks_bankt_initiat_b60378_idx'),
        ),
    ]
