# Generated by Django 5.2.4 on 2026-03-06 11:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_is_cashier_bank'),
        ('banks', '0001_initial'),
        ('branches', '0004_add_contact_fields_and_invoice_bank_flag'),
        ('users', '0004_add_contact_fields_and_invoice_bank_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_primary_for_invoices',
            field=models.BooleanField(db_index=True, default=False, help_text="Show this account's details in the 'Payment Details' section of invoices and other outgoing documents. You may flag multiple accounts (e.g. NGN current + USD domiciliary)."),
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['is_primary_for_invoices'], name='banks_banka_is_prim_a278c3_idx'),
        ),
    ]
