# Generated by Django 5.2.4 on 2026-03-20 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_bankpayment'),
        ('users', '0007_tenant_domainconfig_customlabels_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bankpayment',
            new_name='banks_bankp_payment_650277_idx',
            old_name='banks_bankp_payment_7d6995_idx',
        ),
        migrations.RenameIndex(
            model_name='bankpayment',
            new_name='banks_bankp_payment_87a1d4_idx',
            old_name='banks_bankp_payment_2881a5_idx',
        ),
        migrations.RenameIndex(
            model_name='bankpayment',
            new_name='banks_bankp_status_edc44c_idx',
            old_name='banks_bankp_status_0a7c03_idx',
        ),
        migrations.RenameIndex(
            model_name='bankpayment',
            new_name='banks_bankp_bank_ac_65cbf4_idx',
            old_name='banks_bankp_bank_ac_0b2c78_idx',
        ),
        migrations.AlterField(
            model_name='bankpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankpayment',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankpayment',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
    ]
