# Generated by Django 5.2.4 on 2026-03-25 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_rename_banks_bankp_payment_7d6995_idx_banks_bankp_payment_650277_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankpayment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankpayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bank_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankpayment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if rejected)'),
        ),
        migrations.AlterField(
            model_name='bankpayment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
    ]
