# Generated by Django 5.2.4 on 2026-05-20 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0008_bankpayment_advance_applied'),
        ('branches', '0004_add_contact_fields_and_invoice_bank_flag'),
        ('clients', '0006_ktil_microfinance_fields'),
        ('users', '0008_role_excluded_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankFeedConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('bank_name', models.CharField(help_text='Name of the bank (e.g. GTBank, Zenith)', max_length=200)),
                ('bank_code', models.CharField(blank=True, help_text='CBN bank sort code / NIP code (e.g. 058 for GTBank)', max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending — awaiting bank authorisation'), ('active', 'Active — consent granted'), ('expired', 'Expired'), ('revoked', 'Revoked by client'), ('failed', 'Authorisation failed')], db_index=True, default='pending', max_length=20)),
                ('consent_granted_at', models.DateTimeField(blank=True, null=True)),
                ('consent_expires_at', models.DateTimeField(blank=True, null=True)),
                ('consent_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('consent_token', models.TextField(blank=True, help_text='Encrypted OAuth/API access token stored by Java App 3')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted OAuth refresh token for renewing access')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, help_text='Result of the last sync attempt (e.g. "success", "bank_error")', max_length=50)),
                ('sync_error_detail', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('client', models.ForeignKey(help_text='Client who granted this bank feed consent', on_delete=django.db.models.deletion.CASCADE, related_name='bank_feed_consents', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('phoenix_bank_account', models.ForeignKey(blank=True, help_text='Phoenix internal bank account this feed reconciles against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_consents', to='banks.bankaccount')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_feed_consents_recorded', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Bank Feed Consent',
                'verbose_name_plural': 'Bank Feed Consents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='banks_bankf_client__70dfaa_idx'), models.Index(fields=['status', 'consent_expires_at'], name='banks_bankf_status_3b20bd_idx')],
            },
        ),
    ]
