# Generated by Django 5.2.4 on 2026-05-21 14:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_add_bank_feed_consent'),
        ('branches', '0004_add_contact_fields_and_invoice_bank_flag'),
        ('transactions', '0006_fix_empty_sequence_names'),
        ('users', '0008_role_excluded_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('statement_file', models.FileField(help_text='CSV or Excel bank statement file', upload_to='bank_statements/%Y/%m/')),
                ('statement_date_from', models.DateField(blank=True, null=True)),
                ('statement_date_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded — awaiting parse'), ('parsing', 'Parsing in progress'), ('parsed', 'Parsed — awaiting matching'), ('matching', 'Auto-matching in progress'), ('matched', 'Matching complete'), ('reconciled', 'Fully reconciled'), ('error', 'Parse / match error')], db_index=True, default='uploaded', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('unmatched_count', models.PositiveIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_uploads', to='banks.bankaccount')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, help_text='Closing balance as per the bank statement for this line', max_digits=18, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=200)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('auto_matched', 'Auto-matched by Java service'), ('manual_matched', 'Manually matched'), ('excluded', 'Excluded / ignored')], db_index=True, default='unmatched', max_length=20)),
                ('match_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score (0–100) provided by the Java matching engine', max_digits=5, null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Original parsed row data from the upload file')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statement_matches', to='transactions.transaction')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='banks.bankstatementupload')),
            ],
            options={
                'ordering': ['value_date', 'id'],
                'indexes': [models.Index(fields=['upload', 'match_status'], name='banks_banks_upload__d37a57_idx'), models.Index(fields=['value_date', 'match_status'], name='banks_banks_value_d_23735d_idx')],
            },
        ),
    ]
