# Generated by Django 5.2.4 on 2026-05-25 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0010_insurance_verifier_disbursement'),
        ('branches', '0005_insurance_verifier_disbursement'),
        ('users', '0010_daily_reconciliation_and_exception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reconciliation_date', models.DateField(db_index=True, help_text='The business date of the bank statement being reconciled')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('statement_file', models.FileField(help_text='Raw CSV file as uploaded by the branch manager', upload_to='bank_statements/%Y/%m/')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('total_bank_transactions', models.PositiveIntegerField(default=0)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('unmatched_bank_count', models.PositiveIntegerField(default=0)),
                ('unmatched_erp_count', models.PositiveIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(help_text='The branch bank account being reconciled', on_delete=django.db.models.deletion.PROTECT, related_name='daily_reconciliations', to='banks.bankaccount')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Reconciliation',
                'verbose_name_plural': 'Daily Reconciliations',
                'ordering': ['-reconciliation_date', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exception_type', models.CharField(choices=[('bank_only', 'Bank Only — not in ERP'), ('erp_only', 'ERP Only — not in bank'), ('amount_diff', 'Amount Difference')], db_index=True, max_length=20)),
                ('bank_transaction_id', models.UUIDField(blank=True, help_text='UUID assigned by Java to this bank transaction', null=True)),
                ('bank_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('bank_narration', models.TextField(blank=True)),
                ('bank_date', models.DateField(blank=True, null=True)),
                ('loan_payment_id', models.IntegerField(blank=True, help_text='ID of the ERP transaction (transactions_transaction.id)', null=True)),
                ('erp_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('erp_narration', models.TextField(blank=True)),
                ('erp_date', models.DateField(blank=True, null=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='banks.dailyreconciliation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_recon_exceptions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Reconciliation Exception',
                'verbose_name_plural': 'Reconciliation Exceptions',
                'ordering': ['reconciliation', 'exception_type'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyreconciliation',
            index=models.Index(fields=['bank_account', 'reconciliation_date'], name='banks_daily_bank_ac_6163f5_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreconciliation',
            index=models.Index(fields=['status'], name='banks_daily_status_29524c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreconciliation',
            unique_together={('bank_account', 'reconciliation_date')},
        ),
        migrations.AddIndex(
            model_name='reconciliationexception',
            index=models.Index(fields=['reconciliation', 'exception_type'], name='banks_recon_reconci_baa586_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationexception',
            index=models.Index(fields=['reconciliation', 'resolved'], name='banks_recon_reconci_4befd2_idx'),
        ),
    ]
