# Generated by Django 5.2.4 on 2026-05-26 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0011_daily_reconciliation_and_exception'),
        ('branches', '0005_insurance_verifier_disbursement'),
        ('transactions', '0006_fix_empty_sequence_names'),
        ('users', '0010_daily_reconciliation_and_exception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankFeedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('transaction_date', models.DateField(db_index=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], db_index=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('bank_reference', models.CharField(blank=True, db_index=True, help_text='Reference/ID assigned by the bank', max_length=100)),
                ('java_transaction_id', models.UUIDField(help_text='Stable UUID assigned by Java App 3 for idempotency', unique=True)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched — awaiting auto-match'), ('matched', 'Matched — paired with ERP transaction'), ('exception', 'Exception — could not auto-match'), ('ignored', 'Ignored — excluded from reconciliation')], db_index=True, default='unmatched', max_length=15)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=3, help_text='Auto-match confidence score from Java (0.000–1.000)', max_digits=4, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('bank_account', models.ForeignKey(help_text='Internal Phoenix BankAccount this transaction belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='feed_transactions', to='banks.bankaccount')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('consent', models.ForeignKey(help_text='BankFeedConsent record used to pull this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='feed_transactions', to='banks.bankfeedconsent')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('matched_transaction', models.ForeignKey(blank=True, help_text='ERP Transaction (GL journal entry) this feed transaction was matched to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_feed_matches', to='transactions.transaction')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feed_transactions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Bank Feed Transaction',
                'verbose_name_plural': 'Bank Feed Transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['bank_account', 'match_status'], name='banks_bankf_bank_ac_3de268_idx'), models.Index(fields=['transaction_date', 'match_status'], name='banks_bankf_transac_0d5dab_idx'), models.Index(fields=['java_transaction_id'], name='banks_bankf_java_tr_ddf8dc_idx')],
            },
        ),
    ]
