# Generated by Django 5.2.4 on 2026-05-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0012_java_app_prep_bvn_bankfeed_loanwriteoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='feed_connected',
            field=models.BooleanField(db_index=True, default=False, help_text='True when a live bank-feed consent is active for this account. Set by the bank-feed Java service after successful consent link. Displayed in the UI as "Live feed active" vs "Manual only".'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='last_feed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful bank-feed sync from the Java reconciliation service. Used to detect stale feeds.', null=True),
        ),
    ]
