# Generated by Django 5.2.4 on 2026-07-07 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0015_banktransfer_cashier_destination'),
        ('users', '0010_daily_reconciliation_and_exception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationexception',
            name='direction',
            field=models.CharField(choices=[('CREDIT', 'Credit — money in'), ('DEBIT', 'Debit — money out')], db_index=True, default='CREDIT', help_text='Which side of the statement this exception came from. DEBIT exceptions only appear when a reconciliation opted in to debit checking.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='reconciliationexception',
            index=models.Index(fields=['reconciliation', 'direction'], name='banks_recon_reconci_663e66_idx'),
        ),
    ]
