# Generated by Django 5.2.4 on 2026-07-07 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0016_reconciliationexception_direction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationBankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_ref', models.CharField(help_text="The bank's own reference, or a deterministic hash when none was supplied", max_length=500)),
                ('value_date', models.DateField(db_index=True)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit — money in'), ('DEBIT', 'Debit — money out')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('narration', models.TextField(blank=True)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('matched', models.BooleanField(db_index=True, default=False)),
                ('match_confidence', models.CharField(blank=True, max_length=10)),
                ('matched_erp_payment_id', models.IntegerField(blank=True, null=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_transactions', to='banks.bankaccount')),
            ],
            options={
                'verbose_name': 'Reconciliation Bank Transaction',
                'verbose_name_plural': 'Reconciliation Bank Transactions',
                'indexes': [models.Index(fields=['bank_account', 'value_date', 'matched'], name='banks_recon_bank_ac_9a3ed2_idx')],
                'unique_together': {('bank_account', 'bank_ref')},
            },
        ),
    ]
