# Generated by Django 5.2.4 on 2026-07-14 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0017_reconciliationbanktransaction'),
        ('branches', '0005_insurance_verifier_disbursement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreconciliation',
            name='rerun_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationexception',
            name='erp_branch',
            field=models.ForeignKey(blank=True, help_text="The officer's branch, if any", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_exceptions_as_erp_branch', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='reconciliationexception',
            name='is_high_priority',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='reconciliationexception',
            name='officer',
            field=models.ForeignKey(blank=True, help_text='User who recorded the ERP-side transaction, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recon_exceptions_as_officer', to=settings.AUTH_USER_MODEL),
        ),
    ]
