# Generated by Django 5.2.4 on 2026-07-16 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0022_dailyreconciliation_include_debits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationbanktransaction',
            name='matched_erp_had_reference',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationbanktransaction',
            name='matched_erp_officer',
            field=models.ForeignKey(blank=True, help_text='User who recorded the ERP-side payment this line matched to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_bank_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationbanktransaction',
            name='posting_lag_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreconciliation',
            name='include_debits',
            field=models.BooleanField(default=False),
        ),
    ]
