# Generated by Django 5.2.4 on 2026-07-16 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0024_backfill_match_time_accountability_fields'),
        ('branches', '0005_insurance_verifier_disbursement'),
        ('users', '0010_daily_reconciliation_and_exception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reconciliationexception',
            constraint=models.UniqueConstraint(condition=models.Q(('exception_type', 'bank_only')), fields=('reconciliation', 'bank_transaction_id'), name='uniq_bank_only_exception_per_recon'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationexception',
            constraint=models.UniqueConstraint(condition=models.Q(('exception_type', 'erp_only')), fields=('reconciliation', 'loan_payment_id'), name='uniq_erp_only_exception_per_recon'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationexception',
            constraint=models.UniqueConstraint(condition=models.Q(('exception_type', 'amount_diff')), fields=('reconciliation', 'bank_transaction_id', 'loan_payment_id'), name='uniq_amount_diff_exception_per_recon'),
        ),
    ]
