# Generated by Django 5.2.4 on 2026-07-16 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0025_reconciliationexception_uniq_bank_only_exception_per_recon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationbanktransaction',
            name='unmatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationbanktransaction',
            name='unmatched_by',
            field=models.ForeignKey(blank=True, help_text='Director who manually undid an incorrect auto-match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unmatched_bank_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationbanktransaction',
            name='unmatched_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reconciliationexception',
            name='netted_with',
            field=models.ForeignKey(blank=True, help_text='The other bank_only exception this was manually netted against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='banks.reconciliationexception'),
        ),
        migrations.AddField(
            model_name='reconciliationexception',
            name='pending_bank_payment',
            field=models.ForeignKey(blank=True, help_text='Draft/pending payment created to close this exception via expense posting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_exception_resolutions', to='banks.bankpayment'),
        ),
    ]
