# Generated by Django 5.2.4 on 2026-07-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0027_reconciliationexception_second_resolution_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationexception',
            name='netted_with',
            field=models.ForeignKey(blank=True, help_text='The other exception this was manually linked/netted against', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='banks.reconciliationexception'),
        ),
    ]
