# Generated by Django 5.2.4 on 2026-07-18 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0028_alter_reconciliationexception_netted_with'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationexception',
            name='unresolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reconciliationexception',
            name='unresolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unresolved_recon_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationexception',
            name='unresolved_reason',
            field=models.TextField(blank=True),
        ),
    ]
