# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('collateral_type', models.CharField(help_text='Type of collateral (property, vehicle, etc.)', max_length=100)),
                ('description', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('document_reference', models.CharField(blank=True, max_length=200)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pledged', 'Pledged'), ('verified', 'Verified'), ('released', 'Released')], default='pledged', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanGuarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('guaranteed_amount', models.DecimalField(decimal_places=2, help_text='Maximum amount guaranteed', max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('interest_calculation_method', models.CharField(choices=[('flat', 'Flat Rate'), ('reducing_balance', 'Reducing Balance'), ('compound', 'Compound Interest')], default='reducing_balance', max_length=20)),
                ('default_interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate percentage', max_digits=5)),
                ('min_term_months', models.PositiveIntegerField(default=1)),
                ('max_term_months', models.PositiveIntegerField(default=60)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('allowed_repayment_frequencies', models.JSONField(default=list, help_text="['monthly', 'weekly']")),
                ('processing_fee_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='percentage', max_length=20)),
                ('processing_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('processing_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('late_payment_penalty_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='percentage', max_length=20)),
                ('late_payment_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('grace_period_days', models.PositiveIntegerField(default=0, help_text='Days after due date before penalty applies')),
                ('requires_collateral', models.BooleanField(default=False)),
                ('collateral_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of loan amount required as collateral', max_digits=5)),
                ('requires_guarantor', models.BooleanField(default=False)),
                ('min_guarantors', models.PositiveIntegerField(default=0)),
                ('requires_approval', models.BooleanField(default=True)),
                ('approval_workflow_code', models.CharField(blank=True, help_text='Code of workflow template for approval process', max_length=50)),
                ('additional_config', models.JSONField(default=dict, help_text='Additional product-specific configuration')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fees_due', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('penalty_due', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=18)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('penalty_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('days_late', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('loan_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('application_date', models.DateField(default=django.utils.timezone.now)),
                ('application_notes', models.TextField(blank=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, help_text='Amount requested by client', max_digits=18)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount approved (may differ from requested)', max_digits=18, null=True)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0, help_text='Actual amount disbursed', max_digits=18)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate percentage', max_digits=5)),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('term_months', models.PositiveIntegerField(help_text='Loan term in months')),
                ('repayment_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='monthly', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('paid_off', 'Fully Paid'), ('defaulted', 'Defaulted'), ('written_off', 'Written Off'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('first_payment_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('outstanding_interest', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('outstanding_fees', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('outstanding_penalties', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('penalties_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('installment_amount', models.DecimalField(decimal_places=2, default=0, help_text='Regular installment amount', max_digits=18)),
                ('number_of_installments', models.PositiveIntegerField(default=0)),
                ('installments_paid', models.PositiveIntegerField(default=0)),
                ('days_in_arrears', models.PositiveIntegerField(default=0)),
                ('arrears_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('risk_classification', models.CharField(choices=[('performing', 'Performing'), ('watch', 'Watch'), ('substandard', 'Substandard'), ('doubtful', 'Doubtful'), ('loss', 'Loss')], default='performing', max_length=20)),
                ('metadata', models.JSONField(default=dict, help_text='Additional loan-specific data')),
                ('account', models.OneToOneField(limit_choices_to={'account_level': 'CHILD', 'account_type': 'LOAN'}, on_delete=django.db.models.deletion.PROTECT, related_name='loan_account_detail', to='accounts.account')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
    ]
