# Generated by Django 5.2.4 on 2026-05-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_gl_account_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='batch_accrual_posted',
            field=models.BooleanField(default=False, help_text="True when the current period's accrual journal entry has been posted by the batch processor"),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='last_batch_processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last accrual/arrears batch run by the Java batch processor', null=True),
        ),
    ]
