# Generated by Django 5.2.4 on 2026-05-21 14:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bank_account_fk_on_expense_and_replenishment'),
        ('branches', '0005_insurance_verifier_disbursement'),
        ('loans', '0004_ktil_microfinance_fields'),
        ('users', '0008_role_excluded_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='insurance_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Insurance premium charged at approval (% of approved amount)', max_digits=18),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='insurance_income_account',
            field=models.ForeignKey(blank=True, help_text='Income GL account for insurance premiums collected on this loan product', limit_choices_to={'account_type': 'INCOME'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_products_insurance_income', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='insurance_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Insurance premium as percentage of approved loan amount', max_digits=5),
        ),
        migrations.CreateModel(
            name='LoanDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved for Disbursement'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('cancelled', 'Cancelled')], db_index=True, default='pending_approval', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_disbursements', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_disbursements', to=settings.AUTH_USER_MODEL)),
                ('disbursement_account', models.ForeignKey(blank=True, help_text='Cash/Bank GL account to disburse from. Falls back to product default.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_requests', to='accounts.account')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_request', to='loans.loanaccount')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='User who requested disbursement (must differ from approver)', on_delete=django.db.models.deletion.PROTECT, related_name='requested_disbursements', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nin_used', models.CharField(blank=True, db_index=True, max_length=11)),
                ('active_loans_elsewhere', models.PositiveIntegerField(default=0)),
                ('total_active_exposure', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sum of outstanding principal across all branches', max_digits=18)),
                ('default_rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of closed loans that defaulted/written-off', max_digits=5)),
                ('flags', models.JSONField(default=list, help_text="List of flag strings, e.g. ['loan_hopping', 'prior_default']")),
                ('recommended_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('verdict', models.CharField(choices=[('pending', 'Pending review'), ('pass', 'Pass — proceed to approval'), ('refer', 'Refer — proceed with caution'), ('decline', 'Decline — credit risk too high')], db_index=True, default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to='loans.loanaccount')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_verification_reviews', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
