# Generated by Django 5.2.4 on 2026-05-26 11:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_insurance_verifier_disbursement'),
        ('loans', '0005_insurance_verifier_disbursement'),
        ('transactions', '0006_fix_empty_sequence_names'),
        ('users', '0010_daily_reconciliation_and_exception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanWriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference_number', models.CharField(db_index=True, help_text='Auto-generated reference (e.g. WO-2026-0001)', max_length=50, unique=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, help_text='Outstanding principal at the time of write-off request', max_digits=18)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding interest at the time of write-off request', max_digits=18)),
                ('fees_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding fees/penalties at the time of write-off request', max_digits=18)),
                ('total_write_off_amount', models.DecimalField(decimal_places=2, help_text='Total amount written off (principal + interest + fees)', max_digits=18)),
                ('reason', models.TextField(help_text='Justification for the write-off')),
                ('write_off_date', models.DateField(blank=True, help_text='Date the write-off was executed (set on approval + execution)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_write_offs_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry: Dr Provision for Loan Losses / Cr Loan Receivable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_write_off_entries', to='transactions.transaction')),
                ('loan', models.ForeignKey(help_text='Loan account to be written off', on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='loans.loanaccount')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_write_offs_requested', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Loan Write-Off',
                'verbose_name_plural': 'Loan Write-Offs',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['loan', 'status'], name='loans_loanw_loan_id_7a5c0b_idx'), models.Index(fields=['status', 'requested_at'], name='loans_loanw_status_8579ce_idx')],
            },
        ),
    ]
