# Generated by Django 5.2.4 on 2026-06-25 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_code'),
        ('branches', '0005_insurance_verifier_disbursement'),
        ('loans', '0014_fix_loanguarantor'),
        ('savings', '0004_savingsproduct_withdrawal_models'),
        ('users', '0010_daily_reconciliation_and_exception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanaccount',
            name='term_months',
            field=models.PositiveIntegerField(help_text='Term value — interpret using term_unit (e.g. 23 weeks, 6 months, 50 days).'),
        ),
        migrations.AlterField(
            model_name='loanaccount',
            name='term_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='months', help_text='Unit in which term_months is expressed.', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanfeeapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanfeeapplication',
            name='debit_destination_used',
            field=models.CharField(blank=True, default='', help_text="Actual debit destination: 'cashier' or 'savings'.", max_length=20),
        ),
        migrations.AlterField(
            model_name='loanfeeapplication',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanfeeapplication',
            name='savings_account_debited',
            field=models.ForeignKey(blank=True, help_text="The savings account debited when debit_destination_used='savings'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_debits', to='savings.savingsaccount'),
        ),
        migrations.AlterField(
            model_name='loanfeeapplication',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='first_repayment_buffer_days',
            field=models.PositiveIntegerField(default=0, help_text="Minimum calendar days from disbursement before the first repayment is due. 0 = follows normal cadence. E.g. 14 means first weekly repayment won't be before day 14."),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_suspense_account',
            field=models.ForeignKey(blank=True, help_text='Account used to park suspended interest on NPL loans.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_products_interest_suspense', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='max_term_months',
            field=models.PositiveIntegerField(default=60, help_text="Maximum term value (in the product's term_unit)."),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='min_term_months',
            field=models.PositiveIntegerField(default=1, help_text="Minimum term value (in the product's term_unit)."),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='term_unit',
            field=models.CharField(choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], default='months', help_text='Unit in which min/max terms and loan terms are expressed.', max_length=10),
        ),
        migrations.AlterField(
            model_name='loanproductfee',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanproductfee',
            name='gl_income_account',
            field=models.ForeignKey(help_text='Income GL account where this fee is posted.', limit_choices_to={'account_type': 'INCOME'}, on_delete=django.db.models.deletion.PROTECT, related_name='loan_product_fee_lines', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='loanproductfee',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanproductfee',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AlterField(
            model_name='loanproductsavingsrequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanproductsavingsrequirement',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanproductsavingsrequirement',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AlterField(
            model_name='loanrepaymentrequest',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='loanrepaymentrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanrepaymentrequest',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanrepaymentrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
    ]
