# Generated by Django 5.2.4 on 2026-06-30 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_insurance_verifier_disbursement'),
        ('clients', '0014_guarantor_model'),
        ('loans', '0015_alter_loanaccount_term_months_and_more'),
        ('users', '0010_daily_reconciliation_and_exception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loanguarantor',
            unique_together={('loan', 'guarantor')},
        ),
        migrations.AddField(
            model_name='loanguarantor',
            name='guarantor_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_guarantees', to='clients.guarantor'),
        ),
        migrations.AlterField(
            model_name='loanguarantor',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guaranteed_loans', to='clients.client'),
        ),
        migrations.AlterUniqueTogether(
            name='loanguarantor',
            unique_together={('loan', 'guarantor'), ('loan', 'guarantor_person')},
        ),
        migrations.AddIndex(
            model_name='loanguarantor',
            index=models.Index(fields=['guarantor_person'], name='loans_loang_guarant_e20489_idx'),
        ),
    ]
