# Generated by Django 5.2.4 on 2026-07-06 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_code'),
        ('loans', '0018_loanrepaymentrequest_covered_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='interest_deferral_active',
            field=models.BooleanField(default=False, help_text='True if this loan was disbursed while its product had the deferred/unearned interest income accounts configured — permanently locks this loan onto the new GL flow regardless of later product reconfiguration.'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='interest_writeoff_expense_account',
            field=models.ForeignKey(blank=True, help_text='EXPENSE account debited when a loan is written off with remaining unrecognized unearned interest — recognizes that permanently-booked income will never be collected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_products_interest_writeoff_expense', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='unearned_interest_income_account',
            field=models.ForeignKey(blank=True, help_text='LIABILITY account for deferred/unearned interest income. Credited at disbursement for the full scheduled interest (Interest Income is credited in full at the same time and stays permanent); debited as each installment is recognized as earned. Carries a debit (negative) balance between disbursement and full recognition — this is expected. Leave blank to keep the legacy behavior of crediting interest_income_account only at payment time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_products_unearned_interest', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='loanrepaymentschedule',
            name='interest_recognized',
            field=models.BooleanField(default=False, help_text="True once this installment's interest has moved from Unearned Interest Income into Interest Receivable (earned)."),
        ),
        migrations.AddField(
            model_name='loanrepaymentschedule',
            name='interest_recognized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrepaymentschedule',
            name='interest_written_off',
            field=models.BooleanField(default=False, help_text="True if this installment's interest was flushed to expense on loan write-off rather than genuinely recognized as earned."),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='accrued_interest_account',
            field=models.ForeignKey(blank=True, help_text="ASSET account for interest receivable — debited when an installment's interest is recognized as earned (due date reached), credited when that interest is actually collected. Only used when unearned_interest_income_account is also configured.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_products_accrued_interest', to='accounts.account'),
        ),
    ]
