# Generated by Django 5.2.4 on 2026-07-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_unearned_interest_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='origin',
            field=models.CharField(choices=[('native', 'Originated in Phoenix'), ('legacy_import', 'Imported from legacy system')], default='native', help_text='Where this loan record came from. Purely informational for portfolio reporting/audits — does not affect GL posting behavior, which is already determined by interest_deferral_active and by whether the loan ever goes through disburse().', max_length=20),
        ),
    ]
