# Generated by Django 5.2.4 on 2026-07-10 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_code'),
        ('branches', '0005_insurance_verifier_disbursement'),
        ('loans', '0022_loanaccount_rejection_reason'),
        ('transactions', '0006_fix_empty_sequence_names'),
        ('users', '0010_daily_reconciliation_and_exception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='original_disbursement_date',
            field=models.DateField(blank=True, help_text="Set once, at the loan's first disburse() and never touched again. disbursement_date itself gets overwritten on restructure() (it marks the current repayment cycle's start), so vintage/cohort reporting should key off this field instead.", null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='restructure_interest_income_account',
            field=models.ForeignKey(blank=True, help_text='Separate income GL account for the incremental interest charged on term-extension restructures (kept apart from interest_income_account so restructure revenue can be monitored on its own). Required before any restructure on this product can be approved.', limit_choices_to={'account_type': 'INCOME'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_products_restructure_interest_income', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='loanrestructure',
            name='carried_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='loanrestructure',
            name='carried_penalties',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='loanrestructure',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_restructure_journals', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='loanrestructure',
            name='normal_interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='loanrestructure',
            name='restructure_interest_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='LoanRestructureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_term', models.PositiveIntegerField(help_text="Proposed new term value, in the loan's current term_unit.")),
                ('effective_date', models.DateField(blank=True, help_text='Defaults to today at approval time if left blank.', null=True)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restructure_requests', to='loans.loanaccount')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_loan_restructure_requests', to=settings.AUTH_USER_MODEL)),
                ('restructure', models.ForeignKey(blank=True, help_text='Set once approved — the audit record the approval produced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='loans.loanrestructure')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loan_restructure_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
