# Generated by Django 5.2.4 on 2026-07-17 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_insurance_verifier_disbursement'),
        ('clients', '0014_guarantor_model'),
        ('loans', '0023_loanaccount_original_disbursement_date_and_more'),
        ('transactions', '0006_fix_empty_sequence_names'),
        ('users', '0010_daily_reconciliation_and_exception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offlinepaymentrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlinepaymentrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AlterField(
            model_name='offlinepaymentrecord',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='offlinepaymentrecord',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LoanDisbursementCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference_number', models.CharField(db_index=True, help_text='Auto-generated reference (e.g. LCOR-A1B2C3D4)', max_length=50, unique=True)),
                ('reason', models.TextField(help_text='Why the original loan was disbursed to the wrong customer')),
                ('status', models.CharField(choices=[('pending', 'Pending First Approval'), ('awaiting_second_approval', 'Awaiting Second Approval'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('first_approved_at', models.DateTimeField(blank=True, null=True)),
                ('first_approval_notes', models.TextField(blank=True)),
                ('second_approved_at', models.DateTimeField(blank=True, null=True)),
                ('second_approval_notes', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('correct_client', models.ForeignKey(help_text='The customer the loan should have been disbursed to', on_delete=django.db.models.deletion.PROTECT, related_name='loan_disbursement_corrections', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('first_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_corrections_first_approved', to=settings.AUTH_USER_MODEL)),
                ('new_loan', models.ForeignKey(blank=True, help_text='The replacement loan created and disbursed for the correct client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loans.loanaccount')),
                ('original_loan', models.ForeignKey(help_text='The loan that was disbursed to the wrong customer', on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_corrections', to='loans.loanaccount')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_corrections_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_corrections_requested', to=settings.AUTH_USER_MODEL)),
                ('reversal_journal_entry', models.ForeignKey(blank=True, help_text="The reversal of the original loan's disbursement journal entry", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_correction_reversals', to='transactions.transaction')),
                ('second_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_corrections_second_approved', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Loan Disbursement Correction',
                'verbose_name_plural': 'Loan Disbursement Corrections',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='loans_loand_status_73c740_idx'), models.Index(fields=['original_loan', 'status'], name='loans_loand_origina_9bbfbd_idx')],
            },
        ),
    ]
