# Generated by Django 5.2.4 on 2026-07-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0024_offlinepaymentrecord_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='first_repayment_buffer_days',
            field=models.PositiveIntegerField(default=0, help_text='Extra calendar days added on top of the first naturally-occurring repayment date. 0 = follows normal cadence. E.g. for a weekly loan, a buffer of 7 pushes the first repayment from day 7 to day 14.'),
        ),
    ]
