# Generated by Django 5.2.4 on 2026-08-05 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_insurance_verifier_disbursement'),
        ('loans', '0025_alter_loanproduct_first_repayment_buffer_days'),
        ('transactions', '0006_fix_empty_sequence_names'),
        ('users', '0011_alter_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRepaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_applied', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('interest_applied', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('fees_applied', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('penalty_applied', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayment_allocations', to='transactions.transaction')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_allocations', to='loans.loanaccount')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='loans.loanrepaymentschedule')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['journal_entry'], name='loans_loanr_journal_99dac1_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoanRepaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference_number', models.CharField(db_index=True, help_text='Auto-generated reference (e.g. LREV-A1B2C3D4)', max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount of the payment being reversed (for display/audit)', max_digits=18)),
                ('reason', models.TextField(help_text='Why this repayment is being reversed')),
                ('status', models.CharField(choices=[('pending', 'Pending First Approval'), ('awaiting_second_approval', 'Awaiting Second Approval'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('first_approved_at', models.DateTimeField(blank=True, null=True)),
                ('first_approval_notes', models.TextField(blank=True)),
                ('second_approved_at', models.DateTimeField(blank=True, null=True)),
                ('second_approval_notes', models.TextField(blank=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('first_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayment_reversals_first_approved', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(help_text='The LNPMT payment transaction being reversed', on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayment_reversal_requests', to='transactions.transaction')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_reversals', to='loans.loanaccount')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayment_reversals_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayment_reversals_requested', to=settings.AUTH_USER_MODEL)),
                ('reversal_journal_entry', models.ForeignKey(blank=True, help_text="The reversal of the original payment's journal entry", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayment_reversal_results', to='transactions.transaction')),
                ('second_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayment_reversals_second_approved', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Loan Repayment Reversal',
                'verbose_name_plural': 'Loan Repayment Reversals',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='loans_loanr_status_452b6c_idx'), models.Index(fields=['loan', 'status'], name='loans_loanr_loan_id_b0b12a_idx'), models.Index(fields=['journal_entry', 'status'], name='loans_loanr_journal_cc8ca8_idx')],
            },
        ),
    ]
