# Generated by Django 5.2.4 on 2026-08-06 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0026_loanrepaymentallocation_loanrepaymentreversal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrepaymentallocation',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_allocations', to='loans.loanrepaymentschedule'),
        ),
    ]
