# Generated by Django 5.2.4 on 2026-08-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0027_alter_loanrepaymentallocation_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='penalty_accrual_active',
            field=models.BooleanField(default=False, help_text='True once this loan has had at least one late-payment penalty recognized as income at assessment time (Dr. Loan Receivable / Cr. Penalty Income — see update_loan_status.py), instead of at payment time. record_payment() then collects the penalty portion straight against the Loan Receivable instead of crediting Income again, since it was already booked when the penalty accrued.'),
        ),
    ]
