# Generated by Django 5.2.4 on 2026-08-13 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_code'),
        ('loans', '0028_loanaccount_penalty_accrual_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproductfee',
            name='gl_income_account',
            field=models.ForeignKey(help_text='GL account where this fee is posted. Use an Income account for fees recognized as revenue, or a Liability account for pass-through collections held on behalf of a third party (e.g. Union Purse).', limit_choices_to={'account_type__in': ['INCOME', 'LIABILITY']}, on_delete=django.db.models.deletion.PROTECT, related_name='loan_product_fee_lines', to='accounts.account'),
        ),
    ]
