# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[1-5]\\d{2}(-\\d{3})?$', 'Must be 101–599 for parent (3 digits), or parent-001 format for child (e.g., 101-001).')])),
                ('name', models.CharField(max_length=100)),
                ('account_level', models.CharField(choices=[('PARENT', 'Parent Account (General Ledger)'), ('CHILD', 'Child Account (Sub-Account)')], default='CHILD', help_text='Whether this is a parent (GL) or child account', max_length=10)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset Account'), ('LIABILITY', 'Liability Account'), ('EQUITY', 'Equity Account'), ('INCOME', 'Income Account'), ('EXPENSE', 'Expense Account'), ('LOAN', 'Loan Account'), ('SAVINGS', 'Savings Account')], default='ASSET', help_text='Type of account', max_length=20)),
                ('balance_bf', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance brought forward', max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current balance (updated atomically)', max_digits=18)),
                ('version', models.IntegerField(default=0, help_text='Version number for optimistic locking')),
                ('is_system_account', models.BooleanField(default=False, help_text='System-managed account (cannot be deleted)')),
                ('allow_manual_entries', models.BooleanField(default=True, help_text='Allow manual transaction entries')),
                ('enable_smart_forms', models.BooleanField(default=True, help_text='Enable automatic form/workflow generation for this account')),
                ('default_patterns', models.JSONField(default=list, help_text='Default transaction patterns (created automatically)')),
            ],
        ),
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('section', models.PositiveSmallIntegerField(choices=[(1, 'Assets (100–199)'), (2, 'Liabilities (200–299)'), (3, 'Equity (300–399)'), (4, 'Income/Income (400–499)'), (5, 'Expenses (500–599)')])),
                ('name', models.CharField(max_length=100)),
                ('code_prefix', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_system_category', models.BooleanField(default=False, help_text='True if this category is required by ERP models (Savings, Inventory, Loans, etc.)')),
            ],
            options={
                'verbose_name_plural': 'Account Categories',
                'ordering': ['section', 'code_prefix'],
            },
        ),
        migrations.CreateModel(
            name='AccountTransactionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField()),
                ('this_account_side', models.CharField(choices=[('CR', 'CREDIT SIDE'), ('DR', 'DEBIT SIDE')], max_length=2)),
                ('validation_rules', models.JSONField(default=dict, help_text="\n        {\n            'amount': {'min': 0, 'max': 1000000, 'required': True},\n            'requires_approval_above': 50000,\n            'allowed_days': ['monday', 'tuesday', ...],\n            'custom_validations': [...]\n        }\n        ")),
                ('additional_fields', models.JSONField(default=list, help_text="\n        Additional fields beyond standard transaction fields:\n        [\n            {\n                'id': 'loan_purpose',\n                'label': 'Loan Purpose',\n                'type': 'select',\n                'options': ['business', 'education', 'medical'],\n                'required': True,\n                'visible_when': {'field': 'amount', 'operator': '>', 'value': 10000}\n            }\n        ]\n        ")),
                ('post_transaction_actions', models.JSONField(default=list, help_text="\n        Actions to trigger after transaction:\n        [\n            {'type': 'send_sms', 'template': 'transaction_receipt'},\n            {'type': 'update_client_status', 'condition': '...'},\n            {'type': 'create_schedule', 'frequency': 'monthly'}\n        ]\n        ")),
                ('approval_config', models.JSONField(default=dict, help_text='\n        {\n            \'required\': True,\n            \'rules\': [\n                {\'condition\': \'amount > 50000\', \'approvers\': [\'manager\']},\n                {\'condition\': \'client.risk_level == "high"\', \'approvers\': [\'manager\', \'ceo\']}\n            ]\n        }\n        ')),
                ('availability_conditions', models.JSONField(default=dict, help_text="\n        When this pattern is available:\n        {\n            'account_status': ['active'],\n            'client_status': ['active', 'verified'],\n            'minimum_balance': 1000,\n            'custom_conditions': [...]\n        }\n        ")),
                ('display_config', models.JSONField(default=dict, help_text="\n        {\n            'icon': 'bank-transfer',\n            'color': '#4CAF50',\n            'category': 'payments',\n            'featured': True,\n            'order': 1\n        }\n        ")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceSheetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='PatternContraAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_selection_criteria', models.JSONField(default=dict, help_text="\n        Criteria for selecting contra accounts dynamically:\n        {\n            'account_type': 'ASSET',\n            'code_prefix': '101',\n            'account_level': 'CHILD',\n            'parent_code': '150',\n            'status': 'active',\n            'custom_filters': {'metadata.branch_type': 'main'}\n        }\n        ")),
                ('availability_condition', models.JSONField(default=dict, help_text="\n        {\n            'field': 'client.account_type',\n            'operator': 'in',\n            'values': ['premium', 'vip']\n        }\n        ")),
                ('default_selection_rule', models.JSONField(default=dict, help_text="\n        {\n            'type': 'last_used',  // or 'most_frequent', 'balance_based', etc.\n            'fallback': 'account_id_123'\n        }\n        ")),
                ('form_label', models.CharField(blank=True, max_length=100)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.IntegerField(default=0)),
                ('specific_validation', models.JSONField(default=dict, help_text='Additional validation when this contra account is selected')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('period_type', models.CharField(choices=[('M', 'Month'), ('Y', 'Year')], max_length=1)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, help_text='1–12 for monthly periods; blank for years.', null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('can_reopen', models.BooleanField(default=True, help_text='Month end can be reopened if true; years cannot.')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
    ]
