# Generated by Django - Standard Chart of Accounts Setup
# This migration creates essential accounts for all tenants automatically

from django.db import migrations
from decimal import Decimal


def setup_standard_accounts(apps, schema_editor):
    """
    DEPRECATED: Use management command instead.
    Run: python manage.py setup_chart_of_accounts
    
    This migration is kept for backwards compatibility with existing
    databases but now delegates to the utility function.
    
    For new deployments, prefer:
    - python manage.py migrate  (runs schema changes)
    - python manage.py setup_chart_of_accounts  (sets up data)
    """
    from accounts.utils.setup_accounts import create_standard_accounts
    
    # Get all tenants
    Tenant = apps.get_model('users', 'Tenant')
    tenants = Tenant.objects.all()
    
    if not tenants.exists():
        print(" No tenants found. Skipping account setup.")
        print("   Run 'python manage.py setup_chart_of_accounts' after creating tenants.")
        return
    
    total_created = 0
    total_skipped = 0
    
    print(f"\n Setting up accounts for {tenants.count()} tenant(s)...")
    
    for tenant in tenants:
        try:
            created, skipped = create_standard_accounts(tenant, force=False)
            total_created += created
            total_skipped += skipped
            
            if created > 0:
                print(f"    {tenant.name}: Created {created} accounts")
        except Exception as e:
            print(f"    {tenant.name}: Error - {str(e)}")
    
    print(f"\n SUMMARY:")
    print(f"   Tenants processed: {tenants.count()}")
    print(f"   Total accounts created: {total_created}")
    print(f"   Total accounts skipped: {total_skipped}")
    print(f"\n Standard Chart of Accounts setup complete!")


def reverse_setup(apps, schema_editor):
    """
    Reverse migration - remove system-created accounts.
    WARNING: This will only remove accounts with is_system_account=True
    and balance=0. Accounts with transactions are preserved.
    """
    Account = apps.get_model('accounts', 'Account')
    
    # Only delete system accounts with zero balance (no transactions)
    deleted_count = Account.objects.filter(
        is_system_account=True,
        balance=Decimal('0.00')
    ).delete()[0]
    
    print(f"  Removed {deleted_count} unused system accounts.")
    print(f"   Accounts with transactions were preserved.")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('users', '0001_initial'),
        ('branches', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(setup_standard_accounts, reverse_setup),
    ]
