# Generated by Django 5.2.4 on 2026-01-22 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_conflicting_migrations'),
    ]

    operations = [
        # Remove old unique constraint on (owner, branch, code_prefix)
        migrations.AlterUniqueTogether(
            name='accountcategory',
            unique_together=set(),
        ),
        # Add new unique constraint on (owner, branch, section, name)
        migrations.AlterUniqueTogether(
            name='accountcategory',
            unique_together={('owner', 'branch', 'section', 'name')},
        ),
    ]
