# Generated by Django 5.2.4 on 2026-02-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_cashier_bank',
            field=models.BooleanField(default=False, help_text='Indicates if this is a cashier bank account (intermediate account for approvals). Regular cashiers can only transfer to cashier banks, not main banks.'),
        ),
    ]
