# Generated by Django 5.2.4 on 2026-03-17 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_fix_account_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Account code must be exactly 4 digits (1000–5999). Range: 1000–1999 Assets, 2000–2999 Liabilities, 3000–3999 Equity, 4000–4999 Revenue, 5000–5999 Expenses.')]),
        ),
    ]
