# Generated by Django 5.2.4 on 2026-06-25 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_subledger_account_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{4}(-\\d{5})?$', 'Account code must be either a 4-digit GL code (e.g. 1150) or a sub-ledger code in the format PPPP-NNNNN (e.g. 1150-00001). GL ranges: 1000–1999 Assets, 2000–2999 Liabilities, 3000–3999 Equity, 4000–4999 Revenue, 5000–5999 Expenses.')]),
        ),
    ]
