# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.SlugField(help_text="Unique code (e.g., 'accounts', 'clients')")),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(help_text='Icon name (lucide-react icon names)', max_length=50)),
                ('color', models.CharField(default='#1a73e8', help_text='Hex color code', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('required_permission', models.CharField(blank=True, help_text='Permission code required to view this module', max_length=100)),
            ],
            options={
                'db_table': 'modules',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModulePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.SlugField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('page_type', models.CharField(choices=[('dashboard', 'Dashboard with Widgets'), ('form', 'Single Form Page'), ('list', 'Data List/Table'), ('detail', 'Detail View with Actions'), ('report', 'Report View'), ('iframe', 'Embedded iFrame'), ('custom', 'Custom Component')], max_length=50)),
                ('page_config', models.JSONField(default=dict, help_text="\n        Configuration varies by page_type:\n        - dashboard: {widgets: [...]}\n        - form: {form_schema_id: int, submitEndpoint: '/api/form-submissions/', successUrl: '/path'}\n        - report: {report_id: int, report_code: 'code', default_parameters: {...}, show_export: bool}\n        - list: {entity: 'Transaction', columns: [...], filters: [...]}\n        - detail: {entity: 'Account', fields: [...], actions: [...]}\n        ")),
                ('url_path', models.CharField(editable=False, max_length=255, unique=True)),
                ('show_in_menu', models.BooleanField(default=True, help_text='Show in navigation menu')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('required_permission', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'module_pages',
                'ordering': ['module', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('widget_type', models.CharField(choices=[('kpi', 'KPI Card'), ('chart', 'Chart Widget'), ('table', 'Data Table'), ('quick_actions', 'Quick Action Buttons'), ('form_links', 'Form Links'), ('recent_items', 'Recent Items'), ('account_summary', 'Account Summary'), ('custom', 'Custom Widget')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('widget_config', models.JSONField(default=dict, help_text='Widget-specific configuration')),
                ('layout_x', models.IntegerField(default=0)),
                ('layout_y', models.IntegerField(default=0)),
                ('layout_w', models.IntegerField(default=4)),
                ('layout_h', models.IntegerField(default=4)),
                ('layout_min_w', models.IntegerField(default=2)),
                ('layout_min_h', models.IntegerField(default=2)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'page_widgets',
                'ordering': ['page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.SlugField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(default='#1a73e8', max_length=7)),
                ('context', models.CharField(choices=[('global', 'Appears Everywhere'), ('module', 'Appears in Module'), ('page', 'Appears on Specific Page'), ('account', 'Appears on Account Detail'), ('client', 'Appears on Client Detail'), ('dashboard', 'Appears on Dashboard')], max_length=50)),
                ('action_type', models.CharField(choices=[('form', 'Open Form'), ('page', 'Navigate to Page'), ('modal', 'Open Modal'), ('external', 'External Link')], max_length=50)),
                ('action_config', models.JSONField(default=dict, help_text="\n        Configuration varies by action_type:\n        - form: {pattern_id: 'xxx', prefill: {...}}\n        - page: {page_id: 'xxx', params: {...}}\n        - modal: {component: 'xxx', props: {...}}\n        - external: {url: 'https://...', target: '_blank'}\n        ")),
                ('display_condition', models.JSONField(default=dict, help_text="\n        Conditions for showing this action:\n        {\n            'account_type': 'SAVINGS',\n            'minimum_balance': 1000,\n            'user_role': 'manager'\n        }\n        ")),
                ('required_permission', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'quick_actions',
                'ordering': ['context', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FormLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7)),
                ('placement', models.CharField(choices=[('menu', 'Main Menu'), ('dashboard', 'Dashboard Widget'), ('account_detail', 'Account Detail Page'), ('client_detail', 'Client Detail Page'), ('report', 'Report Page'), ('list_action', 'List Row Action')], max_length=50)),
                ('context_filter', models.JSONField(default=dict, help_text="\n        When to show this link:\n        {\n            'account_type': 'SAVINGS',\n            'account_status': 'active'\n        }\n        ")),
                ('prefill_mapping', models.JSONField(default=dict, help_text="\n        Map context to form fields:\n        {\n            'client_id': 'context.client.id',\n            'account_id': 'context.account.id',\n            'amount': 'context.suggested_amount'\n        }\n        ")),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
            ],
            options={
                'db_table': 'form_links',
                'ordering': ['placement', 'order'],
            },
        ),
    ]
