# Generated by Django 5.2.4 on 2026-02-18 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_latitude_branch_longitude'),
        ('pages', '0002_initial'),
        ('users', '0002_setup_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.SlugField(help_text="Unique action code (e.g., 'view', 'create', 'edit', 'delete', 'approve')", max_length=100)),
                ('name', models.CharField(help_text="Human-readable action name (e.g., 'View Details', 'Create New')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of what this action does')),
                ('action_type', models.CharField(choices=[('view', 'View/Read'), ('create', 'Create'), ('edit', 'Edit/Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('submit', 'Submit'), ('process', 'Process'), ('export', 'Export'), ('import', 'Import'), ('custom', 'Custom Action')], default='custom', max_length=50)),
                ('permission_codename', models.CharField(blank=True, help_text="Django permission codename (e.g., 'procurement.add_purchaserequisition')", max_length=200)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, default='#3b82f6', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('show_in_list', models.BooleanField(default=True, help_text='Show this action in list views')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(help_text='Module this action belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='pages.module')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(blank=True, help_text='Specific page this action belongs to (optional, can be module-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='pages.modulepage')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'db_table': 'page_actions',
                'ordering': ['module', 'page', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleActionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission_level', models.CharField(choices=[('none', 'No Access'), ('read', 'Read Only'), ('write', 'Read & Write'), ('full', 'Full Control')], default='none', max_length=20)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='\n        Optional conditions for this permission:\n        {\n            "own_records_only": true,\n            "branch_only": true,\n            "max_amount": 10000\n        }\n        ')),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='pages.pageaction')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_permissions', to='users.role')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'db_table': 'role_action_permissions',
            },
        ),
        migrations.AddIndex(
            model_name='pageaction',
            index=models.Index(fields=['module', 'is_active'], name='page_action_module__a1d44a_idx'),
        ),
        migrations.AddIndex(
            model_name='pageaction',
            index=models.Index(fields=['page', 'is_active'], name='page_action_page_id_8e04ad_idx'),
        ),
        migrations.AddIndex(
            model_name='pageaction',
            index=models.Index(fields=['code'], name='page_action_code_25e326_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pageaction',
            unique_together={('module', 'page', 'code')},
        ),
        migrations.AddIndex(
            model_name='roleactionpermission',
            index=models.Index(fields=['role', 'is_active'], name='role_action_role_id_d03daa_idx'),
        ),
        migrations.AddIndex(
            model_name='roleactionpermission',
            index=models.Index(fields=['action', 'is_active'], name='role_action_action__32ee8f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roleactionpermission',
            unique_together={('role', 'action')},
        ),
    ]
