# Generated by Django 5.2.4 on 2026-06-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_add_page_actions_and_role_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulepage',
            name='is_threadable',
            field=models.BooleanField(default=False, help_text='Allow contextual discussion threads on this page'),
        ),
    ]
