# Generated by Django 5.2.4 on 2026-07-31 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_alter_account_code'),
        ('branches', '0005_insurance_verifier_disbursement'),
        ('transactions', '0006_fix_empty_sequence_names'),
        ('users', '0011_alter_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterBranchClearingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('direction', models.CharField(choices=[('due_from', 'Due From (Asset)'), ('due_to', 'Due To (Liability)')], max_length=10)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='interbranch_clearing_registration', to='accounts.account')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interbranch_clearing_accounts', to='branches.branch')),
                ('counterparty_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('branch', 'counterparty_branch', 'direction'), name='unique_interbranch_clearing_account')],
            },
        ),
        migrations.CreateModel(
            name='InterBranchTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('transfer_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='posted', max_length=10)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_transaction', models.ForeignKey(help_text='JV posted in to_branch: Dr to_account / Cr Due-to-clearing', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.transaction')),
                ('from_account', models.ForeignKey(help_text='Real operational account debited in the source branch (e.g. Cash/Bank)', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.account')),
                ('from_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_interbranch_transfers', to='branches.branch')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_transaction', models.ForeignKey(help_text='JV posted in from_branch: Dr Due-from-clearing / Cr from_account', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='transactions.transaction')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
                ('to_account', models.ForeignKey(help_text='Real operational account credited in the destination branch (e.g. Cash/Bank)', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.account')),
                ('to_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_interbranch_transfers', to='branches.branch')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['from_branch', 'date'], name='interbranch_from_br_71576e_idx'), models.Index(fields=['to_branch', 'date'], name='interbranch_to_bran_216030_idx')],
            },
        ),
    ]
