# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.SlugField(help_text='Unique code for this widget type')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(default=dict, help_text='JSON Schema for widget configuration')),
                ('default_config', models.JSONField(default=dict, help_text='Default configuration values')),
                ('refresh_interval', models.IntegerField(default=0, help_text='Default auto-refresh interval in seconds (0 for no auto-refresh)')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant this widget definition belongs to', on_delete=django.db.models.deletion.CASCADE, to='users.tenant')),
            ],
            options={
                'verbose_name': 'Widget Definition',
                'verbose_name_plural': 'Widget Definitions',
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='WidgetInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('position', models.JSONField(default=dict, help_text='Widget position and size in the grid')),
                ('configuration', models.JSONField(default=dict, help_text='Widget-specific configuration')),
                ('refresh_interval', models.IntegerField(blank=True, help_text='Override default refresh interval (null uses definition default)', null=True)),
                ('last_refresh', models.DateTimeField(blank=True, help_text='When the widget data was last refreshed', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(help_text='Widget type definition', on_delete=django.db.models.deletion.PROTECT, to='widgets.widgetdefinition')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(help_text='Page this widget is placed on', on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='pages.modulepage')),
                ('tenant', models.ForeignKey(help_text='Tenant this widget instance belongs to', on_delete=django.db.models.deletion.CASCADE, to='users.tenant')),
            ],
            options={
                'verbose_name': 'Widget Instance',
                'verbose_name_plural': 'Widget Instances',
                'ordering': ['page', 'title'],
                'unique_together': {('page', 'title')},
            },
        ),
    ]
