# Generated by Django 5.2.4 on 2026-01-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('receivable_type', models.CharField(choices=[('invoice', 'Invoice'), ('entitlement', 'Fee Entitlement'), ('loan', 'Loan'), ('other', 'Other')], db_index=True, max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('reference_number', models.CharField(db_index=True, max_length=50)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('due_date', models.DateField(db_index=True)),
                ('aging_bucket', models.CharField(choices=[('current', 'Current (Not Due)'), ('1-30', '1-30 Days Overdue'), ('31-60', '31-60 Days Overdue'), ('61-90', '61-90 Days Overdue'), ('90+', '90+ Days Overdue')], db_index=True, default='current', max_length=20)),
                ('days_overdue', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overdue', 'Overdue'), ('written_off', 'Written Off')], db_index=True, default='pending', max_length=20)),
                ('overdue_interest_rate', models.DecimalField(decimal_places=2, default=0, help_text='Annual interest rate % for overdue amounts (0 = no interest)', max_digits=5)),
                ('accrued_interest', models.DecimalField(decimal_places=2, default=0, help_text='Interest accumulated on overdue balance', max_digits=18)),
                ('last_interest_calculation', models.DateField(blank=True, null=True)),
                ('last_reminder_sent', models.DateField(blank=True, null=True)),
                ('reminder_count', models.IntegerField(default=0)),
                ('collection_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('statement_number', models.CharField(max_length=50, unique=True)),
                ('statement_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('sent_via', models.CharField(blank=True, choices=[('email', 'Email'), ('print', 'Print'), ('download', 'Download'), ('portal', 'Customer Portal')], max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to', models.EmailField(blank=True, max_length=254)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='statements/%Y/%m/')),
            ],
            options={
                'ordering': ['-statement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivableActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('activity_type', models.CharField(choices=[('payment', 'Payment Received'), ('adjustment', 'Balance Adjustment'), ('interest_applied', 'Interest Applied'), ('reminder_sent', 'Reminder Sent'), ('status_change', 'Status Changed'), ('assigned', 'Assigned to Collector'), ('note_added', 'Note Added'), ('written_off', 'Written Off'), ('reversed', 'Payment Reversed')], max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount involved (if applicable)', max_digits=18, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
