# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_initial'),
        ('clients', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('receivables', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerreceivable',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Collection agent assigned to this receivable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_receivables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerreceivable',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='customerreceivable',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='clients.client'),
        ),
        migrations.AddField(
            model_name='customerreceivable',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='customerreceivable',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerreceivable',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerreceivable',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='customerstatement',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='customerstatement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statements', to='clients.client'),
        ),
        migrations.AddField(
            model_name='customerstatement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerstatement',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerstatement',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerstatement',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='receivableactivitylog',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='receivableactivitylog',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivableactivitylog',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivableactivitylog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receivableactivitylog',
            name='receivable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='receivables.customerreceivable'),
        ),
        migrations.AddField(
            model_name='receivableactivitylog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddIndex(
            model_name='customerreceivable',
            index=models.Index(fields=['client', 'status'], name='receivables_client__e9cbd9_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreceivable',
            index=models.Index(fields=['aging_bucket', 'status'], name='receivables_aging_b_bf6bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreceivable',
            index=models.Index(fields=['due_date', 'status'], name='receivables_due_dat_37c9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreceivable',
            index=models.Index(fields=['receivable_type', 'status'], name='receivables_receiva_20b166_idx'),
        ),
        migrations.AddIndex(
            model_name='customerreceivable',
            index=models.Index(fields=['owner', 'branch', 'status'], name='receivables_owner_i_ec2c06_idx'),
        ),
        migrations.AddIndex(
            model_name='customerstatement',
            index=models.Index(fields=['client', 'statement_date'], name='receivables_client__3d808e_idx'),
        ),
        migrations.AddIndex(
            model_name='customerstatement',
            index=models.Index(fields=['statement_number'], name='receivables_stateme_f8b6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='receivableactivitylog',
            index=models.Index(fields=['receivable', 'activity_type'], name='receivables_receiva_2aec65_idx'),
        ),
        migrations.AddIndex(
            model_name='receivableactivitylog',
            index=models.Index(fields=['created_at'], name='receivables_created_7cccb1_idx'),
        ),
    ]
