# Generated by Django 5.2.4 on 2026-04-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivableactivitylog',
            name='activity_type',
            field=models.CharField(choices=[('payment', 'Payment Received'), ('adjustment', 'Balance Adjustment'), ('interest_applied', 'Interest Applied'), ('reminder_sent', 'Reminder Sent'), ('status_change', 'Status Changed'), ('assigned', 'Assigned to Collector'), ('note_added', 'Note Added'), ('written_off', 'Written Off'), ('write_off', 'Write Off'), ('reversed', 'Payment Reversed'), ('credit_note_applied', 'Credit Note Applied'), ('refund', 'Refund Issued')], max_length=50),
        ),
    ]
