# Generated by Django 5.2.4 on 2026-06-25 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_rename_clients_clientgroup_officer_idx_clients_cli_assigne_a98ebc_idx'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='permissionelevationlog',
            new_name='perm_elevat_user_id_250291_idx',
            old_name='perm_elev_log_user_logged',
        ),
        migrations.RenameIndex(
            model_name='permissionelevationlog',
            new_name='perm_elevat_overrid_2b8622_idx',
            old_name='perm_elev_log_override_logged',
        ),
        migrations.RenameIndex(
            model_name='permissionelevationlog',
            new_name='perm_elevat_record__b39869_idx',
            old_name='perm_elev_log_record',
        ),
        migrations.RenameIndex(
            model_name='rolepermissionpolicy',
            new_name='perm_role_p_role_id_1f0d37_idx',
            old_name='perm_role_policy_role_module',
        ),
        migrations.RenameIndex(
            model_name='rolepermissionpolicy',
            new_name='perm_role_p_role_id_886d90_idx',
            old_name='perm_role_policy_role_page',
        ),
        migrations.RenameIndex(
            model_name='rolepermissionpolicy',
            new_name='perm_role_p_role_id_4f26e1_idx',
            old_name='perm_role_policy_role_action',
        ),
        migrations.RenameIndex(
            model_name='userpermissionoverride',
            new_name='perm_user_o_user_id_2d49a9_idx',
            old_name='perm_user_override_user_active',
        ),
        migrations.RenameIndex(
            model_name='userpermissionoverride',
            new_name='perm_user_o_is_elev_d028a1_idx',
            old_name='perm_user_override_elevated',
        ),
        migrations.RenameIndex(
            model_name='userpermissionoverride',
            new_name='perm_user_o_expires_1620a8_idx',
            old_name='perm_user_override_expires_at',
        ),
        migrations.AlterField(
            model_name='permissionelevationlog',
            name='record_type',
            field=models.CharField(help_text='Django model name of the affected record (e.g. "LoanAccount").', max_length=100),
        ),
        migrations.AlterField(
            model_name='userpermissionoverride',
            name='approval_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override approval monetary limit for this user. NULL = use role limit.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='userpermissionoverride',
            name='grant_reason',
            field=models.TextField(blank=True, help_text='Reason for granting this override (shown in exception report).'),
        ),
        migrations.AlterField(
            model_name='userpermissionoverride',
            name='scope_ajo_group',
            field=models.ForeignKey(blank=True, help_text='The Ajo group this override scopes to (only used when scope=ajo_group).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_overrides', to='clients.clientgroup'),
        ),
    ]
