# Generated by Django 5.2.4 on 2026-07-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_rename_perm_elev_log_user_logged_perm_elevat_user_id_250291_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissionoverride',
            name='last_expiry_warning_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
