# Generated by Django 5.2.4 on 2026-08-18 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_insurance_verifier_disbursement'),
        ('permissions', '0003_add_last_expiry_warning_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermissionoverride',
            name='target_branch',
            field=models.ForeignKey(blank=True, help_text="Grants access to this ADDITIONAL branch (on top of the user's home branch) for the duration of this override. Must be used with no module/page/action set — a branch grant applies tenant-page-wide, not to one specific page.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_branch_grants', to='branches.branch'),
        ),
    ]
