# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_number', models.CharField(editable=False, help_text='Auto-generated reference number', max_length=50, unique=True)),
                ('workflow_reference', models.CharField(blank=True, help_text='Optional reference for external workflows', max_length=50, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('is_reversed', models.BooleanField(default=False, help_text='Whether this transaction has been reversed')),
                ('reversed_at', models.DateTimeField(blank=True, help_text='When this transaction was reversed', null=True)),
                ('reversal_reason', models.TextField(blank=True, help_text='Reason for reversal')),
                ('is_reversal', models.BooleanField(default=False, help_text='Whether this transaction is a reversal of another')),
            ],
            options={
                'ordering': ['-date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to debit/credit', max_digits=18)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount that has been reversed', max_digits=18)),
                ('posted', models.BooleanField(default=False, help_text='Whether this entry has been posted to the account')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Transaction Entries',
            },
        ),
        migrations.CreateModel(
            name='TransactionSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Short alpha code, e.g. 'CA' for Current Assets, 'LN' for Loans", max_length=5, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('sequence_name', models.CharField(editable=False, help_text='Internally used Postgres sequence name', max_length=50, unique=True)),
            ],
        ),
    ]
