# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('branches', '0002_initial'),
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reversal_transaction',
            field=models.ForeignKey(blank=True, help_text='The reversing transaction (if this is reversed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_transaction', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reversed_by',
            field=models.ForeignKey(blank=True, help_text='User who reversed this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reverses_transaction',
            field=models.ForeignKey(blank=True, help_text='The original transaction (if this is a reversal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_by_transaction', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='transactionentry',
            name='account',
            field=models.ForeignKey(help_text='Account to debit/credit (can be parent or child)', on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transactionentry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='series',
            field=models.ForeignKey(help_text='Select the series (e.g. CA, LN) to drive the reference number.', on_delete=django.db.models.deletion.PROTECT, to='transactions.transactionseries'),
        ),
        migrations.AddIndex(
            model_name='transactionentry',
            index=models.Index(fields=['account', 'posted'], name='transaction_account_b405b4_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionentry',
            index=models.Index(fields=['transaction', 'side'], name='transaction_transac_c265c5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'reference_number'], name='transaction_owner_i_c0ee64_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'workflow_reference'], name='transaction_owner_i_0676e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('owner', 'reference_number'), ('owner', 'workflow_reference')},
        ),
    ]
