# Generated by Django 5.2.4 on 2026-01-26 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_update_accountcategory_unique_constraint'),
        ('branches', '0002_initial'),
        ('transactions', '0002_initial'),
        ('users', '0002_setup_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'owner', 'branch', 'is_deleted'], name='idx_trans_date_owner_br'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['owner', 'date'], name='idx_trans_owner_date'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['branch', 'date'], name='idx_trans_branch_date'),
        ),
        migrations.AddIndex(
            model_name='transactionentry',
            index=models.Index(fields=['account', 'posted', 'side'], name='idx_entry_acct_posted_side'),
        ),
        migrations.AddIndex(
            model_name='transactionentry',
            index=models.Index(fields=['posted'], name='idx_entry_posted'),
        ),
    ]
