# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('assets', '0003_initial'),
        ('automations', '0002_initial'),
        ('branches', '0002_initial'),
        ('expenses', '0001_initial'),
        ('hr', '0001_initial'),
        ('liabilities', '0001_initial'),
        ('procurement', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='expense',
            name='workflow_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='automations.workflowrun'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='expense_account',
            field=models.ForeignKey(help_text='Expense account (must be EXPENSE type)', on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories_main', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='prepaid_account',
            field=models.ForeignKey(blank=True, help_text='Asset account for prepaid expenses (must be ASSET type)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories_prepaid', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product configuration for expense limits and validation', limit_choices_to={'product_type': 'EXPENSE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='products.product'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory'),
        ),
        migrations.AddField(
            model_name='prepaidexpense',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='prepaidexpense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepaid_expenses', to='expenses.expensecategory'),
        ),
        migrations.AddField(
            model_name='prepaidexpense',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prepaidexpense',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prepaidexpense',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='prepaidvoucher',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='prepaidvoucher',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prepaidvoucher',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prepaidvoucher',
            name='prepaid_expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='expenses.prepaidexpense'),
        ),
        migrations.AddField(
            model_name='prepaidvoucher',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='resource',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='default_supplier',
            field=models.ForeignKey(blank=True, help_text='Default supplier for this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='resource',
            name='expense_category',
            field=models.ForeignKey(help_text='Expense category for this resource', on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='expenses.expensecategory'),
        ),
        migrations.AddField(
            model_name='resource',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='resourceconsumption',
            name='accounts_payable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_consumptions', to='liabilities.accountspayable'),
        ),
        migrations.AddField(
            model_name='resourceconsumption',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_consumptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceconsumption',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='If beneficiary is an asset', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_consumptions', to='assets.fixedasset'),
        ),
        migrations.AddField(
            model_name='resourceconsumption',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='resourceconsumption',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceconsumption',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='If beneficiary is a staff member (from HR)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_consumptions', to='hr.staff'),
        ),
        migrations.AddField(
            model_name='resourceconsumption',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceconsumption',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_consumptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceconsumption',
            name='prepaid_voucher',
            field=models.ForeignKey(blank=True, help_text='Required for prepaid flow', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='expenses.prepaidvoucher'),
        ),
        migrations.AddField(
            model_name='resourceconsumption',
            name='resource',
            field=models.ForeignKey(help_text='The resource being consumed', on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='expenses.resource'),
        ),
        migrations.AddField(
            model_name='resourceconsumption',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Required for postpaid flow (can be overridden from Resource default)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resource_consumptions', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='resourceconsumption',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='resourceconsumption',
            name='workflow_run',
            field=models.ForeignKey(blank=True, help_text='Linked workflow run for approval automation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_consumptions', to='automations.workflowrun'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('branch', 'code')},
        ),
        migrations.AddIndex(
            model_name='prepaidvoucher',
            index=models.Index(fields=['voucher_number'], name='expenses_pr_voucher_919e95_idx'),
        ),
        migrations.AddIndex(
            model_name='prepaidvoucher',
            index=models.Index(fields=['status'], name='expenses_pr_status_6cec84_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_code'], name='expenses_re_resourc_78d7a9_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type', 'is_active'], name='expenses_re_resourc_062f65_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_service'], name='expenses_re_is_serv_76f98b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('branch', 'resource_code')},
        ),
        migrations.AddIndex(
            model_name='resourceconsumption',
            index=models.Index(fields=['consumption_number'], name='expenses_re_consump_de2aed_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceconsumption',
            index=models.Index(fields=['payment_flow', 'status'], name='expenses_re_payment_3600c7_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceconsumption',
            index=models.Index(fields=['resource', 'consumption_date'], name='expenses_re_resourc_47d5af_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceconsumption',
            index=models.Index(fields=['asset', 'consumption_date'], name='expenses_re_asset_i_f5f0ca_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceconsumption',
            index=models.Index(fields=['is_irregular', 'status'], name='expenses_re_is_irre_46929b_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceconsumption',
            index=models.Index(fields=['beneficiary_type', 'consumption_date'], name='expenses_re_benefic_de94ad_idx'),
        ),
    ]
