# Generated by Django 5.2.4 on 2026-01-24 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
        ('procurement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidexpense',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier for this prepaid expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepaid_expenses', to='procurement.supplier'),
        ),
        migrations.AlterField(
            model_name='prepaidexpense',
            name='supplier_name',
            field=models.CharField(blank=True, help_text='Supplier name (for reference or if supplier not in system)', max_length=200),
        ),
    ]
