# Generated by Django 5.2.4 on 2026-03-17 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_bankaccount_gl_account_nullable'),
        ('expenses', '0003_prepaidexpense_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Bank account used for this payment. Required when payment_method is bank_transfer, cheque, or card. The GL account linked to this bank account will be credited when the expense is posted.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='banks.bankaccount'),
        ),
    ]
