# Generated by Django 5.2.4 on 2026-03-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_bank_account_fk_on_expense_and_replenishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidvoucher',
            name='odometer_reading',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Odometer reading at time of voucher issue (for vehicle assets)', max_digits=12, null=True),
        ),
    ]
