# Generated by Django 5.2.4 on 2026-04-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_add_journal_entry_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='budget_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Budget allocation for this category (per fiscal year)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='budget_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='yearly', help_text='Budget period for tracking', max_length=10),
        ),
    ]
