// src/services/invoiceService.ts
import { api } from './api';

// Invoice Line Item - supports service, inventory, and custom items
export interface InvoiceItem {
  id?: number;
  item_type: 'service' | 'inventory' | 'custom';
  /** ServiceItem FK — required for item_type='service' */
  service_item?: number;
  service_item_details?: {
    id: number;
    name: string;
    code: string;
    creates_entitlement: boolean;
    /** e.g. 'tuition', 'boarding', 'transport', 'inventory' */
    service_type?: string;
    allows_material_requests?: boolean;
    material_request_config?: {
      allowed_categories?: string[];
      allowed_item_types?: string[];
      [key: string]: unknown;
    } | null;
  };
  inventory_item?: number;
  inventory_item_details?: {
    id: number;
    name: string;
    sku: string;
    category?: number;
    category_name?: string;
    /** Short code for the category, e.g. 'CAT-001' */
    category_code?: string;
    /** Broad type label for the category, e.g. 'Book', 'Uniform' */
    category_item_type?: string;
  };
  // Flat category / type fields (populated by InvoiceItemSerializer when item_type='inventory')
  inventory_item_category?: number | null;
  inventory_item_category_name?: string | null;
  inventory_item_category_code?: string | null;
  inventory_item_category_item_type?: string | null;
  // Flat MR fields (populated when item_type='service')
  service_item_service_type?: string | null;
  service_item_allows_material_requests?: boolean | null;
  service_item_material_request_config?: {
    allowed_categories?: string[];
    allowed_item_types?: string[];
    [key: string]: unknown;
  } | null;
  description: string;
  quantity: string;
  unit_price: string;
  line_total: string;
  // Per-item payment tracking (read-only, set by backend)
  amount_paid?: string;
  line_balance?: string;
  payment_percentage?: string;
  // Entitlement tracking
  creates_entitlement?: boolean;
  entitlement?: number | null;
  metadata?: any;
}

/** A per-line-item payment allocation sent with a payment request */
export interface LineItemAllocation {
  invoice_item_id: number;
  amount: string;
  notes?: string;
}

// Unified Invoice - supports multiple line items
export interface Invoice {
  id: number;
  client: number;
  client_name: string;
  invoice_number: string;
  invoice_date: string;
  due_date: string;
  description?: string;
  notes?: string;

  // New unified amounts
  subtotal: string;
  discount_amount: string;
  tax_amount: string;
  total_amount: string;
  amount_paid: string;
  balance: string;

  // Optional primary fee structure (for bulk generation)
  fee_structure?: number;
  fee_structure_name?: string;

  // Line items
  items: InvoiceItem[];

  status: 'draft' | 'sent' | 'partial' | 'paid' | 'overdue' | 'cancelled';
  metadata?: any;

  // Accounting
  is_posted: boolean;
  posted_at?: string;
  posted_by?: number;

  inventory_allocation?: number;
  is_overdue: boolean;
  created_at: string;
  updated_at: string;

  // Legacy fields (deprecated)
  amount?: string; // Use total_amount instead
}

// Create Invoice Data - with line items
export interface CreateInvoiceData {
  client: number;
  invoice_date: string;
  due_date: string;
  description?: string;
  notes?: string;
  discount_amount?: string;
  fee_structure?: number | null;
  status?: 'draft' | 'sent';
  metadata?: any;
  items: InvoiceItem[];
  // Note: invoice_number is auto-generated by backend
}

// Update Invoice Data
export interface UpdateInvoiceData {
  client?: number;
  invoice_date?: string;
  due_date?: string;
  description?: string;
  notes?: string;
  discount_amount?: string;
  fee_structure?: number | null;
  status?: 'draft' | 'sent' | 'partial' | 'paid' | 'overdue' | 'cancelled';
  metadata?: any;
  items?: InvoiceItem[];
}

export interface InvoiceFilters {
  client_id?: number;
  status?: 'draft' | 'sent' | 'partial' | 'paid' | 'overdue' | 'cancelled';
  invoice_date?: string;
  due_date?: string;
  search?: string;
  ordering?: string;
  page?: number;
}

export interface CreditNote {
  id: number;
  credit_note_number: string;
  /** Backend returns a nested object: { id, invoice_number, invoice_date, total_amount, status } */
  original_invoice: {
    id: number;
    invoice_number: string;
    invoice_date: string;
    total_amount: string;
    status: string;
  };
  client: {
    id: number;
    /** Backend ClientListSerializer exposes full_name, not name */
    full_name: string;
    first_name: string;
    last_name: string;
  };
  issue_date: string;
  reason: string;
  notes?: string;
  subtotal: string;
  discount: string;
  tax_amount: string;
  total_amount: string;
  applied_to_account: boolean;
  applied_date?: string;
  applied_by?: {
    id: number;
    username: string;
  };
  status: 'draft' | 'issued' | 'applied' | 'cancelled';
  reversed: boolean;
  reversed_date?: string;
  reversed_by?: {
    id: number;
    username: string;
  };
  reversal_reason?: string;
  created_by?: {
    id: number;
    username: string;
  };
  branch?: number;
  owner?: number;
  items: CreditNoteItem[];
  remaining_amount: string;
  can_be_applied: boolean;
  can_be_cancelled: boolean;
  created_at: string;
  updated_at: string;
}
export interface CreditNoteItem {
  id: number;
  credit_note: number;
  original_invoice_item?: number;
  item?: number;
  item_name: string;
  item_sku: string;
  description: string;
  quantity_returned: string;
  original_quantity: string;
  unit_price: string;
  discount: string;
  tax_amount: string;
  line_total: string;
  return_reason?:
    | 'defective'
    | 'wrong_item'
    | 'damaged'
    | 'not_as_described'
    | 'customer_request'
    | 'pricing_error'
    | 'other';
  return_notes?: string;
  return_to_stock: boolean;
  stock_returned: boolean;
  original_invoice_item_description: string;
  created_at: string;
  updated_at: string;
}

export interface CreditNoteItemRequest {
  original_invoice_item?: number;
  item?: number;
  description: string;
  quantity_returned: string;
  original_quantity: string;
  unit_price: string;
  discount: string;
  tax_amount: string;
  line_total: string;
  return_reason?:
    | 'defective'
    | 'wrong_item'
    | 'damaged'
    | 'not_as_described'
    | 'customer_request'
    | 'pricing_error'
    | 'other';
  return_notes?: string;
  return_to_stock: boolean;
}
export interface CreateCreditNoteData {
  original_invoice: number;
  client: number;
  issue_date: string;
  reason: string;
  notes?: string;
  subtotal: string;
  discount: string;
  tax_amount: string;
  total_amount: string;
  status?: 'draft' | 'issued' | 'applied' | 'cancelled';
  reversal_reason?: string;
  created_by?: number;
  branch?: number;
  owner?: number;
  items: CreditNoteItemRequest[];
}

// Bulk Invoice Interfaces
export interface BulkInvoiceData {
  fee_structure: number;
  clients: number[];
  invoice_date: string;
  due_date: string;
  description?: string;
  send_immediately: boolean;
  email_template?: string;
}

export interface BulkInvoiceResult {
  success: boolean;
  created_count: number;
  failed_count: number;
  total_amount?: string;
  created_invoices: {
    id: number;
    invoice_number: string;
    client_id: number;
    client_name: string;
    amount: string;
    status?: 'created' | 'sent' | 'failed';
    error?: string;
  }[];
  failed?: any;
  errors?: string[];
  // Legacy support for old interface
  invoices?: {
    id: number;
    invoice_number: string;
    client_name: string;
    amount: string;
    status: 'created' | 'sent' | 'failed';
    error?: string;
  }[];
}

export const invoiceService = {
  // Invoice CRUD
  async getInvoices(filters?: InvoiceFilters) {
    return api.get('/incomes/invoices/', { params: filters });
  },

  async createInvoice(data: CreateInvoiceData): Promise<Invoice> {
    return api.post('/incomes/invoices/', data);
  },

  async getInvoice(id: number): Promise<Invoice> {
    return api.get(`/incomes/invoices/${id}/`);
  },

  async updateInvoice(id: number, data: Partial<CreateInvoiceData>): Promise<Invoice> {
    return api.put(`/incomes/invoices/${id}/`, data);
  },

  async deleteInvoice(id: number) {
    return api.delete(`/incomes/invoices/${id}/`);
  },

  // Post invoice (recognize revenue)
  async postInvoice(id: number) {
    return api.post(`/incomes/invoices/${id}/post/`);
  },

  // Payment recording
  async recordPayment(
    id: number,
    data: {
      amount: string;
      payment_date: string;
      payment_method: string;
      bank_account_id?: number;
      reference?: string;
      notes?: string;
      /** Optional per-line-item allocation. If omitted, backend distributes proportionally. */
      line_item_allocations?: LineItemAllocation[];
    }
  ) {
    return api.post(`/incomes/invoices/${id}/record_payment/`, data);
  },

  // Get payment history for an invoice (includes reversal request status)
  async getPaymentHistory(id: number) {
    return api.get(`/incomes/invoices/${id}/payment_history/`);
  },

  // List all payment reversal requests (for the Approvals page)
  async listPaymentReversalRequests(params?: {
    status?: 'pending' | 'approved' | 'rejected';
    invoice_id?: number;
  }): Promise<{
    results: Array<{
      id: number;
      invoice_id: number;
      invoice_number: string;
      client_name: string | null;
      payment_reference: string;
      amount: string;
      reason: string;
      status: 'pending' | 'approved' | 'rejected';
      requested_by: string | null;
      created_at: string;
      approved_by: string | null;
      approved_at: string | null;
      rejection_reason: string;
      draft_journal_entry_ref: string | null;
    }>;
    count: number;
  }> {
    return api.get('/incomes/payment-reversal-requests/', { params });
  },

  // Step 1: Request a payment reversal (creates draft GL entry, pending approval)
  async requestPaymentReversal(
    id: number,
    data: { payment_reference: string; reason: string }
  ): Promise<{
    success: boolean;
    message: string;
    reversal_request_id: number;
    draft_journal_entry_id: number;
    draft_journal_entry_ref: string;
    amount: string;
  }> {
    return api.post(`/incomes/invoices/${id}/request_payment_reversal/`, data);
  },

  // Step 2a: Approve a pending reversal request (approver only)
  async approvePaymentReversal(
    id: number,
    data: { reversal_request_id: number }
  ): Promise<{ success: boolean; message: string; reversed_amount: string; invoice: Invoice }> {
    return api.post(`/incomes/invoices/${id}/approve_payment_reversal/`, data);
  },

  // Step 2b: Reject a pending reversal request (approver only)
  async rejectPaymentReversal(
    id: number,
    data: { reversal_request_id: number; rejection_reason: string }
  ): Promise<{ success: boolean; message: string; reversal_request_id: number }> {
    return api.post(`/incomes/invoices/${id}/reject_payment_reversal/`, data);
  },

  // Mark invoice as sent
  async markAsSent(id: number, data: any) {
    return api.post(`/incomes/invoices/${id}/mark_sent/`, data);
  },

  // Invoice Actions (Critical Missing Endpoints)
  async sendInvoiceEmail(id: number, data: { email: string; subject?: string; message?: string }) {
    return api.post(`/incomes/invoices/${id}/send-email/`, data);
  },

  async getInvoicePdf(id: number): Promise<Blob> {
    const response = await fetch(`/api/incomes/invoices/${id}/pdf/`, {
      headers: {
        Authorization: `Bearer ${localStorage.getItem('accessToken') || sessionStorage.getItem('accessToken')}`,
      },
    });
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    return response.blob();
  },

  async voidInvoice(id: number, data: { reason?: string }) {
    return api.post(`/incomes/invoices/${id}/void/`, data);
  },

  // Credit Notes (Nested under invoices)
  async getCreditNotes(
    invoiceId: number,
    filters?: {
      applied_to_account?: boolean;
      client?: number;
      issue_date?: string;
      ordering?: string;
      original_invoice?: number;
      page?: number;
      search?: string;
      status?: 'draft' | 'issued' | 'applied' | 'cancelled';
    }
  ) {
    return api.get(`/inventory/invoices/${invoiceId}/credit-notes/`, { params: filters });
  },

  async createCreditNote(invoiceId: number, data: CreateCreditNoteData): Promise<CreditNote> {
    return api.post(`/inventory/invoices/${invoiceId}/credit-notes/`, data);
  },

  async getCreditNote(invoiceId: number, creditNoteId: number): Promise<CreditNote> {
    return api.get(`/inventory/invoices/${invoiceId}/credit-notes/${creditNoteId}/`);
  },

  async updateCreditNote(
    invoiceId: number,
    creditNoteId: number,
    data: Partial<CreateCreditNoteData>
  ): Promise<CreditNote> {
    return api.put(`/inventory/invoices/${invoiceId}/credit-notes/${creditNoteId}/`, data);
  },

  async deleteCreditNote(invoiceId: number, creditNoteId: number) {
    return api.delete(`/inventory/invoices/${invoiceId}/credit-notes/${creditNoteId}/`);
  },

  // Credit Note Actions
  async issueCreditNote(
    invoiceId: number,
    creditNoteId: number,
    data: CreateCreditNoteData
  ): Promise<CreditNote> {
    return api.post(`/inventory/invoices/${invoiceId}/credit-notes/${creditNoteId}/issue/`, data);
  },

  async applyCreditNote(
    invoiceId: number,
    creditNoteId: number,
    data: { notes?: string }
  ): Promise<{ notes?: string }> {
    return api.post(`/inventory/invoices/${invoiceId}/credit-notes/${creditNoteId}/apply/`, data);
  },

  async cancelCreditNote(
    invoiceId: number,
    creditNoteId: number,
    data: { cancellation_reason: string }
  ): Promise<{ cancellation_reason: string }> {
    return api.post(`/inventory/invoices/${invoiceId}/credit-notes/${creditNoteId}/cancel/`, data);
  },

  async reverseCreditNote(
    invoiceId: number,
    creditNoteId: number,
    data: { reversal_reason: string }
  ): Promise<{ reversal_reason: string }> {
    return api.post(`/inventory/invoices/${invoiceId}/credit-notes/${creditNoteId}/reverse/`, data);
  },

  async getCreditNotePdf(invoiceId: number, creditNoteId: number): Promise<Blob> {
    const response = await fetch(
      `/api/inventory/invoices/${invoiceId}/credit-notes/${creditNoteId}/pdf/`,
      {
        headers: {
          Authorization: `Bearer ${localStorage.getItem('accessToken') || sessionStorage.getItem('accessToken')}`,
        },
      }
    );
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    return response.blob();
  },

  // Bulk Invoice Operations
  async createBulkInvoices(data: BulkInvoiceData): Promise<BulkInvoiceResult> {
    return api.post('/incomes/invoices/bulk_create/', data);
  },

  async sendBulkInvoices(
    invoiceIds: number[],
    options?: { email_template?: string }
  ): Promise<{
    success: boolean;
    sent_count: number;
    failed_count: number;
    results: { id: number; status: 'sent' | 'failed'; error?: string }[];
  }> {
    return api.post('/incomes/invoices/bulk_send/', {
      invoice_ids: invoiceIds,
      ...options,
    });
  },

  // Batch Review and Approval Methods
  async getBatchSample(
    batchId: string,
    samplePercent: number = 5
  ): Promise<{
    batch_id: string;
    total_invoices: number;
    sample_size: number;
    sample_invoices: Invoice[];
    discrepancies: {
      invoice_id: number;
      issue_type: string;
      description: string;
      severity: 'high' | 'medium' | 'low';
    }[];
  }> {
    return api.get(`/incomes/invoices/batch-sample/`, {
      params: { batch_id: batchId, sample_pct: samplePercent },
    });
  },

  async downloadBatchApprovalReport(batchId: string): Promise<Blob> {
    const response = await fetch(
      `/api/incomes/invoices/batch-approval-report/?batch_id=${batchId}`,
      {
        headers: {
          Authorization: `Bearer ${localStorage.getItem('accessToken') || sessionStorage.getItem('accessToken')}`,
        },
      }
    );
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    return response.blob();
  },
};
