# Generated by Django 5.2.4 on 2026-05-21 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0010_insurance_verifier_disbursement'),
        ('branches', '0004_add_contact_fields_and_invoice_bank_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='main_bank_account',
            field=models.ForeignKey(blank=True, help_text="The branch's main bank account. Cash collected by COs is swept into this account's GL during daily reconciliation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_branches', to='banks.bankaccount'),
        ),
    ]
