# Generated by Django 5.2.4 on 2026-09-09 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_insurance_verifier_disbursement'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='attendance_radius_meters',
            field=models.PositiveIntegerField(default=1500, help_text="How far (in meters) from latitude/longitude staff may clock in/out. Ignored if latitude/longitude aren't set.", validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50000)]),
        ),
    ]
