# Generated by Django 5.2.4 on 2026-08-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
