# Generated by Django 5.2.4 on 2026-08-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_thread_is_locked_threadmessage_reply_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmessageattachment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='threads/attachments/thumbnails/'),
        ),
    ]
