# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branches', '0001_initial'),
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Role description')),
                ('can_access_dashboards', models.JSONField(default=list, help_text='List of dashboard IDs this role can access')),
                ('can_access_modules', models.JSONField(default=list, help_text='List of module codes this role can access')),
                ('can_access_pages', models.JSONField(default=list, help_text='List of page codes this role can access')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_dashboard', models.ForeignKey(blank=True, help_text='Default dashboard for users with this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_roles', to='dashboards.dashboard')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_active_user', models.BooleanField(default=True, help_text='Whether this user account is active for the tenant')),
                ('is_system_admin', models.BooleanField(default=False, help_text='True for system owner who manages all tenant subscriptions')),
                ('assigned_dashboard', models.ForeignKey(blank=True, help_text='Individual dashboard assignment (overrides role default)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='dashboards.dashboard')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='branches.branch')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='users.role')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier for subdomain (e.g., school1 for school1.yourdomain.com)', max_length=200, unique=True)),
                ('custom_domain', models.CharField(blank=True, help_text='Custom domain (e.g., www.schoolname.com)', max_length=255, null=True, unique=True)),
                ('domain_type', models.CharField(choices=[('microfinance', 'Microfinance Institution'), ('school', 'School'), ('hospital', 'Hospital'), ('retail', 'Retail Business'), ('multi', 'Multi-Domain')], default='microfinance', help_text='Primary domain type of this tenant', max_length=20)),
                ('domain_config', models.JSONField(default=dict, help_text='Domain-specific settings and customizations')),
                ('enabled_features', models.JSONField(default=list, help_text="List of enabled features for this tenant (e.g., ['inventory', 'hr', 'payroll'])")),
                ('custom_labels', models.JSONField(default=dict, help_text='Custom field labels for this tenant')),
                ('settings', models.JSONField(default=dict, help_text='General settings for this tenant')),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', help_text='Subscription tier', max_length=20)),
                ('subscription_expires', models.DateField(blank=True, help_text='Subscription expiry date', null=True)),
                ('max_users', models.IntegerField(default=10, help_text='Maximum number of users allowed')),
                ('max_storage_gb', models.IntegerField(default=5, help_text='Maximum storage in GB')),
                ('logo_url', models.URLField(blank=True, help_text='URL to tenant logo')),
                ('primary_color', models.CharField(default='#0066cc', help_text='Primary brand color (hex)', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(blank=True, help_text='The primary owner user for this tenant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_tenant',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.tenant'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug'], name='users_tenan_slug_99d161_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['custom_domain'], name='users_tenan_custom__b9ec8a_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['is_active'], name='users_tenan_is_acti_405a25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('tenant', 'name')},
        ),
    ]
