# Generated by Django 5.2.4 on 2026-01-18 22:00

from django.db import migrations


def setup_default_tenant(apps, schema_editor):
    """
    Create default tenant and assign all existing records to it.
    This is safe to run multiple times - it will skip if tenant exists
    and only update records that have NULL tenant_id.
    """
    Tenant = apps.get_model('users', 'Tenant')
    
    # Create or get default tenant
    default_tenant, created = Tenant.objects.get_or_create(
        slug='default',
        defaults={
            'name': 'Default Organization',
            'domain_type': 'subdomain',
            'is_active': True,
            'subscription_tier': 'enterprise',
            'enabled_features': [
                'inventory', 'procurement', 'receivables', 'payables',
                'hr', 'payroll', 'assets', 'loans', 'savings', 'school'
            ]
        }
    )
    
    if created:
        print(f"✓ Created default tenant: {default_tenant.name} (ID: {default_tenant.id})")
    else:
        print(f"✓ Using existing tenant: {default_tenant.name} (ID: {default_tenant.id})")
    
    # Use raw SQL to update all tables with tenant_id column
    # This is more reliable than iterating through models
    db_alias = schema_editor.connection.alias
    from django.db import connections
    connection = connections[db_alias]
    
    with connection.cursor() as cursor:
        # Get all tables with tenant_id column
        cursor.execute("""
            SELECT table_name 
            FROM information_schema.columns 
            WHERE column_name = 'tenant_id' 
            AND table_schema = 'public'
            AND table_name NOT LIKE '%_old'
            ORDER BY table_name;
        """)
        
        tables = [row[0] for row in cursor.fetchall()]
        
        total_updated = 0
        for table in tables:
            # Update records where tenant_id is NULL
            cursor.execute(f"""
                UPDATE {table} 
                SET tenant_id = %s 
                WHERE tenant_id IS NULL
            """, [default_tenant.id])
            
            count = cursor.rowcount
            if count > 0:
                total_updated += count
                print(f"  ✓ Updated {count} records in {table}")
        
        if total_updated > 0:
            print(f"\n✅ Total: Updated {total_updated} records across {len(tables)} tables")
        else:
            print(f"\n✅ All records already have tenant assigned")


def reverse_setup_default_tenant(apps, schema_editor):
    """
    Reverse migration: Set tenant_id to NULL for default tenant records.
    WARNING: This will make existing data inaccessible!
    Only use for testing or rollback scenarios.
    """
    Tenant = apps.get_model('users', 'Tenant')
    
    try:
        default_tenant = Tenant.objects.get(slug='default')
        print(f"⚠️ Reverting tenant assignment for: {default_tenant.name}")
        
        db_alias = schema_editor.connection.alias
        from django.db import connections
        connection = connections[db_alias]
        
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT table_name 
                FROM information_schema.columns 
                WHERE column_name = 'tenant_id' 
                AND table_schema = 'public'
                ORDER BY table_name;
            """)
            
            tables = [row[0] for row in cursor.fetchall()]
            
            for table in tables:
                cursor.execute(f"""
                    UPDATE {table} 
                    SET tenant_id = NULL 
                    WHERE tenant_id = %s
                """, [default_tenant.id])
                
                count = cursor.rowcount
                if count > 0:
                    print(f"  ✓ Reverted {count} records in {table}")
        
        # Optionally delete the default tenant
        # default_tenant.delete()
        # print(f"✓ Deleted default tenant")
        
    except Tenant.DoesNotExist:
        print("⚠️ Default tenant not found, nothing to revert")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            setup_default_tenant,
            reverse_setup_default_tenant
        ),
    ]
