# Generated by Django 5.2.4 on 2026-02-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_setup_default_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission_codes',
            field=models.JSONField(default=list, help_text='List of action permission codes (e.g., ["pr-list", "pr-create", "pr-approve"])'),
        ),
        migrations.AddField(
            model_name='user',
            name='permission_codes',
            field=models.JSONField(blank=True, default=list, help_text='User-specific permission codes that override/extend role permissions (e.g., ["pr-approve", "po-delete"])'),
        ),
    ]
