# Generated by Django 5.2.4 on 2026-03-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_contact_fields_and_invoice_bank_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload tenant/organisation logo (PNG, JPG, SVG)', null=True, upload_to='tenant_logos/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, help_text='External URL to tenant logo (used if no file uploaded)'),
        ),
    ]
