# Generated by Django 5.2.4 on 2026-03-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_tenant_logo_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='enabled_features',
            field=models.JSONField(blank=True, default=list, help_text="List of enabled features for this tenant (e.g., ['inventory', 'hr', 'payroll'])", null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='settings',
            field=models.JSONField(blank=True, default=dict, help_text='General settings for this tenant', null=True),
        ),
    ]
