# Generated by Django 5.2.4 on 2026-03-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_tenant_features_settings_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='custom_labels',
            field=models.JSONField(blank=True, default=dict, help_text='Custom field labels for this tenant', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='domain_config',
            field=models.JSONField(blank=True, default=dict, help_text='Domain-specific settings and customizations', null=True),
        ),
    ]
