# Generated by Django 5.2.4 on 2026-05-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_role_mf_scope_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='excluded_permission_codes',
            field=models.JSONField(blank=True, default=list, help_text='[LEGACY] Permission codes explicitly denied for this role.'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permission_codes',
            field=models.JSONField(default=list, help_text='[LEGACY] Flat list of action permission codes used by the frontend (e.g. ["pr-list", "loan-approve"]).  Populated automatically from RolePermissionPolicy.  Do not edit directly.'),
        ),
    ]
