# Generated by Django 5.2.4 on 2026-07-29 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_daily_reconciliation_and_exception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.FileField(blank=True, help_text='Upload tenant/organisation logo (PNG, JPG, SVG, WEBP, GIF)', null=True, upload_to='tenant_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg', 'webp', 'gif'])]),
        ),
    ]
