# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_posted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('maintenance_date', models.DateField(default=django.utils.timezone.now)),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Maintenance'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('performed_by', models.CharField(blank=True, max_length=200)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('meter_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Odometer, hour meter, etc.', max_digits=18, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('asset_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(blank=True, help_text='License plate, registration, etc.', max_length=100)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('units_of_production', 'Units of Production')], max_length=30)),
                ('useful_life_years', models.PositiveIntegerField()),
                ('depreciation_start_date', models.DateField()),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('assigned_to', models.CharField(blank=True, help_text='Employee, department, etc.', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active/In Use'), ('idle', 'Idle'), ('maintenance', 'Under Maintenance'), ('disposed', 'Disposed'), ('sold', 'Sold')], db_index=True, default='active', max_length=20)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('disposal_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, help_text='Asset-specific data (mileage, hours, etc.)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assets/photos/')),
            ],
            options={
                'ordering': ['asset_number'],
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('default_depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('units_of_production', 'Units of Production')], default='straight_line', max_length=30)),
                ('default_useful_life_years', models.PositiveIntegerField(default=5)),
                ('default_salvage_value_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('accumulated_depreciation_account', models.ForeignKey(help_text='Accumulated depreciation account (must be ASSET type - contra-asset)', on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories_accumulated', to='accounts.account')),
                ('asset_account', models.ForeignKey(help_text='Asset account (must be ASSET type)', on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories_asset', to='accounts.account')),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
            },
        ),
    ]
