# Generated by Django 5.2.4 on 2026-01-29 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_update_accountcategory_unique_constraint'),
        ('assets', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='maintenance_expense_account',
            field=models.ForeignKey(blank=True, help_text='Maintenance expense account (must be EXPENSE type)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories_maintenance', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
