# Generated by Django 5.2.4 on 2026-03-27 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_add_journal_entry_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdepreciation',
            name='posted_by',
            field=models.ForeignKey(blank=True, help_text='User who posted this depreciation entry to the GL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_depreciations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='payment_method',
            field=models.CharField(choices=[('credit', 'Credit (Accounts Payable)'), ('cash', 'Cash'), ('bank', 'Bank Transfer')], default='credit', help_text='How this maintenance was/will be paid. Determines GL credit account.', max_length=10),
        ),
        migrations.AddField(
            model_name='assetmaintenance',
            name='posted_by',
            field=models.ForeignKey(blank=True, help_text='User who posted this maintenance record to the GL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_maintenances', to=settings.AUTH_USER_MODEL),
        ),
    ]
