# Generated by Django 5.2.4 on 2026-04-01 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_add_posted_by_payment_method'),
        ('liabilities', '0003_accountspayable_posted_at_accountspayable_posted_by_and_more'),
        ('procurement', '0004_goodsreceivednoteitem_quality_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='accounts_payable',
            field=models.ForeignKey(blank=True, help_text='AP liability record auto-created when asset bought on credit', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='liabilities.accountspayable'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='PO auto-created for this asset acquisition (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier from whom this asset was purchased (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='procurement.supplier'),
        ),
    ]
