# Generated by Django 5.2.4 on 2026-04-01 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_fixedasset_supplier_po_ap_links'),
        ('branches', '0004_add_contact_fields_and_invoice_bank_flag'),
        ('liabilities', '0003_accountspayable_posted_at_accountspayable_posted_by_and_more'),
        ('procurement', '0004_goodsreceivednoteitem_quality_data_and_more'),
        ('transactions', '0006_fix_empty_sequence_names'),
        ('users', '0007_tenant_domainconfig_customlabels_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reference_number', models.CharField(db_index=True, help_text='Auto-generated reference, e.g. ACQ-20260401-0001', max_length=60, unique=True)),
                ('purchase_date', models.DateField(help_text='Date of purchase / invoice date')),
                ('payment_terms', models.CharField(blank=True, help_text='e.g. net_30 – overrides supplier default when set', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], db_index=True, default='draft', max_length=10)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('accounts_payable', models.OneToOneField(blank=True, help_text='AP record auto-created when this acquisition is posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_acquisition', to='liabilities.accountspayable')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, help_text='GL journal entry auto-created when this acquisition is posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_acquisition_journal', to='transactions.transaction')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_asset_acquisitions', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(blank=True, help_text='PO auto-created when this acquisition is posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_acquisition', to='procurement.purchaseorder')),
                ('supplier', models.ForeignKey(help_text='Supplier from whom the assets are being purchased', on_delete=django.db.models.deletion.PROTECT, related_name='asset_acquisitions', to='procurement.supplier')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['-purchase_date', '-reference_number'],
            },
        ),
        migrations.CreateModel(
            name='AssetAcquisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Asset name / description', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Computed: quantity × unit_price', max_digits=18)),
                ('depreciation_method', models.CharField(blank=True, choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('units_of_production', 'Units of Production')], help_text='Leave blank to inherit from category default', max_length=30)),
                ('useful_life_years', models.PositiveIntegerField(blank=True, help_text='Leave blank to inherit from category default', null=True)),
                ('salvage_value_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Salvage % of unit price – leave blank to inherit from category', max_digits=5, null=True)),
                ('acquisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='assets.assetacquisition')),
                ('asset_category', models.ForeignKey(help_text='Asset category – determines the GL debit account', on_delete=django.db.models.deletion.PROTECT, related_name='acquisition_lines', to='assets.assetcategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='acquisition_line',
            field=models.ForeignKey(blank=True, help_text='Acquisition batch line that generated this asset (optional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='assets.assetacquisitionline'),
        ),
    ]
