# Generated by Django 5.2.4 on 2026-04-02 15:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_asset_acquisition_line_items'),
        ('branches', '0004_add_contact_fields_and_invoice_bank_flag'),
        ('users', '0007_tenant_domainconfig_customlabels_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ar_number', models.CharField(db_index=True, help_text='Auto-generated reference, e.g. AR-20260401-0001', max_length=60, unique=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('required_by_date', models.DateField(blank=True, help_text='When the assets are needed', null=True)),
                ('purpose', models.TextField(help_text='Business justification for the asset purchase')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('converted', 'Converted to Acquisition'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('estimated_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('approval_chain', models.JSONField(blank=True, default=list)),
                ('acquisition', models.OneToOneField(blank=True, help_text='AssetAcquisition created when this requisition was approved and converted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition', to='assets.assetacquisition')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_asset_requisitions', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_requisitions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetRequisitionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='What exactly is needed and why')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('estimated_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Rough cost estimate – refined by Finance before posting', max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('asset_category', models.ForeignKey(help_text='Type of asset being requested', on_delete=django.db.models.deletion.PROTECT, related_name='requisition_lines', to='assets.assetcategory')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.assetrequisition')),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='assetrequisition',
            index=models.Index(fields=['status', 'request_date'], name='assets_asse_status_b1d51d_idx'),
        ),
    ]
