# Generated by Django 5.2.4 on 2026-04-10 18:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_assetacquisition_approved_at_acquisition_and_more'),
        ('procurement', '0004_goodsreceivednoteitem_quality_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetrequisitionline',
            name='estimated_unit_price',
        ),
        migrations.AddField(
            model_name='assetacquisitionline',
            name='registered_asset',
            field=models.ForeignKey(blank=True, help_text='Registered asset shell to activate on posting (preferred). If blank, a new FixedAsset record is created.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acquisition_line_links', to='assets.fixedasset'),
        ),
        migrations.AddField(
            model_name='assetrequisitionline',
            name='actual_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Actual (or best-estimate) unit cost from the supplier', max_digits=18),
        ),
        migrations.AddField(
            model_name='assetrequisitionline',
            name='asset',
            field=models.ForeignKey(blank=True, help_text='Registered asset (from the asset register) being requisitioned', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisition_lines', to='assets.fixedasset'),
        ),
        migrations.AddField(
            model_name='assetrequisitionline',
            name='is_activated',
            field=models.BooleanField(default=False, help_text='True once the linked FixedAsset has been activated (value set, GL posted)'),
        ),
        migrations.AddField(
            model_name='assetrequisitionline',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Supplier for this specific asset line item', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_requisition_lines', to='procurement.supplier'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='depreciation_batch_id',
            field=models.CharField(blank=True, db_index=True, help_text='Reference linking assets acquired together (e.g. ACQ-20260401-0001). Each asset still has its own depreciation schedule.', max_length=60),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='registered_at',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date the asset was registered in the system (before acquisition)'),
        ),
        migrations.AlterField(
            model_name='assetrequisitionline',
            name='asset_category',
            field=models.ForeignKey(blank=True, help_text='Category derived from the linked asset (auto-set on save)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisition_lines', to='assets.assetcategory'),
        ),
        migrations.AlterField(
            model_name='assetrequisitionline',
            name='description',
            field=models.TextField(blank=True, help_text='Additional details / justification for this specific asset'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='depreciation_method',
            field=models.CharField(blank=True, choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('units_of_production', 'Units of Production')], help_text='Defaults to category setting; can be overridden per asset', max_length=30),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='depreciation_start_date',
            field=models.DateField(blank=True, help_text='Set automatically to purchase_date when the asset is activated', null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Date of actual purchase — set when asset is activated via acquisition', null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Actual cost — 0 until activated via acquisition', max_digits=18),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft / Registered (Pending Acquisition)'), ('active', 'Active / In Use'), ('idle', 'Idle'), ('maintenance', 'Under Maintenance'), ('disposed', 'Disposed'), ('sold', 'Sold')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='useful_life_years',
            field=models.PositiveIntegerField(blank=True, help_text='Defaults to category setting; can be overridden per asset', null=True),
        ),
    ]
