# Generated by Django 5.2.4 on 2026-04-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_asset_register_requisition_overhaul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetacquisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('routine', 'Routine Maintenance'), ('preventive', 'Preventive Maintenance'), ('corrective', 'Corrective Maintenance'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('overhaul', 'Overhaul'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='assetmaintenance',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('bank', 'Bank Transfer'), ('petty_cash', 'Petty Cash'), ('cheque', 'Cheque'), ('credit_card', 'Credit Card'), ('credit', 'Credit / Accounts Payable')], default='credit', help_text='How this maintenance was/will be paid. Determines GL credit account.', max_length=20),
        ),
    ]
