# Generated by Django 5.2.4 on 2026-07-31 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_code'),
        ('assets', '0013_alter_assetacquisition_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='account',
            field=models.OneToOneField(blank=True, help_text="This asset's own GL cost account (once its category is migrated to per-asset tracking)", limit_choices_to={'account_level': 'CHILD', 'account_type': 'ASSET'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_detail', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='accumulated_depreciation_account',
            field=models.OneToOneField(blank=True, help_text="This asset's own accumulated-depreciation GL account (contra-asset)", limit_choices_to={'account_level': 'CHILD', 'account_type': 'ASSET'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fixed_asset_accumulated_depreciation_detail', to='accounts.account'),
        ),
    ]
