# Generated by Django 5.2.4 on 2026-01-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('calculation_date', models.DateField()),
                ('daily_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('accrued_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('posting_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='active', max_length=20)),
                ('opened_on', models.DateField()),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('last_transaction_date', models.DateField(blank=True, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_calculation_method', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20)),
                ('minimum_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('allow_overdraft', models.BooleanField(default=False)),
                ('overdraft_limit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('auto_renew', models.BooleanField(default=True)),
                ('statement_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually'), ('on_demand', 'On Demand')], default='monthly', max_length=20)),
            ],
            options={
                'ordering': ['-opened_on'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('target_date', models.DateField()),
                ('auto_save', models.BooleanField(default=False)),
                ('save_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True)),
                ('save_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.CharField(max_length=200)),
                ('hold_type', models.CharField(choices=[('pending_debit', 'Pending Debit'), ('legal_hold', 'Legal Hold'), ('collateral', 'Collateral Hold'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('expired', 'Expired')], default='active', max_length=20)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
