# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('branches', '0002_initial'),
        ('clients', '0002_initial'),
        ('products', '0002_initial'),
        ('savings', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interestaccrual',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interestaccrual',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interestaccrual',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_interest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interestaccrual',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='account',
            field=models.OneToOneField(limit_choices_to={'account_level': 'CHILD', 'account_type': 'SAVINGS'}, on_delete=django.db.models.deletion.PROTECT, related_name='savings_account_detail', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_accounts', to='clients.client'),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'SAVINGS'}, on_delete=django.db.models.deletion.PROTECT, related_name='savings_accounts', to='products.product'),
        ),
        migrations.AddField(
            model_name='savingsaccount',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='interestaccrual',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_accruals', to='savings.savingsaccount'),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='savings.savingsaccount'),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='transactionhold',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_holds', to='savings.savingsaccount'),
        ),
        migrations.AddField(
            model_name='transactionhold',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionhold',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionhold',
            name='placed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placed_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionhold',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionhold',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddIndex(
            model_name='savingsaccount',
            index=models.Index(fields=['account_number'], name='savings_sav_account_5fdcd4_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsaccount',
            index=models.Index(fields=['status'], name='savings_sav_status_ba7fdd_idx'),
        ),
        migrations.AddIndex(
            model_name='interestaccrual',
            index=models.Index(fields=['calculation_date'], name='savings_int_calcula_3873bc_idx'),
        ),
        migrations.AddIndex(
            model_name='interestaccrual',
            index=models.Index(fields=['status'], name='savings_int_status_ea210e_idx'),
        ),
    ]
