# Generated by Django 5.2.4 on 2026-06-25 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_code'),
        ('savings', '0004_savingsproduct_withdrawal_models'),
        ('users', '0010_daily_reconciliation_and_exception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='savingswithdrawalrequest',
            new_name='savings_sav_status_7871d2_idx',
            old_name='savings_swr_status_ca_idx',
        ),
        migrations.RenameIndex(
            model_name='savingswithdrawalrequest',
            new_name='savings_sav_savings_1d9a92_idx',
            old_name='savings_swr_acct_st_idx',
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='cycle_length_months',
            field=models.PositiveIntegerField(blank=True, help_text='Length of the savings cycle in months (e.g. 3).', null=True),
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='first_deposit_income_account',
            field=models.ForeignKey(blank=True, help_text='Income GL account for first-deposit income. Required when first_deposit_is_income=True.', limit_choices_to={'account_type': 'INCOME'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='savings_first_deposit_income', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='first_deposit_is_income',
            field=models.BooleanField(default=False, help_text="When True, the first deposit each calendar month is posted as income rather than added to the client's savings balance."),
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='has_savings_cycle',
            field=models.BooleanField(default=False, help_text='Enable fixed-term cycle savings (e.g. 3-month cycle with interest/penalty).'),
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='only_account_manager_can_withdraw',
            field=models.BooleanField(default=True, help_text="Only the client's assigned account manager (Client.account_manager) may initiate a withdrawal request."),
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savingsproduct',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AlterField(
            model_name='savingswithdrawalrequest',
            name='cashier_account',
            field=models.ForeignKey(blank=True, help_text='Cash / Cashier GL account debited from savings, used when no bank account.', limit_choices_to={'account_type': 'ASSET'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_request_cashier', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='savingswithdrawalrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savingswithdrawalrequest',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savingswithdrawalrequest',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AlterField(
            model_name='withdrawalapprovalstep',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalapprovalstep',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalapprovalstep',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AlterField(
            model_name='withdrawalapprovaltier',
            name='approver_roles',
            field=models.JSONField(default=list, help_text='List of Django auth.Group names that can approve, e.g. ["Manager", "Admin"].'),
        ),
        migrations.AlterField(
            model_name='withdrawalapprovaltier',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalapprovaltier',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
    ]
