# Generated by Django 5.2.4 on 2026-06-29 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0005_rename_savings_swr_status_ca_idx_savings_sav_status_7871d2_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savingswithdrawalrequest',
            name='disbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingswithdrawalrequest',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, help_text='The user who physically released funds (must differ from creator and all approvers).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_withdrawals', to=settings.AUTH_USER_MODEL),
        ),
    ]
