# Generated by Django 5.2.4 on 2026-07-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0007_add_payment_method_to_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='last_first_deposit_income_date',
            field=models.DateField(blank=True, help_text="Date of the most recent deposit posted as first-deposit-income (daily contribution). Used to detect whether this calendar month's first-deposit-income has already been charged — deliberately separate from last_transaction_date, which is also touched by withdrawals.", null=True),
        ),
    ]
