# Generated by Django 5.2.4 on 2026-07-20 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_code'),
        ('banks', '0029_reconciliationexception_unresolved_at_and_more'),
        ('branches', '0005_insurance_verifier_disbursement'),
        ('clients', '0015_clientgroup_member_officers'),
        ('products', '0003_savings_cycles_and_smart_savings'),
        ('savings', '0008_savingsaccount_last_first_deposit_income_date_and_more'),
        ('users', '0010_daily_reconciliation_and_exception'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingswithdrawalrequest',
            name='cashier_account',
            field=models.ForeignKey(blank=True, help_text='Cash / Cashier GL account debited from savings, used for cash withdrawals.', limit_choices_to={'account_type': 'ASSET'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_request_cashier', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='savingswithdrawalrequest',
            name='destination_bank_account',
            field=models.ForeignKey(blank=True, help_text='Bank account to credit when withdrawal completes (bank transfers only).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_withdrawal_requests', to='banks.bankaccount'),
        ),
        migrations.AlterField(
            model_name='savingswithdrawalrequest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank Transfer')], help_text="Set by the Branch Manager during approval. 'cash' = teller payout via a cashier GL account; 'bank' = bank transfer. Amounts ≥ ₦50,000 are forced to 'bank'.", max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='savingsaccount',
            index=models.Index(fields=['client', 'product'], name='savings_sav_client__9c1e99_idx'),
        ),
        migrations.AddConstraint(
            model_name='savingsaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('status', 'closed'), _negated=True)), fields=('client', 'product'), name='unique_active_savings_per_client_product'),
        ),
    ]
