# Generated by Django 5.2.4 on 2026-07-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0009_alter_savingswithdrawalrequest_cashier_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsaccount',
            name='contribution_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="This client's committed contribution amount per cycle. Overrides the product's default contribution_amount when set.", max_digits=18, null=True),
        ),
    ]
