# Generated by Django 5.2.4 on 2026-08-18 12:30
#
# Changes the unique constraint on SavingsAccount.account_number from a
# global unique=True to (account_number, tenant, branch) — same fix as
# accounts/migrations/0010_fix_account_unique_constraint.py applied to
# Account.code.
#
# WHY:
#   account_number is copied from the linked GL child account's code
#   (savings/signals.py, backfill_missing_default_savings.py), and that
#   sub-ledger numbering (Account.create_with_parent) is scoped per
#   (tenant, branch) by design — every branch's own '2140' parent restarts
#   its child sequence at -00001. A global unique=True on account_number
#   made every branch's first-ever savings account collide with whichever
#   other branch had already claimed "2140-00001", silently blocking the
#   default-savings-account signal for every subsequent client in that
#   branch (caught by the signal's broad except-and-log). No dedup needed:
#   any set that was globally unique is automatically unique within this
#   narrower scope too.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_code'),
        ('branches', '0005_insurance_verifier_disbursement'),
        ('clients', '0016_clientregistrationconfig_reactivation_fee_and_more'),
        ('products', '0003_savings_cycles_and_smart_savings'),
        ('savings', '0010_savingsaccount_contribution_amount'),
        ('users', '0011_alter_tenant_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsaccount',
            name='account_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='savingsaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('account_number', 'tenant', 'branch'), name='unique_account_number_per_tenant_branch_when_not_deleted'),
        ),
    ]
