# Generated by Django 5.2.4 on 2026-05-25 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField(help_text='Calendar date (Africa/Lagos timezone) that the batch ran for.')),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('STOPPED', 'Stopped')], max_length=20)),
                ('loans_processed', models.PositiveIntegerField(default=0)),
                ('loans_skipped', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When Django received this summary from the batch processor.')),
            ],
            options={
                'verbose_name': 'Batch Run Log',
                'verbose_name_plural': 'Batch Run Logs',
                'ordering': ['-run_date', '-received_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanAccrualRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.PositiveIntegerField(db_index=True)),
                ('idempotency_key', models.CharField(help_text='Format: "{loanId}-{YYYY-MM-DD}" e.g. "1042-2026-05-23"', max_length=60, unique=True)),
                ('run_date', models.DateField()),
                ('accrual_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('provision_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('risk_classification_applied', models.CharField(max_length=20)),
                ('days_in_arrears_at_run', models.PositiveIntegerField(default=0)),
                ('journal_entry_id', models.PositiveIntegerField(blank=True, help_text='PK of the Transaction (GL journal entry) created for this accrual.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Loan Accrual Record',
                'verbose_name_plural': 'Loan Accrual Records',
                'ordering': ['-run_date', 'loan_id'],
            },
        ),
    ]
