// src/config/permissionModules.ts
import {
  Eye,
  Edit,
  Plus,
  Trash2,
  Check,
  X,
  Download,
  Upload,
  Send,
  FileText,
  Calculator,
  BarChart3,
  Users,
  Package,
  ShoppingCart,
  RotateCcw,
  Building,
  Boxes,
  TrendingUp,
  CheckSquare,
  AlertTriangle,
  Calendar,
  DollarSign,
  Truck,
  ClipboardList,
  PieChart,
  Receipt,
  CreditCard,
  Target,
  GraduationCap,
  Clock,
  Tag,
  Activity,
  Folder,
  Trash,
  CheckCircle,
  Printer,
  Quote,
  Scale,
  XCircle,
  Home,
  ExternalLink,
  Settings,
} from 'lucide-react';
import { ModuleInfo } from '@/pages/settings/components/PermissionEditor';

export const modulesData: ModuleInfo[] = [
  {
    id: 'procurement',
    name: 'Procurement',
    description: 'Purchase requisitions, orders, quotes, and supplier management',
    pages: [
      {
        id: 'purchase-orders',
        name: 'Purchase Orders',
        path: '/procurement/orders',
        description: 'Manage purchase orders from creation to receipt',
        actions: [
          // List actions
          {
            id: 'po-list',
            name: 'View Purchase Orders',
            type: 'view',
            description: 'View list of purchase orders',
            icon: Eye,
          },
          {
            id: 'po-bulk-approve',
            name: 'Bulk Approve',
            type: 'approve',
            description: 'Approve multiple orders',
            icon: Check,
          },
          {
            id: 'po-export',
            name: 'Export List',
            type: 'export',
            description: 'Export orders to Excel/PDF',
            icon: Download,
          },
          // Create
          {
            id: 'po-create',
            name: 'Create Purchase Order',
            type: 'create',
            description: 'Create new purchase order',
            icon: Plus,
          },
          // Detail actions
          {
            id: 'po-view-detail',
            name: 'View Purchase Order Details',
            type: 'view',
            description: 'View purchase order details',
            icon: Eye,
          },
          {
            id: 'po-edit',
            name: 'Edit Order',
            type: 'edit',
            description: 'Edit purchase order (draft only)',
            icon: Edit,
          },
          {
            id: 'po-save-draft',
            name: 'Save as Draft',
            type: 'create',
            description: 'Save order as draft',
            icon: FileText,
          },
          {
            id: 'po-submit-approval',
            name: 'Submit for Approval',
            type: 'process',
            description: 'Submit purchase order for approval',
            icon: Send,
          },
          {
            id: 'po-approve',
            name: 'Approve Order',
            type: 'approve',
            description: 'Approve purchase order',
            icon: CheckCircle,
          },
          {
            id: 'po-send',
            name: 'Send to Supplier',
            type: 'process',
            description: 'Send purchase order to supplier',
            icon: Send,
          },
          {
            id: 'po-acknowledge',
            name: 'Acknowledge Receipt',
            type: 'process',
            description: 'Acknowledge supplier receipt',
            icon: CheckCircle,
          },
          {
            id: 'po-generate-pdf',
            name: 'Download PDF',
            type: 'export',
            description: 'Generate and download PDF',
            icon: Download,
          },
          {
            id: 'po-cancel',
            name: 'Cancel Order',
            type: 'process',
            description: 'Cancel purchase order',
            icon: XCircle,
          },
          {
            id: 'po-delete',
            name: 'Delete Order',
            type: 'delete',
            description: 'Delete purchase order (draft only)',
            icon: Trash2,
          },
        ],
      },
      {
        id: 'purchase-requisitions',
        name: 'Purchase Requisitions',
        path: '/procurement/requisitions',
        description: 'Manage purchase requisitions with approval workflow and quotes',
        actions: [
          // List
          {
            id: 'pr-list',
            name: 'View Requisitions',
            type: 'view',
            description: 'View all requisitions',
            icon: Eye,
          },
          {
            id: 'pr-create',
            name: 'Create Requisition',
            type: 'create',
            description: 'Create new requisition',
            icon: Plus,
          },
          {
            id: 'pr-view-detail',
            name: 'View Requisition Details',
            type: 'view',
            description: 'View requisition details',
            icon: Eye,
          },
          {
            id: 'pr-edit',
            name: 'Edit Requisition',
            type: 'edit',
            description: 'Edit requisition details',
            icon: Edit,
          },
          {
            id: 'pr-delete',
            name: 'Delete Requisition',
            type: 'delete',
            description: 'Delete requisition',
            icon: Trash2,
          },
          {
            id: 'pr-approve',
            name: 'Approve Requisition',
            type: 'approve',
            description: 'Approve requisition',
            icon: Check,
          },
          {
            id: 'pr-reject',
            name: 'Reject Requisition',
            type: 'reject',
            description: 'Reject requisition',
            icon: X,
          },
          {
            id: 'pr-convert-to-po',
            name: 'Convert to PO',
            type: 'process',
            description: 'Convert to purchase order',
            icon: ExternalLink,
          },
          {
            id: 'pr-submit-approval',
            name: 'Submit for Approval',
            type: 'process',
            description: 'Submit requisition for approval',
            icon: Send,
          },
          {
            id: 'pr-request-quotes',
            name: 'Request Quotes',
            type: 'process',
            description: 'Request quotes from suppliers',
            icon: Quote,
          },
          {
            id: 'pr-view-quotes',
            name: 'View Quotes',
            type: 'view',
            description: 'View supplier quotes comparison',
            icon: Eye,
          },
          {
            id: 'pr-compare-quotes',
            name: 'Compare Quotes',
            type: 'view',
            description: 'Compare supplier quotes',
            icon: Scale,
          },
          {
            id: 'pr-select-quote',
            name: 'Select Quote',
            type: 'process',
            description: 'Select a quote for conversion',
            icon: Check,
          },
          {
            id: 'pr-convert-quote-to-po',
            name: 'Convert Quote to PO',
            type: 'process',
            description: 'Convert selected quote to purchase order',
            icon: ShoppingCart,
          },
        ],
      },
      {
        id: 'goods-received-notes',
        name: 'Goods Received Notes (GRN)',
        path: '/procurement/grn',
        description: 'Manage goods receipt, quality inspection, and posting',
        actions: [
          {
            id: 'grn-list',
            name: 'View GRNs',
            type: 'view',
            description: 'View all goods receipt notes',
            icon: Eye,
          },
          {
            id: 'grn-create',
            name: 'Create GRN',
            type: 'create',
            description: 'Create goods receipt note',
            icon: Plus,
          },
          {
            id: 'grn-view-detail',
            name: 'View GRN Details',
            type: 'view',
            description: 'View GRN details',
            icon: Eye,
          },
          {
            id: 'grn-quality-check',
            name: 'Quality Check',
            type: 'process',
            description: 'Perform quality inspection',
            icon: CheckSquare,
          },
          {
            id: 'grn-post',
            name: 'Post to Inventory',
            type: 'process',
            description: 'Post GRN to inventory and create AP entry',
            icon: Package,
          },
          {
            id: 'grn-create-return',
            name: 'Create Return',
            type: 'process',
            description: 'Create return for rejected items',
            icon: RotateCcw,
          },
          {
            id: 'grn-print',
            name: 'Print GRN',
            type: 'export',
            description: 'Print GRN document',
            icon: Printer,
          },
          {
            id: 'grn-edit',
            name: 'Edit GRN',
            type: 'edit',
            description: 'Edit GRN (only when not posted)',
            icon: Edit,
          },
        ],
      },
      {
        id: 'purchase-returns',
        name: 'Purchase Returns',
        path: '/procurement/returns',
        description: 'Manage returns, refunds, and credit notes',
        actions: [
          {
            id: 'return-list',
            name: 'View Returns',
            type: 'view',
            description: 'View all purchase returns',
            icon: Eye,
          },
          {
            id: 'return-create',
            name: 'Create Return',
            type: 'create',
            description: 'Create new return',
            icon: Plus,
          },
          {
            id: 'return-view-detail',
            name: 'View Return Details',
            type: 'view',
            description: 'View return details',
            icon: Eye,
          },
          {
            id: 'return-approve',
            name: 'Approve Return',
            type: 'approve',
            description: 'Approve return request',
            icon: Check,
          },
          {
            id: 'return-process-refund',
            name: 'Process Refund',
            type: 'process',
            description: 'Process refund payment',
            icon: DollarSign,
          },
          {
            id: 'return-complete',
            name: 'Complete Return',
            type: 'process',
            description: 'Mark the return as complete',
            icon: CreditCard,
          },
          {
            id: 'return-cancel',
            name: 'Cancel Return',
            type: 'process',
            description: 'Cancel return',
            icon: X,
          },
        ],
      },
      {
        id: 'suppliers',
        name: 'Suppliers',
        path: '/procurement/suppliers',
        description: 'Manage supplier information and performance',
        actions: [
          {
            id: 'supplier-list',
            name: 'View Suppliers',
            type: 'view',
            description: 'View all suppliers',
            icon: Eye,
          },
          {
            id: 'supplier-create',
            name: 'Create Supplier',
            type: 'create',
            description: 'Add new supplier',
            icon: Plus,
          },
          {
            id: 'supplier-view-detail',
            name: 'View Supplier Details',
            type: 'view',
            description: 'View supplier details',
            icon: Eye,
          },
          {
            id: 'supplier-edit',
            name: 'Edit Supplier',
            type: 'edit',
            description: 'Edit supplier information',
            icon: Edit,
          },
          {
            id: 'supplier-deactivate',
            name: 'Deactivate Supplier',
            type: 'process',
            description: 'Deactivate supplier',
            icon: X,
          },
        ],
      },
    ],
  },
  {
    id: 'inventory',
    name: 'Inventory',
    description: 'Stock tracking, movements, and inventory operations',
    pages: [
      {
        id: 'inventory-dashboard',
        name: 'Inventory Dashboard',
        path: '/inventory',
        description: 'Complete inventory overview with stats and quick actions',
        actions: [
          {
            id: 'inv-dashboard-view',
            name: 'View Dashboard',
            type: 'view',
            description: 'View inventory overview',
            icon: Eye,
          },
        ],
      },
      {
        id: 'inventory-items',
        name: 'Inventory Items',
        path: '/inventory/items',
        description: 'Manage item catalog with pricing and tracking',
        actions: [
          {
            id: 'item-list',
            name: 'View Items',
            type: 'view',
            description: 'View all inventory items',
            icon: Eye,
          },
          {
            id: 'item-create',
            name: 'Create Item',
            type: 'create',
            description: 'Create new inventory item',
            icon: Plus,
          },
          {
            id: 'item-edit',
            name: 'Edit Item',
            type: 'edit',
            description: 'Edit existing item',
            icon: Edit,
          },
        ],
      },
      {
        id: 'stock-movements',
        name: 'Stock Movements',
        path: '/inventory/movements',
        description: 'View movement history',
        actions: [
          {
            id: 'movement-list',
            name: 'View Movements',
            type: 'view',
            description: 'View stock movements',
            icon: Eye,
          },
        ],
      },
      {
        id: 'stock-adjustments',
        name: 'Stock Adjustments',
        path: '/inventory/adjustments',
        description: 'Create and manage stock adjustments',
        actions: [
          {
            id: 'adjustment-create',
            name: 'Create Adjustment',
            type: 'create',
            description: 'Create stock adjustment',
            icon: Plus,
          },
        ],
      },
      {
        id: 'stock-transfers',
        name: 'Stock Transfers',
        path: '/inventory/transfers',
        description: 'Transfer inventory between locations',
        actions: [
          {
            id: 'transfer-create',
            name: 'Create Transfer',
            type: 'create',
            description: 'Create stock transfer',
            icon: Plus,
          },
        ],
      },
      {
        id: 'item-categories',
        name: 'Item Categories',
        path: '/inventory/categories',
        description: 'Manage item categories',
        actions: [
          {
            id: 'category-list',
            name: 'View Categories',
            type: 'view',
            description: 'View all item categories',
            icon: Eye,
          },
          {
            id: 'category-create',
            name: 'Create Category',
            type: 'create',
            description: 'Create new item category',
            icon: Plus,
          },
          {
            id: 'category-edit',
            name: 'Edit Category',
            type: 'edit',
            description: 'Edit category details',
            icon: Edit,
          },
          {
            id: 'category-delete',
            name: 'Delete Category',
            type: 'delete',
            description: 'Delete item category',
            icon: Trash2,
          },
        ],
      },
      {
        id: 'inventory-locations',
        name: 'Inventory Locations',
        path: '/inventory/locations',
        description: 'Manage storage locations',
        actions: [
          {
            id: 'location-list',
            name: 'View Locations',
            type: 'view',
            description: 'View storage locations',
            icon: Eye,
          },
          {
            id: 'location-create',
            name: 'Create Location',
            type: 'create',
            description: 'Add new storage location',
            icon: Plus,
          },
          {
            id: 'location-edit',
            name: 'Edit Location',
            type: 'edit',
            description: 'Edit location details',
            icon: Edit,
          },
        ],
      },
    ],
  },
  {
    id: 'receivables',
    name: 'Receivables & Invoicing',
    description: 'Invoicing, payments, entitlements, and fee structures',
    pages: [
      {
        id: 'invoices',
        name: 'Invoices',
        path: '/sales/invoices',
        description: 'Manage customer invoices and payments',
        actions: [
          {
            id: 'invoice-list',
            name: 'View Invoices',
            type: 'view',
            description: 'View all invoices',
            icon: Eye,
          },
          {
            id: 'invoice-create',
            name: 'Create Invoice',
            type: 'create',
            description: 'Create new invoice',
            icon: Plus,
          },
          {
            id: 'invoice-preview',
            name: 'Preview Invoice',
            type: 'view',
            description: 'Preview before saving',
            icon: Eye,
          },
          {
            id: 'invoice-record-payment',
            name: 'Record Payment',
            type: 'create',
            description: 'Record invoice payment',
            icon: CreditCard,
          },
          {
            id: 'invoice-view-detail',
            name: 'View Invoice Details',
            type: 'view',
            description: 'View invoice details',
            icon: Eye,
          },
          {
            id: 'invoice-edit',
            name: 'Edit Invoice',
            type: 'edit',
            description: 'Edit draft invoice',
            icon: Edit,
          },
          {
            id: 'invoice-mark-sent',
            name: 'Mark as Sent',
            type: 'process',
            description: 'Mark invoice as sent',
            icon: Send,
          },
          {
            id: 'invoice-export-pdf',
            name: 'Export PDF',
            type: 'export',
            description: 'Generate PDF invoice',
            icon: Download,
          },
          {
            id: 'invoice-send',
            name: 'Send Invoice',
            type: 'send',
            description: 'Email invoice to customer',
            icon: Send,
          },
          {
            id: 'invoice-void',
            name: 'Void Invoice',
            type: 'process',
            description: 'Void the invoice',
            icon: X,
          },
        ],
      },
      {
        id: 'entitlements',
        name: 'Entitlements',
        path: '/incomes/entitlements',
        description: 'Manage client repayment schedules and loan assignments',
        actions: [
          {
            id: 'entitlement-list',
            name: 'View Entitlements',
            type: 'view',
            description: 'View all client repayment schedules',
            icon: Eye,
          },
          {
            id: 'entitlement-create',
            name: 'Create Entitlement',
            type: 'create',
            description: 'Create new entitlement',
            icon: Plus,
          },
          {
            id: 'entitlement-view-detail',
            name: 'View Entitlement Details',
            type: 'view',
            description: 'View entitlement details',
            icon: Eye,
          },
          {
            id: 'entitlement-edit',
            name: 'Edit Entitlement',
            type: 'edit',
            description: 'Edit entitlement information',
            icon: Edit,
          },
          {
            id: 'entitlement-delete',
            name: 'Delete Entitlement',
            type: 'delete',
            description: 'Delete entitlement',
            icon: Trash2,
          },
        ],
      },
      {
        id: 'fee-structures',
        name: 'Fee Structures',
        path: '/incomes/fee-structures',
        description: 'Configure loan products for financial periods',
        actions: [
          {
            id: 'fee-structure-list',
            name: 'View Fee Structures',
            type: 'view',
            description: 'View all fee structures',
            icon: Eye,
          },
          {
            id: 'fee-structure-create',
            name: 'Create Fee Structure',
            type: 'create',
            description: 'Create new fee structure',
            icon: Plus,
          },
          {
            id: 'fee-structure-view-detail',
            name: 'View Fee Structure Details',
            type: 'view',
            description: 'View fee structure details',
            icon: Eye,
          },
          {
            id: 'fee-structure-edit',
            name: 'Edit Fee Structure',
            type: 'edit',
            description: 'Edit fee structure configuration',
            icon: Edit,
          },
          {
            id: 'fee-structure-delete',
            name: 'Delete Fee Structure',
            type: 'process',
            description: 'Delete fee structure',
            icon: X,
          },
        ],
      },
      {
        id: 'receivables-list',
        name: 'All Receivables',
        path: '/receivables/list',
        description: 'Unified view of all receivables',
        actions: [
          {
            id: 'receivables-list',
            name: 'List All Receivables',
            type: 'view',
            description: 'View all receivables',
            icon: Eye,
          },
        ],
      },
    ],
  },
  {
    id: 'hr-payroll',
    name: 'HR & Payroll',
    description: 'Staff management, payroll, attendance, and leave',
    pages: [
      {
        id: 'hr-dashboard',
        name: 'HR Dashboard',
        path: '/hr',
        description: 'Main HR overview',
        actions: [
          {
            id: 'hr-dashboard-view',
            name: 'View Dashboard',
            type: 'view',
            description: 'View HR overview',
            icon: Eye,
          },
          {
            id: 'hr-staff-summary',
            name: 'View Staff Summary',
            type: 'view',
            description: 'View staff statistics',
            icon: Users,
          },
          {
            id: 'hr-attendance-summary',
            name: 'View Attendance Summary',
            type: 'view',
            description: 'View attendance overview',
            icon: CheckSquare,
          },
          {
            id: 'hr-leave-summary',
            name: 'View Leave Summary',
            type: 'view',
            description: 'View leave statistics',
            icon: Calendar,
          },
          {
            id: 'hr-payroll-summary',
            name: 'View Payroll Summary',
            type: 'view',
            description: 'View payroll overview',
            icon: DollarSign,
          },
        ],
      },
      {
        id: 'staff-management',
        name: 'Staff Management',
        path: '/hr/staff',
        description: 'Complete staff directory',
        actions: [
          {
            id: 'staff-list',
            name: 'View Staff',
            type: 'view',
            description: 'View all staff members',
            icon: Eye,
          },
          {
            id: 'staff-create',
            name: 'Add Staff Member',
            type: 'create',
            description: 'Add new staff member',
            icon: Plus,
          },
          {
            id: 'staff-view-detail',
            name: 'View Staff Details',
            type: 'view',
            description: 'View staff member details',
            icon: Eye,
          },
          {
            id: 'staff-edit',
            name: 'Edit Staff',
            type: 'edit',
            description: 'Edit staff information',
            icon: Edit,
          },
          {
            id: 'staff-delete',
            name: 'Delete Staff',
            type: 'process',
            description: 'Delete staff member',
            icon: X,
          },
        ],
      },
      {
        id: 'attendance-management',
        name: 'Attendance Management',
        path: '/hr/attendance',
        description: 'Daily attendance tracking',
        actions: [
          {
            id: 'attendance-list',
            name: 'View Attendance Records',
            type: 'view',
            description: 'View attendance records',
            icon: Eye,
          },
          {
            id: 'attendance-clock',
            name: 'Clock In/Out',
            type: 'process',
            description: 'Record clock in/out',
            icon: Clock,
          },
          {
            id: 'attendance-manual',
            name: 'Manual Entry',
            type: 'create',
            description: 'Manual attendance entry',
            icon: Edit,
          },
          {
            id: 'attendance-approve',
            name: 'Approve Attendance',
            type: 'approve',
            description: 'Approve attendance records',
            icon: Check,
          },
          {
            id: 'attendance-export',
            name: 'Export Attendance',
            type: 'export',
            description: 'Export attendance report',
            icon: Download,
          },
        ],
      },
      {
        id: 'leave-management',
        name: 'Leave Management',
        path: '/hr/leave-requests',
        description: 'Manage leave requests and balances',
        actions: [
          {
            id: 'leave-list',
            name: 'View Leave Requests',
            type: 'view',
            description: 'View all leave requests',
            icon: Eye,
          },
          {
            id: 'leave-create',
            name: 'Submit Leave Request',
            type: 'create',
            description: 'Submit new leave request',
            icon: Plus,
          },
          {
            id: 'leave-view-detail',
            name: 'View Leave Details',
            type: 'view',
            description: 'View leave request details',
            icon: Eye,
          },
          {
            id: 'leave-approve',
            name: 'Approve Leave',
            type: 'approve',
            description: 'Approve leave request',
            icon: Check,
          },
          {
            id: 'leave-reject',
            name: 'Reject Leave',
            type: 'reject',
            description: 'Reject leave request',
            icon: X,
          },
          {
            id: 'leave-balances',
            name: 'View Leave Balances',
            type: 'view',
            description: 'View staff leave balances',
            icon: BarChart3,
          },
          {
            id: 'leave-types',
            name: 'Leave Types Management',
            type: 'navigate',
            description: 'Configure leave types with rules',
            icon: Settings,
          },
          {
            id: 'leave-type-create',
            name: 'Create/Edit Leave Type',
            type: 'create',
            description: 'Create and configure leave types',
            icon: Plus,
          },
        ],
      },
      {
        id: 'payroll-management',
        name: 'Payroll Management',
        path: '/hr/payroll',
        description: 'Process payroll and generate payslips',
        actions: [
          {
            id: 'payroll-list',
            name: 'View Payroll Records',
            type: 'view',
            description: 'View payroll records',
            icon: Eye,
          },
          {
            id: 'payroll-view-detail',
            name: 'View Payroll Details',
            type: 'view',
            description: 'View detailed payroll information',
            icon: Eye,
          }, // ADD THIS
          {
            id: 'payroll-create',
            name: 'Create Payroll',
            type: 'create',
            description: 'Create new payroll',
            icon: Plus,
          },
          {
            id: 'payroll-calculate',
            name: 'Calculate Payroll',
            type: 'process',
            description: 'Calculate payroll amounts',
            icon: Calculator,
          },
          {
            id: 'payroll-approve',
            name: 'Approve Payroll',
            type: 'approve',
            description: 'Approve payroll for payment',
            icon: Check,
          },
          {
            id: 'payroll-process',
            name: 'Process Payroll',
            type: 'process',
            description: 'Process monthly payroll',
            icon: DollarSign,
          },
          {
            id: 'payroll-generate-payslips',
            name: 'Generate Payslips',
            type: 'export',
            description: 'Generate payslip documents',
            icon: Receipt,
          },
        ],
      },
      {
        id: 'salary-components',
        name: 'Salary Components',
        path: '/hr/salary-components',
        description: 'Manage salary components, allowances, and deductions',
        actions: [
          {
            id: 'salary-component-list',
            name: 'View Components',
            type: 'view',
            description: 'View salary components',
            icon: Eye,
          },
          {
            id: 'salary-component-create',
            name: 'Create Component',
            type: 'create',
            description: 'Create salary component',
            icon: Plus,
          },
          {
            id: 'salary-component-edit',
            name: 'Edit Component',
            type: 'edit',
            description: 'Edit salary component',
            icon: Edit,
          },
          {
            id: 'salary-component-delete',
            name: 'Delete Component',
            type: 'delete',
            description: 'Delete salary component',
            icon: Trash,
          },
        ],
      },
      {
        id: 'bonus-deductions',
        name: 'Bonus & Deduction Requests',
        path: '/hr/bonus-deduction',
        description: 'Manage bonus and deduction requests',
        actions: [
          {
            id: 'bonus-deduction-list',
            name: 'View Requests',
            type: 'view',
            description: 'View bonus/deduction requests',
            icon: Eye,
          },
          {
            id: 'bonus-deduction-create',
            name: 'Create Request',
            type: 'create',
            description: 'Create bonus/deduction request',
            icon: Plus,
          },
          {
            id: 'bonus-deduction-view-detail',
            name: 'View Request Detail',
            type: 'view',
            description: 'View detailed request information',
            icon: Eye,
          },
          {
            id: 'bonus-deduction-approve',
            name: 'Approve Request',
            type: 'approve',
            description: 'Approve bonus/deduction',
            icon: Check,
          },
          {
            id: 'bonus-deduction-reject',
            name: 'Reject Request',
            type: 'reject',
            description: 'Reject bonus/deduction',
            icon: X,
          },
        ],
      },
    ],
  },
  {
    id: 'expenses',
    name: 'Expenses & Resource Management',
    description: 'Expense tracking, prepaid expenses, resource consumption, and vouchers',
    pages: [
      {
        id: 'prepaid-expenses',
        name: 'Prepaid Expenses',
        path: '/expenses/prepaid',
        description: 'Manage prepaid expenses and amortization',
        actions: [
          {
            id: 'prepaid-list',
            name: 'View Prepaid Expenses',
            type: 'view',
            description: 'View all prepaid expenses',
            icon: Eye,
          },
          {
            id: 'prepaid-amortize',
            name: 'Process Amortization',
            type: 'process',
            description: 'Process monthly amortization',
            icon: Calculator,
          },
          {
            id: 'prepaid-create',
            name: 'Create Prepaid Expense',
            type: 'create',
            description: 'Create new prepaid expense',
            icon: Plus,
          },
        ],
      },
      {
        id: 'resource-consumption',
        name: 'Resource Consumption',
        path: '/expenses/resource-consumption',
        description: 'Track and manage resource consumption',
        actions: [
          {
            id: 'consumption-list',
            name: 'View Consumption',
            type: 'view',
            description: 'View resource consumption',
            icon: Eye,
          },
          {
            id: 'consumption-post-list',
            name: 'Post Consumption List',
            type: 'view',
            description: 'List of consumption records ready for posting',
            icon: Eye,
          },
          {
            id: 'consumption-approval-list',
            name: 'Approval Consumption List',
            type: 'view',
            description: 'List of consumption records ready for approval',
            icon: Eye,
          },
          {
            id: 'consumption-record',
            name: 'Record Consumption',
            type: 'create',
            description: 'Record resource usage',
            icon: Plus,
          },
          {
            id: 'consumption-post',
            name: 'Post Record',
            type: 'process',
            description: 'Post consumption data',
            icon: CheckSquare,
          },
          {
            id: 'consumption-submit-approval',
            name: 'Submit for Approval',
            type: 'process',
            description: 'Submit for approval',
            icon: Send,
          },
        ],
      },
      {
        id: 'irregularities',
        name: 'Irregularities Dashboard',
        path: '/expenses/resource-consumption/irregularities',
        description: 'Monitor consumption irregularities',
        actions: [
          {
            id: 'irregularities-view',
            name: 'View Irregularities',
            type: 'view',
            description: 'View reported irregularities',
            icon: AlertTriangle,
          },
        ],
      },
      {
        id: 'vouchers',
        name: 'Vouchers',
        path: '/expenses/vouchers',
        description: 'Expense voucher management',
        actions: [
          {
            id: 'voucher-list',
            name: 'View Vouchers',
            type: 'view',
            description: 'View all vouchers',
            icon: Eye,
          },
          {
            id: 'voucher-create',
            name: 'Create Voucher',
            type: 'create',
            description: 'Create new voucher',
            icon: Plus,
          },
          {
            id: 'voucher-view-detail',
            name: 'View Voucher Details',
            type: 'view',
            description: 'View voucher details',
            icon: Eye,
          },
          {
            id: 'voucher-cancel',
            name: 'Cancel Voucher',
            type: 'process',
            description: 'Cancel a voucher',
            icon: Calculator,
          },
        ],
      },
    ],
  },
  {
    id: 'financial-reports',
    name: 'Financial Reports',
    description: 'Financial reporting and analysis',
    pages: [
      {
        id: 'trial-balance',
        name: 'Trial Balance Report',
        path: '/reports/financial/trial-balance',
        description: 'Generate trial balance',
        actions: [
          {
            id: 'trial-balance-view',
            name: 'View Trial Balance',
            type: 'view',
            description: 'Generate trial balance',
            icon: Eye,
          },
        ],
      },
      {
        id: 'profit-loss',
        name: 'Profit & Loss Statement',
        path: '/reports/financial/profit-loss',
        description: 'Generate P&L report',
        actions: [
          {
            id: 'pl-view',
            name: 'View P&L Statement',
            type: 'view',
            description: 'Generate P&L report',
            icon: Eye,
          },
        ],
      },
      {
        id: 'balance-sheet',
        name: 'Balance Sheet Report',
        path: '/reports/financial/balance-sheet',
        description: 'Generate balance sheet',
        actions: [
          {
            id: 'balance-sheet-view',
            name: 'View Balance Sheet',
            type: 'view',
            description: 'Generate balance sheet',
            icon: Eye,
          },
        ],
      },
      // Add Chart of Accounts here
      {
        id: 'chart-of-accounts',
        name: 'Chart of Accounts',
        path: '/accounts',
        description: 'Manage chart of accounts',
        actions: [
          {
            id: 'accounts-view',
            name: 'View Chart of Accounts',
            type: 'view',
            description: 'View chart of accounts',
            icon: Eye,
          },
          {
            id: 'accounts-create',
            name: 'Create Account',
            type: 'create',
            description: 'Create new account',
            icon: Plus,
          },
          {
            id: 'accounts-edit',
            name: 'Edit Account',
            type: 'edit',
            description: 'Edit existing account',
            icon: Edit,
          },
          {
            id: 'accounts-delete',
            name: 'Delete Account',
            type: 'delete',
            description: 'Delete account',
            icon: Trash2,
          },
        ],
      },
    ],
  },

  {
    id: 'client-management',
    name: 'Client Management',
    description: 'Customer and client management',
    pages: [
      {
        id: 'clients',
        name: 'Clients',
        path: '/clients',
        description: 'Manage client information',
        actions: [
          {
            id: 'client-list',
            name: 'View Clients',
            type: 'view',
            description: 'View all clients',
            icon: Eye,
          },
          {
            id: 'client-create',
            name: 'Create Client',
            type: 'create',
            description: 'Add new client',
            icon: Plus,
          },
          {
            id: 'client-view-detail',
            name: 'View Client Details',
            type: 'view',
            description: 'View client details',
            icon: Eye,
          },
          {
            id: 'client-edit',
            name: 'Edit Client',
            type: 'edit',
            description: 'Edit client information',
            icon: Edit,
          },
          {
            id: 'client-bulk-import',
            name: 'Bulk Import',
            type: 'import',
            description: 'Import multiple clients',
            icon: Upload,
          },
          {
            id: 'client-export',
            name: 'Export Clients',
            type: 'export',
            description: 'Export client list',
            icon: Download,
          },
        ],
      },
      {
        id: 'client-classifications',
        name: 'Client Classifications',
        path: '/clients/classifications',
        description: 'Manage client categories',
        actions: [
          {
            id: 'classification-list',
            name: 'View Classifications',
            type: 'view',
            description: 'View client classifications',
            icon: Eye,
          },
          {
            id: 'classification-create',
            name: 'Create Classification',
            type: 'create',
            description: 'Create new classification',
            icon: Plus,
          },
          {
            id: 'classification-edit',
            name: 'Edit Classification',
            type: 'edit',
            description: 'Edit classification',
            icon: Edit,
          },
          {
            id: 'classification-delete',
            name: 'Delete Classification',
            type: 'delete',
            description: 'Delete classification',
            icon: Trash2,
          },
        ],
      },
    ],
  },
  {
    id: 'admin-management',
    name: 'Admin Management',
    description: 'System administration and configuration',
    pages: [
      {
        id: 'branch-management',
        name: 'Branches',
        path: '/admin/branches',
        description: 'Manage branches',
        actions: [
          {
            id: 'branch-list',
            name: 'View Branches',
            type: 'view',
            description: 'View all branches',
            icon: Eye,
          },
          {
            id: 'branch-create',
            name: 'Create Branch',
            type: 'create',
            description: 'Add new branch',
            icon: Plus,
          },
          {
            id: 'branch-view-detail',
            name: 'View Branch Details',
            type: 'view',
            description: 'View branch details',
            icon: Eye,
          },
          {
            id: 'branch-edit',
            name: 'Edit Branch',
            type: 'edit',
            description: 'Edit branch details',
            icon: Edit,
          },
        ],
      },
      {
        id: 'user-management',
        name: 'User Management',
        path: '/admin/users',
        description: 'Manage users, roles, and permissions',
        actions: [
          // User actions
          {
            id: 'user-list',
            name: 'View Users',
            type: 'view',
            description: 'View all users',
            icon: Eye,
          },
          {
            id: 'user-create',
            name: 'Create User',
            type: 'create',
            description: 'Add new user',
            icon: Plus,
          },
          {
            id: 'user-view-detail',
            name: 'View User Details',
            type: 'view',
            description: 'View user details',
            icon: Eye,
          },
          {
            id: 'user-edit',
            name: 'Edit User',
            type: 'edit',
            description: 'Edit user information',
            icon: Edit,
          },
          {
            id: 'user-delete',
            name: 'Delete User',
            type: 'delete',
            description: 'Delete user',
            icon: Trash2,
          },
          {
            id: 'user-toggle-status',
            name: 'Activate/Deactivate User',
            type: 'process',
            description: 'Toggle user active status',
            icon: CheckCircle,
          },

          // Role actions
          {
            id: 'role-list',
            name: 'View Roles',
            type: 'view',
            description: 'View all roles',
            icon: Eye,
          },
          {
            id: 'role-create',
            name: 'Create Role',
            type: 'create',
            description: 'Add new role',
            icon: Plus,
          },
          {
            id: 'role-edit',
            name: 'Edit Role',
            type: 'edit',
            description: 'Edit role information',
            icon: Edit,
          },
          {
            id: 'role-delete',
            name: 'Delete Role',
            type: 'delete',
            description: 'Delete role',
            icon: Trash2,
          },

          // Permission actions
          {
            id: 'permission-manage',
            name: 'Manage Permissions',
            type: 'process',
            description: 'Edit role permissions',
            icon: Settings,
          },
          {
            id: 'permission-view',
            name: 'View Permissions',
            type: 'view',
            description: 'View role permissions',
            icon: Eye,
          },
        ],
      },
    ],
  },
];
