/**
 * routeToPageMap.ts
 *
 * Mechanical join between every route path in App.tsx and the new
 * module:page permission taxonomy defined in permissionRegistry.ts.
 *
 * Consumed by:
 *   - ProtectedRoute migration (replaces legacy requiredPermission strings)
 *   - Nav unification (roleSidebarConfig / featureRegistry)
 *
 * Action is inferred from the path shape (bare/:id -> 'view', /new or /create
 * -> 'create', /:id/edit -> 'edit', /approve or /approvals -> 'approve') and
 * cross-checked against the original legacy requiredPermission suffix where it
 * disambiguates.
 *
 * Do not hand-edit path ordering; regenerate from App.tsx if routes change.
 */
import { PAGE_REGISTRY_MAP } from './permissionRegistry';

export interface RouteMapping {
  module: string;
  page: string;
  action: 'view' | 'create' | 'edit' | 'delete' | 'approve' | 'export';
}

export const ROUTE_TO_PAGE: Record<string, RouteMapping> = {
  '/accounting/journal-vouchers': { module: 'accounts', page: 'chart-of-accounts', action: 'view' },
  '/accounting/journal-vouchers/:id': { module: 'accounts', page: 'chart-of-accounts', action: 'view' },
  '/accounting/journal-vouchers/create': { module: 'accounts', page: 'chart-of-accounts', action: 'create' },
  '/accounting/periods': { module: 'accounts', page: 'chart-of-accounts', action: 'view' },
  '/accounts': { module: 'accounts', page: 'chart-of-accounts', action: 'view' },
  '/accounts-payable': { module: 'liabilities', page: 'accounts-payable', action: 'view' },
  '/accounts/:accountId/ledger': { module: 'accounts', page: 'account-ledger', action: 'view' },
  '/accounts/:accountId/summary': { module: 'accounts', page: 'account-summary', action: 'view' },
  '/accounts/hierarchy': { module: 'accounts', page: 'account-hierarchy', action: 'view' },
  // LedgerSearchPage calls GET /accounts/ (AccountViewSet), which the backend
  // gates by accounts:chart-of-accounts (accounts/views.py) — not a dedicated
  // accounts:ledger-search endpoint, despite that being a distinct registry
  // entry. Mapped to chart-of-accounts here so visibility actually matches
  // what the underlying data call requires; previously a user could see/open
  // this card while still 403'ing on load if their ledger-search and
  // chart-of-accounts grants differed.
  '/accounts/ledger-search': { module: 'accounts', page: 'chart-of-accounts', action: 'view' },
  '/accounts/new': { module: 'accounts', page: 'chart-of-accounts', action: 'create' },
  '/admin/access-control': { module: 'users', page: 'staff-users', action: 'view' },
  '/admin/branches': { module: 'branches', page: 'branches', action: 'view' },
  '/admin/branches/:id/view': { module: 'branches', page: 'branches', action: 'view' },
  '/admin/branches/create': { module: 'branches', page: 'branches', action: 'create' },
  '/admin/close-year': { module: 'common', page: 'business-day', action: 'edit' },
  '/admin/dashboard-assignment': { module: 'users', page: 'staff-users', action: 'view' },
  '/admin/dashboard-builder/:templateId?': { module: 'users', page: 'staff-users', action: 'view' },
  '/admin/forms': { module: 'automations', page: 'forms', action: 'edit' },
  '/admin/permission-elevation-log': { module: 'permissions', page: 'user-permission-overrides', action: 'view' },
  '/admin/permission-exceptions': { module: 'permissions', page: 'user-permission-overrides', action: 'view' },
  '/admin/permission-setup': { module: 'permissions', page: 'role-permission-policies', action: 'edit' },
  '/admin/permissions-matrix': { module: 'permissions', page: 'role-permission-policies', action: 'view' },
  '/admin/review-week': { module: 'common', page: 'business-day', action: 'edit' },
  '/admin/scheduled-jobs': { module: 'common', page: 'business-day', action: 'edit' },
  '/admin/submissions': { module: 'automations', page: 'forms', action: 'view' },
  '/admin/tenants': { module: 'tenants', page: 'tenants', action: 'view' },
  '/admin/tenants/:id/edit': { module: 'tenants', page: 'tenants', action: 'edit' },
  '/admin/tenants/:id/view': { module: 'tenants', page: 'tenants', action: 'view' },
  '/admin/tenants/create': { module: 'tenants', page: 'tenants', action: 'create' },
  '/admin/transaction-reversal': { module: 'common', page: 'business-day', action: 'edit' },
  '/admin/user-overrides': { module: 'permissions', page: 'user-permission-overrides', action: 'edit' },
  '/admin/users': { module: 'users', page: 'staff-users', action: 'view' },
  '/admin/workflows': { module: 'automations', page: 'workflow-templates', action: 'view' },
  '/admin/workflows/:workflowId': { module: 'automations', page: 'workflow-templates', action: 'edit' },
  '/admin/workflows/new': { module: 'automations', page: 'workflow-templates', action: 'create' },
  '/administration': { module: 'users', page: 'staff-users', action: 'view' },
  '/all-access': { module: 'users', page: 'staff-users', action: 'view' },
  '/approvals': { module: 'automations', page: 'workflow-approvals', action: 'view' },
  '/approvals/pending': { module: 'automations', page: 'workflow-approvals', action: 'view' },
  '/approvals/workflow': { module: 'automations', page: 'workflow-approvals', action: 'approve' },
  '/assets': { module: 'assets', page: 'fixed-assets', action: 'view' },
  '/assets/:id': { module: 'assets', page: 'fixed-assets', action: 'view' },
  '/assets/:id/dispose': { module: 'assets', page: 'fixed-assets', action: 'edit' },
  '/assets/:id/edit': { module: 'assets', page: 'fixed-assets', action: 'edit' },
  '/assets/acquisitions': { module: 'assets', page: 'fixed-assets', action: 'view' },
  '/assets/acquisitions/:id': { module: 'assets', page: 'fixed-assets', action: 'view' },
  '/assets/acquisitions/new': { module: 'assets', page: 'fixed-assets', action: 'create' },
  '/assets/categories': { module: 'assets', page: 'asset-categories', action: 'view' },
  '/assets/categories/:id/edit': { module: 'assets', page: 'asset-categories', action: 'edit' },
  '/assets/categories/create': { module: 'assets', page: 'asset-categories', action: 'create' },
  '/assets/depreciation': { module: 'assets', page: 'asset-depreciation', action: 'view' },
  '/assets/depreciation/run': { module: 'assets', page: 'asset-depreciation', action: 'edit' },
  '/assets/dispose': { module: 'assets', page: 'fixed-assets', action: 'edit' },
  '/assets/fuel-monitor': { module: 'assets', page: 'asset-fuel-monitor', action: 'view' },
  '/assets/maintenance': { module: 'assets', page: 'asset-maintenance', action: 'view' },
  '/assets/maintenance/:id': { module: 'assets', page: 'asset-maintenance', action: 'view' },
  '/assets/maintenance/new': { module: 'assets', page: 'asset-maintenance', action: 'create' },
  '/assets/purchases': { module: 'assets', page: 'fixed-assets', action: 'view' },
  '/assets/purchases/:id': { module: 'assets', page: 'fixed-assets', action: 'view' },
  '/assets/purchases/new': { module: 'assets', page: 'fixed-assets', action: 'create' },
  '/assets/register': { module: 'assets', page: 'fixed-assets', action: 'create' },
  '/automations/approvals/:id': { module: 'automations', page: 'workflow-approvals', action: 'approve' },
  '/automations/approvals/history': { module: 'automations', page: 'workflow-approvals', action: 'view' },
  '/automations/run/:templateId': { module: 'automations', page: 'workflow-runs', action: 'create' },
  '/automations/runs': { module: 'automations', page: 'workflow-runs', action: 'view' },
  '/automations/runs/:id': { module: 'automations', page: 'workflow-runs', action: 'view' },
  '/automations/runs/:id/logs': { module: 'automations', page: 'workflow-runs', action: 'view' },
  '/automations/templates': { module: 'automations', page: 'workflow-templates', action: 'view' },
  '/automations/templates/:id/edit': { module: 'automations', page: 'workflow-templates', action: 'edit' },
  '/automations/templates/:id/view': { module: 'automations', page: 'workflow-templates', action: 'view' },
  '/automations/templates/create': { module: 'automations', page: 'workflow-templates', action: 'create' },
  '/banks': { module: 'banks', page: 'banks', action: 'view' },
  '/banks/:id': { module: 'banks', page: 'banks', action: 'view' },
  '/banks/:id/edit': { module: 'banks', page: 'banks', action: 'edit' },
  '/banks/accounts': { module: 'banks', page: 'bank-accounts', action: 'view' },
  '/banks/accounts/:id': { module: 'banks', page: 'bank-accounts', action: 'view' },
  '/banks/accounts/:id/edit': { module: 'banks', page: 'bank-accounts', action: 'edit' },
  '/banks/accounts/new': { module: 'banks', page: 'bank-accounts', action: 'create' },
  '/banks/new': { module: 'banks', page: 'banks', action: 'create' },
  '/banks/payments': { module: 'banks', page: 'bank-payments', action: 'view' },
  '/banks/payments/new': { module: 'banks', page: 'bank-payments', action: 'create' },
  '/banks/reconciliations': { module: 'banks', page: 'bank-statement-reconciliation', action: 'view' },
  '/banks/reconciliations/new': { module: 'banks', page: 'bank-statement-reconciliation', action: 'create' },
  '/banks/reconciliations/:id': { module: 'banks', page: 'bank-statement-reconciliation', action: 'view' },
  '/banks/transfers': { module: 'banks', page: 'bank-transfers', action: 'view' },
  '/banks/transfers/approvals': { module: 'banks', page: 'bank-transfers', action: 'approve' },
  '/banks/transfers/new': { module: 'banks', page: 'bank-transfers', action: 'create' },
  '/budgets/periods': { module: 'budgets', page: 'budget-periods', action: 'view' },
  '/budgets/periods/:id': { module: 'budgets', page: 'budget-periods', action: 'view' },
  '/budgets/periods/:id/edit': { module: 'budgets', page: 'budget-periods', action: 'edit' },
  '/budgets/periods/:id/variance': { module: 'budgets', page: 'budget-periods', action: 'export' },
  '/budgets/periods/new': { module: 'budgets', page: 'budget-periods', action: 'create' },
  '/business-day': { module: 'common', page: 'business-day', action: 'edit' },
  '/cash-management/collection-sheets': { module: 'cash-management', page: 'collection-sheets', action: 'view' },
  '/cash-management/collection-sheets/:sheetId': { module: 'cash-management', page: 'collection-sheets', action: 'view' },
  '/client-services': { module: 'clients', page: 'client-services', action: 'view' },
  '/clients': { module: 'clients', page: 'clients', action: 'view' },
  '/clients/:clientId/ledger': { module: 'clients', page: 'clients', action: 'view' },
  '/clients/:id': { module: 'clients', page: 'clients', action: 'view' },
  '/clients/:id/edit': { module: 'clients', page: 'clients', action: 'edit' },
  '/clients/:id/statement': { module: 'clients', page: 'clients', action: 'view' },
  '/clients/classifications': { module: 'clients', page: 'client-classifications', action: 'view' },
  '/clients/classifications/:id/edit': { module: 'clients', page: 'client-classifications', action: 'edit' },
  '/clients/classifications/create': { module: 'clients', page: 'client-classifications', action: 'create' },
  '/clients/create': { module: 'clients', page: 'clients', action: 'create' },
  '/clients/groups': { module: 'clients', page: 'client-groups', action: 'view' },
  '/clients/import': { module: 'clients', page: 'clients', action: 'create' },
  '/clients/reactivate': { module: 'clients', page: 'prospects', action: 'edit' },
  '/clients/registration-config': { module: 'clients', page: 'clients', action: 'edit' },
  '/clients/school-fees-import': { module: 'clients', page: 'clients', action: 'create' },
  '/collections/dashboard': { module: 'receivables', page: 'customer-receivables', action: 'view' },
  '/dashboard': { module: 'dashboards', page: 'dashboards', action: 'view' },
  '/dashboard/:dashboardId': { module: 'dashboards', page: 'dashboards', action: 'view' },
  '/dashboard/:dashboardId/edit': { module: 'dashboards', page: 'dashboards', action: 'edit' },
  '/dashboard/create': { module: 'dashboards', page: 'dashboards', action: 'create' },
  '/dashboard/debug': { module: 'dashboards', page: 'dashboards', action: 'view' },
  '/dashboard/demo': { module: 'dashboards', page: 'dashboards', action: 'view' },
  '/dashboard/role-based': { module: 'dashboards', page: 'dashboards', action: 'view' },
  '/dashboard/select': { module: 'dashboards', page: 'dashboards', action: 'view' },
  '/dashboard/settings': { module: 'dashboards', page: 'dashboards', action: 'view' },
  '/dashboard/workflow-centric': { module: 'dashboards', page: 'dashboards', action: 'view' },
  '/discounts/analytics': { module: 'discounts', page: 'applied-discounts', action: 'view' },
  '/discounts/applications': { module: 'discounts', page: 'discount-applications', action: 'view' },
  '/discounts/applications/:id': { module: 'discounts', page: 'discount-applications', action: 'view' },
  '/discounts/applications/new': { module: 'discounts', page: 'discount-applications', action: 'create' },
  '/discounts/applied': { module: 'discounts', page: 'applied-discounts', action: 'view' },
  '/discounts/apply': { module: 'discounts', page: 'applied-discounts', action: 'view' },
  '/discounts/auto-apply': { module: 'discounts', page: 'applied-discounts', action: 'view' },
  '/discounts/programs': { module: 'discounts', page: 'discount-programs', action: 'view' },
  '/discounts/programs/:id': { module: 'discounts', page: 'discount-programs', action: 'view' },
  '/discounts/programs/:id/edit': { module: 'discounts', page: 'discount-programs', action: 'edit' },
  '/discounts/programs/create': { module: 'discounts', page: 'discount-programs', action: 'create' },
  '/expenses': { module: 'expenses', page: 'expenses', action: 'view' },
  '/expenses/:id': { module: 'expenses', page: 'expenses', action: 'view' },
  '/expenses/:id/edit': { module: 'expenses', page: 'expenses', action: 'edit' },
  '/expenses/categories': { module: 'expenses', page: 'expense-categories', action: 'view' },
  '/expenses/categories/:id/edit': { module: 'expenses', page: 'expense-categories', action: 'edit' },
  '/expenses/categories/create': { module: 'expenses', page: 'expense-categories', action: 'create' },
  '/expenses/create': { module: 'expenses', page: 'expenses', action: 'create' },
  '/expenses/fuel-log/create': { module: 'expenses', page: 'resource-consumption', action: 'create' },
  '/expenses/prepaid': { module: 'expenses', page: 'prepaid-vouchers', action: 'view' },
  '/expenses/prepaid/:id': { module: 'expenses', page: 'prepaid-vouchers', action: 'view' },
  '/expenses/prepaid/:id/amortize': { module: 'expenses', page: 'prepaid-vouchers', action: 'edit' },
  '/expenses/prepaid/:id/edit': { module: 'expenses', page: 'prepaid-vouchers', action: 'edit' },
  '/expenses/prepaid/create': { module: 'expenses', page: 'prepaid-vouchers', action: 'create' },
  '/expenses/resource-consumption': { module: 'expenses', page: 'resource-consumption', action: 'view' },
  '/expenses/resource-consumption/:id': { module: 'expenses', page: 'resource-consumption', action: 'view' },
  '/expenses/resource-consumption/:id/approve': { module: 'expenses', page: 'resource-consumption', action: 'approve' },
  '/expenses/resource-consumption/:id/edit': { module: 'expenses', page: 'resource-consumption', action: 'edit' },
  '/expenses/resource-consumption/:id/post': { module: 'expenses', page: 'resource-consumption', action: 'edit' },
  '/expenses/resource-consumption/approval-queue': { module: 'expenses', page: 'resource-consumption', action: 'approve' },
  '/expenses/resource-consumption/create': { module: 'expenses', page: 'resource-consumption', action: 'create' },
  '/expenses/resource-consumption/fuel-report': { module: 'expenses', page: 'resource-consumption', action: 'export' },
  '/expenses/resource-consumption/irregularities': { module: 'expenses', page: 'resource-consumption', action: 'view' },
  '/expenses/resource-consumption/posting-queue': { module: 'expenses', page: 'resource-consumption', action: 'edit' },
  '/expenses/resources': { module: 'expenses', page: 'resources', action: 'view' },
  '/expenses/resources/:id': { module: 'expenses', page: 'resources', action: 'view' },
  '/expenses/resources/:id/edit': { module: 'expenses', page: 'resources', action: 'edit' },
  '/expenses/resources/create': { module: 'expenses', page: 'resources', action: 'create' },
  '/expenses/vouchers': { module: 'expenses', page: 'expenses', action: 'view' },
  '/expenses/vouchers/:id': { module: 'expenses', page: 'expenses', action: 'view' },
  '/expenses/vouchers/:id/edit': { module: 'expenses', page: 'expenses', action: 'edit' },
  '/expenses/vouchers/create': { module: 'expenses', page: 'expenses', action: 'create' },
  '/expenses/vouchers/expiring': { module: 'expenses', page: 'expenses', action: 'view' },
  '/fee/invoices/create': { module: 'incomes', page: 'invoices', action: 'create' },
  '/financial-management': { module: 'accounts', page: 'financial-management', action: 'view' },
  '/fixed-asset': { module: 'assets', page: 'fixed-assets', action: 'view' },
  '/forms': { module: 'automations', page: 'forms', action: 'view' },
  '/forms/:formId': { module: 'automations', page: 'forms', action: 'view' },
  '/forms/submissions': { module: 'automations', page: 'forms', action: 'view' },
  '/hr': { module: 'hr', page: 'staff', action: 'view' },
  '/hr/attendance': { module: 'hr', page: 'attendance', action: 'view' },
  '/hr/attendance/:id/edit': { module: 'hr', page: 'attendance', action: 'edit' },
  '/hr/attendance/:id/view': { module: 'hr', page: 'attendance', action: 'view' },
  '/hr/attendance/create': { module: 'hr', page: 'attendance', action: 'create' },
  '/hr/bonus-deduction': { module: 'hr', page: 'bonus-deductions', action: 'view' },
  '/hr/bonus-deduction/:id/edit': { module: 'hr', page: 'bonus-deductions', action: 'edit' },
  '/hr/bonus-deduction/:id/view': { module: 'hr', page: 'bonus-deductions', action: 'view' },
  '/hr/bonus-deduction/create': { module: 'hr', page: 'bonus-deductions', action: 'create' },
  '/hr/clock': { module: 'hr', page: 'attendance', action: 'create' },
  '/hr/config': { module: 'hr', page: 'hr-config', action: 'edit' },
  '/hr/dashboard': { module: 'hr', page: 'staff', action: 'view' },
  '/hr/ious': { module: 'hr', page: 'staff-ious', action: 'view' },
  '/hr/ious/:id/view': { module: 'hr', page: 'staff-ious', action: 'view' },
  '/hr/ious/bulk-debit': { module: 'hr', page: 'staff-ious', action: 'create' },
  '/hr/ious/create': { module: 'hr', page: 'staff-ious', action: 'create' },
  '/hr/leave-balances': { module: 'hr', page: 'leave-balances', action: 'view' },
  '/hr/leave-calendar': { module: 'hr', page: 'leave-calendar', action: 'view' },
  '/hr/leave-requests': { module: 'hr', page: 'leave-requests', action: 'view' },
  '/hr/leave-requests/:id/edit': { module: 'hr', page: 'leave-requests', action: 'edit' },
  '/hr/leave-requests/:id/view': { module: 'hr', page: 'leave-requests', action: 'view' },
  '/hr/leave-requests/create': { module: 'hr', page: 'leave-requests', action: 'create' },
  '/hr/leave-types': { module: 'hr', page: 'leave-types', action: 'view' },
  '/hr/leave-types/:id/edit': { module: 'hr', page: 'leave-types', action: 'edit' },
  '/hr/leave-types/create': { module: 'hr', page: 'leave-types', action: 'create' },
  '/hr/pay-component-removals': { module: 'hr', page: 'staff-pay-info', action: 'view' },
  '/hr/payroll': { module: 'hr', page: 'payroll', action: 'view' },
  '/hr/payroll-schedules': { module: 'hr', page: 'payroll', action: 'view' },
  '/hr/payroll-schedules/:id/edit': { module: 'hr', page: 'payroll', action: 'edit' },
  '/hr/payroll-schedules/new': { module: 'hr', page: 'payroll', action: 'create' },
  '/hr/payroll/:id/edit': { module: 'hr', page: 'payroll', action: 'edit' },
  '/hr/payroll/:id/view': { module: 'hr', page: 'payroll', action: 'view' },
  '/hr/payroll/create': { module: 'hr', page: 'payroll', action: 'create' },
  '/hr/payslips': { module: 'hr', page: 'payslips', action: 'view' },
  '/hr/payslips/:id': { module: 'hr', page: 'payslips', action: 'view' },
  '/hr/pension-remittances': { module: 'hr', page: 'payroll', action: 'view' },
  '/hr/salary-components': { module: 'hr', page: 'salary-components', action: 'view' },
  '/hr/salary-components/:id/edit': { module: 'hr', page: 'salary-components', action: 'edit' },
  '/hr/salary-components/new': { module: 'hr', page: 'salary-components', action: 'create' },
  '/hr/self-service': { module: 'hr', page: 'staff', action: 'view' },
  '/hr/staff': { module: 'hr', page: 'staff', action: 'view' },
  '/hr/staff/:id/edit': { module: 'hr', page: 'staff', action: 'edit' },
  '/hr/staff/:id/view': { module: 'hr', page: 'staff', action: 'view' },
  '/hr/staff/:staffId/documents': { module: 'hr', page: 'staff', action: 'view' },
  '/hr/staff/:staffId/pay-components': { module: 'hr', page: 'staff-pay-info', action: 'edit' },
  '/hr/staff/create': { module: 'hr', page: 'staff', action: 'create' },
  '/hr/staff/import': { module: 'hr', page: 'staff', action: 'create' },
  '/incomes/categories': { module: 'incomes', page: 'income-categories', action: 'view' },
  '/incomes/entitlements': { module: 'incomes', page: 'fee-entitlements', action: 'view' },
  '/incomes/entitlements/:id/edit': { module: 'incomes', page: 'fee-entitlements', action: 'edit' },
  '/incomes/entitlements/:id/view': { module: 'incomes', page: 'fee-entitlements', action: 'view' },
  '/incomes/entitlements/create': { module: 'incomes', page: 'fee-entitlements', action: 'create' },
  '/incomes/entitlements/dashboard': { module: 'incomes', page: 'fee-entitlements', action: 'view' },
  '/incomes/fee-structures': { module: 'incomes', page: 'fee-structures', action: 'view' },
  '/incomes/fee-structures/:id/edit': { module: 'incomes', page: 'fee-structures', action: 'edit' },
  '/incomes/fee-structures/:id/view': { module: 'incomes', page: 'fee-structures', action: 'view' },
  '/incomes/fee-structures/approvals': { module: 'incomes', page: 'fee-structures', action: 'view' },
  '/incomes/fee-structures/create': { module: 'incomes', page: 'fee-structures', action: 'create' },
  '/incomes/financial-periods': { module: 'incomes', page: 'academic-years', action: 'view' },
  '/incomes/invoices/batch-review': { module: 'incomes', page: 'invoices', action: 'view' },
  '/incomes/service-items': { module: 'incomes', page: 'service-items', action: 'view' },
  '/incomes/setup/fee-structure': { module: 'incomes', page: 'fee-structures', action: 'view' },
  '/inventory': { module: 'inventory', page: 'inventory-items', action: 'view' },
  '/inventory/adjustments': { module: 'inventory', page: 'stock-adjustments', action: 'view' },
  '/inventory/adjustments/:id': { module: 'inventory', page: 'stock-adjustments', action: 'view' },
  '/inventory/adjustments/create': { module: 'inventory', page: 'stock-adjustments', action: 'create' },
  '/inventory/allocations': { module: 'inventory', page: 'allocations', action: 'view' },
  '/inventory/allocations/:id': { module: 'inventory', page: 'allocations', action: 'view' },
  '/inventory/initial-stock-import': { module: 'inventory', page: 'inventory-items', action: 'create' },
  '/inventory/items': { module: 'inventory', page: 'inventory-items', action: 'view' },
  '/inventory/items/:id/edit': { module: 'inventory', page: 'inventory-items', action: 'edit' },
  '/inventory/items/:id/ledger': { module: 'inventory', page: 'inventory-items', action: 'view' },
  '/inventory/items/:id/view': { module: 'inventory', page: 'inventory-items', action: 'view' },
  '/inventory/items/create': { module: 'inventory', page: 'inventory-items', action: 'create' },
  '/inventory/locations': { module: 'inventory', page: 'locations', action: 'view' },
  '/inventory/material-requests': { module: 'inventory', page: 'material-requests', action: 'view' },
  '/inventory/material-requests/:id': { module: 'inventory', page: 'material-requests', action: 'view' },
  '/inventory/material-requests/create': { module: 'inventory', page: 'material-requests', action: 'create' },
  '/inventory/movements': { module: 'inventory', page: 'stock-movements', action: 'view' },
  '/inventory/office-use-requests': { module: 'inventory', page: 'office-use-requests', action: 'view' },
  '/inventory/office-use-requests/:id': { module: 'inventory', page: 'office-use-requests', action: 'view' },
  '/inventory/office-use-requests/create': { module: 'inventory', page: 'office-use-requests', action: 'create' },
  '/inventory/physical-counts': { module: 'inventory', page: 'physical-counts', action: 'view' },
  '/inventory/physical-counts/:id': { module: 'inventory', page: 'physical-counts', action: 'view' },
  '/inventory/physical-counts/new': { module: 'inventory', page: 'physical-counts', action: 'create' },
  '/inventory/redemptions': { module: 'inventory', page: 'allocation-redemptions', action: 'view' },
  '/inventory/reorder-alerts': { module: 'inventory', page: 'pending-approvals', action: 'view' },
  '/inventory/reports/valuation': { module: 'inventory', page: 'stock-valuation', action: 'export' },
  '/inventory/sales-orders': { module: 'inventory', page: 'sales-orders', action: 'view' },
  '/inventory/sales-orders/:id': { module: 'inventory', page: 'sales-orders', action: 'view' },
  '/inventory/sales-orders/new': { module: 'inventory', page: 'sales-orders', action: 'create' },
  '/inventory/tracker': { module: 'inventory', page: 'stock-movements', action: 'view' },
  '/inventory/transfers': { module: 'inventory', page: 'stock-transfers', action: 'view' },
  '/inventory/transfers/:id': { module: 'inventory', page: 'stock-transfers', action: 'view' },
  '/inventory/transfers/create': { module: 'inventory', page: 'stock-transfers', action: 'create' },
  '/inventory/write-offs': { module: 'inventory', page: 'write-offs', action: 'view' },
  '/inventory/write-offs/new': { module: 'inventory', page: 'write-offs', action: 'create' },
  '/invoices/create': { module: 'incomes', page: 'invoices', action: 'create' },
  '/liabilities/matching': { module: 'liabilities', page: 'accounts-payable', action: 'view' },
  '/liabilities/payables': { module: 'liabilities', page: 'accounts-payable', action: 'view' },
  '/liabilities/payables/:id': { module: 'liabilities', page: 'accounts-payable', action: 'view' },
  '/liabilities/payables/new': { module: 'liabilities', page: 'accounts-payable', action: 'create' },
  '/liabilities/vendors': { module: 'liabilities', page: 'accounts-payable', action: 'view' },
  '/loans/accounts': { module: 'loans', page: 'loan-accounts', action: 'view' },
  '/loans/accounts/:id': { module: 'loans', page: 'loan-accounts', action: 'view' },
  '/loans/accounts/create': { module: 'loans', page: 'loan-accounts', action: 'create' },
  '/loans/collection': { module: 'loans', page: 'loan-collection', action: 'view' },
  '/loans/disbursements': { module: 'loans', page: 'loan-disbursements', action: 'view' },
  '/loans/disbursements/:loanId': { module: 'loans', page: 'loan-disbursements', action: 'create' },
  '/loans/products': { module: 'loans', page: 'loan-products', action: 'view' },
  '/loans/products/:id/config': { module: 'loans', page: 'loan-products', action: 'edit' },
  '/loans/repayment-approvals': { module: 'loans', page: 'loan-repayment-approvals', action: 'approve' },
  '/loans/verification': { module: 'loans', page: 'loan-verification', action: 'view' },
  '/loans/verification/:loanId': { module: 'loans', page: 'loan-verification', action: 'view' },
  '/newpages': { module: 'pages', page: 'pages', action: 'view' },
  '/petty-cash': { module: 'cash-management', page: 'petty-cash-funds', action: 'view' },
  '/procurement': { module: 'procurement', page: 'purchase-requisitions', action: 'view' },
  '/procurement/grn': { module: 'procurement', page: 'goods-received', action: 'view' },
  '/procurement/grn/:id/quality-check': { module: 'procurement', page: 'goods-received', action: 'edit' },
  '/procurement/grn/:id/view': { module: 'procurement', page: 'goods-received', action: 'view' },
  '/procurement/grn/create': { module: 'procurement', page: 'goods-received', action: 'create' },
  '/procurement/orders': { module: 'procurement', page: 'purchase-orders', action: 'view' },
  '/procurement/orders/:id/edit': { module: 'procurement', page: 'purchase-orders', action: 'edit' },
  '/procurement/orders/:id/view': { module: 'procurement', page: 'purchase-orders', action: 'view' },
  '/procurement/orders/create': { module: 'procurement', page: 'purchase-orders', action: 'create' },
  '/procurement/quotes': { module: 'procurement', page: 'supplier-quotes', action: 'view' },
  '/procurement/quotes/:id': { module: 'procurement', page: 'supplier-quotes', action: 'view' },
  '/procurement/quotes/:id/edit': { module: 'procurement', page: 'supplier-quotes', action: 'edit' },
  '/procurement/quotes/:id/view': { module: 'procurement', page: 'supplier-quotes', action: 'view' },
  '/procurement/quotes/compare/:requisitionId': { module: 'procurement', page: 'supplier-quotes', action: 'view' },
  '/procurement/quotes/new': { module: 'procurement', page: 'supplier-quotes', action: 'create' },
  '/procurement/requisitions': { module: 'procurement', page: 'purchase-requisitions', action: 'view' },
  '/procurement/requisitions/:id/edit': { module: 'procurement', page: 'purchase-requisitions', action: 'edit' },
  '/procurement/requisitions/:id/view': { module: 'procurement', page: 'purchase-requisitions', action: 'view' },
  '/procurement/requisitions/create': { module: 'procurement', page: 'purchase-requisitions', action: 'create' },
  '/procurement/returns': { module: 'procurement', page: 'purchase-returns', action: 'view' },
  '/procurement/returns/:id/edit': { module: 'procurement', page: 'purchase-returns', action: 'edit' },
  '/procurement/returns/:id/view': { module: 'procurement', page: 'purchase-returns', action: 'view' },
  '/procurement/returns/create': { module: 'procurement', page: 'purchase-returns', action: 'create' },
  '/procurement/settings': { module: 'procurement', page: 'procurement-config', action: 'edit' },
  '/procurement/suppliers': { module: 'procurement', page: 'suppliers', action: 'view' },
  '/procurement/suppliers/:id/edit': { module: 'procurement', page: 'suppliers', action: 'edit' },
  '/procurement/suppliers/:id/view': { module: 'procurement', page: 'suppliers', action: 'view' },
  '/procurement/suppliers/create': { module: 'procurement', page: 'suppliers', action: 'create' },
  '/procurement/three-way-matching': { module: 'procurement', page: 'three-way-matching', action: 'view' },
  '/products': { module: 'products', page: 'products', action: 'view' },
  '/prospects': { module: 'clients', page: 'prospects', action: 'view' },
  '/receivable': { module: 'receivables', page: 'customer-receivables', action: 'view' },
  '/receivables/:id/view': { module: 'receivables', page: 'customer-receivables', action: 'view' },
  '/receivables/advanced-reporting': { module: 'receivables', page: 'customer-statements', action: 'view' },
  '/receivables/aging-report': { module: 'receivables', page: 'customer-receivables', action: 'view' },
  '/receivables/bulk-payment-upload': { module: 'receivables', page: 'customer-statements', action: 'view' },
  '/receivables/collections': { module: 'receivables', page: 'customer-receivables', action: 'view' },
  '/receivables/collections/workbench': { module: 'receivables', page: 'customer-receivables', action: 'view' },
  '/receivables/dashboard': { module: 'receivables', page: 'customer-receivables', action: 'view' },
  '/receivables/data-consistency': { module: 'receivables', page: 'customer-statements', action: 'view' },
  '/receivables/list': { module: 'receivables', page: 'customer-receivables', action: 'view' },
  '/receivables/payment-plans': { module: 'receivables', page: 'payment-plans', action: 'view' },
  '/receivables/payment-trends': { module: 'receivables', page: 'customer-statements', action: 'view' },
  '/receivables/payments/record': { module: 'receivables', page: 'record-payment', action: 'create' },
  '/receivables/reminders': { module: 'receivables', page: 'receivable-activity', action: 'view' },
  '/receivables/statement-preview-test': { module: 'receivables', page: 'customer-statements', action: 'view' },
  '/receivables/statements': { module: 'receivables', page: 'customer-statements', action: 'view' },
  '/receivables/workflows': { module: 'receivables', page: 'receivable-activity', action: 'view' },
  '/report/:reportCode': { module: 'reports', page: 'report-executions', action: 'view' },
  '/reports': { module: 'reports', page: 'report-templates', action: 'view' },
  '/reports/:reportId/edit': { module: 'reports', page: 'report-templates', action: 'edit' },
  '/reports/clients/groups': { module: 'clients', page: 'client-groups', action: 'export' },
  '/reports/contributions/daily': { module: 'savings', page: 'savings-collection', action: 'export' },
  '/reports/contributions/spreadsheet': { module: 'savings', page: 'savings-collection', action: 'export' },
  '/reports/daily-summary': { module: 'loans', page: 'loan-reports', action: 'export' },
  '/reports/daily-transactions': { module: 'loans', page: 'loan-reports', action: 'export' },
  '/reports/financial/balance-sheet': { module: 'reports', page: 'financial-reports', action: 'view' },
  '/reports/financial/cash-flow': { module: 'reports', page: 'financial-reports', action: 'view' },
  '/reports/financial/profit-loss': { module: 'reports', page: 'financial-reports', action: 'view' },
  '/reports/financial/trial-balance': { module: 'reports', page: 'financial-reports', action: 'view' },
  '/reports/loans/debtors': { module: 'loans', page: 'loan-reports', action: 'export' },
  '/reports/loans/defaulters': { module: 'loans', page: 'loan-reports', action: 'export' },
  '/reports/loans/par': { module: 'loans', page: 'loan-reports', action: 'export' },
  '/reports/new': { module: 'reports', page: 'report-templates', action: 'create' },
  '/reports/officer-portfolio': { module: 'loans', page: 'loan-reports', action: 'export' },
  '/reports/portfolio-performance': { module: 'loans', page: 'loan-reports', action: 'export' },
  '/reports/savings-by-product': { module: 'savings', page: 'savings-reports', action: 'export' },
  '/reports/summary': { module: 'loans', page: 'loan-reports', action: 'export' },
  '/sales/credit-notes': { module: 'incomes', page: 'invoices', action: 'view' },
  '/sales/invoices': { module: 'incomes', page: 'invoices', action: 'view' },
  '/sales/invoices/:id/edit': { module: 'incomes', page: 'invoices', action: 'edit' },
  '/sales/invoices/:id/view': { module: 'incomes', page: 'invoices', action: 'view' },
  '/sales/invoices/:invoiceId/credit-notes': { module: 'incomes', page: 'invoices', action: 'view' },
  '/sales/invoices/:invoiceId/credit-notes/:creditNoteId/edit': { module: 'incomes', page: 'invoices', action: 'edit' },
  '/sales/invoices/:invoiceId/credit-notes/:creditNoteId/view': { module: 'incomes', page: 'invoices', action: 'view' },
  '/sales/invoices/:invoiceId/credit-notes/create': { module: 'incomes', page: 'invoices', action: 'create' },
  '/sales/invoices/create-inventory': { module: 'incomes', page: 'invoices', action: 'create' },
  '/savings/accounts': { module: 'savings', page: 'savings-accounts', action: 'view' },
  '/savings/accounts/:id': { module: 'savings', page: 'savings-accounts', action: 'view' },
  '/savings/accounts/create': { module: 'savings', page: 'savings-accounts', action: 'create' },
  '/savings/collection': { module: 'savings', page: 'savings-collection', action: 'view' },
  '/savings/collection/multi-day': { module: 'savings', page: 'savings-collection', action: 'create' },
  '/savings/collection/sheet': { module: 'savings', page: 'savings-collection', action: 'view' },
  '/savings/collection/spreadsheet': { module: 'savings', page: 'savings-collection', action: 'view' },
  '/savings/combined-receipt': { module: 'savings', page: 'combined-receipt', action: 'view' },
  '/savings/deposit': { module: 'savings', page: 'savings-deposit', action: 'create' },
  '/savings/group-combined-receipt': { module: 'savings', page: 'combined-receipt', action: 'view' },
  '/savings/policy': { module: 'savings', page: 'compulsory-savings-policies', action: 'view' },
  '/savings/products': { module: 'products', page: 'products', action: 'view' },
  '/savings/products/:id/config': { module: 'products', page: 'products', action: 'edit' },
  '/savings/withdrawals': { module: 'savings', page: 'savings-withdrawals', action: 'edit' },
  '/settings/role-navigation': { module: 'dashboards', page: 'dashboards', action: 'view' },
  '/treasury': { module: 'cash-management', page: 'summary', action: 'view' },
  '/treasury/bank-reconciliation': { module: 'cash-management', page: 'bank-reconciliation', action: 'edit' },
  '/treasury/cash-reconciliation': { module: 'cash-management', page: 'cash-reconciliation', action: 'edit' },
  '/treasury/cash-transfers': { module: 'cash-management', page: 'cash-transfers', action: 'view' },
  '/treasury/cash-transfers/new': { module: 'cash-management', page: 'cash-transfers', action: 'create' },
  '/treasury/cashier-accounts': { module: 'cash-management', page: 'cashier-accounts', action: 'view' },
  '/treasury/cashier-accounts/new': { module: 'cash-management', page: 'cashier-accounts', action: 'create' },
  '/treasury/dashboard': { module: 'cash-management', page: 'summary', action: 'view' },
  '/treasury/petty-cash': { module: 'cash-management', page: 'petty-cash-funds', action: 'view' },
  '/treasury/petty-cash/funds/:id': { module: 'cash-management', page: 'petty-cash-funds', action: 'view' },
  '/treasury/petty-cash/funds/:id/edit': { module: 'cash-management', page: 'petty-cash-funds', action: 'edit' },
  '/treasury/petty-cash/funds/new': { module: 'cash-management', page: 'petty-cash-funds', action: 'create' },
  '/treasury/petty-cash/replenishments': { module: 'cash-management', page: 'petty-cash-replenishments', action: 'view' },
  '/treasury/petty-cash/replenishments/:id': { module: 'cash-management', page: 'petty-cash-replenishments', action: 'view' },
  '/treasury/petty-cash/replenishments/new': { module: 'cash-management', page: 'petty-cash-replenishments', action: 'create' },
  '/treasury/petty-cash/vouchers': { module: 'cash-management', page: 'petty-cash-vouchers', action: 'view' },
  '/treasury/petty-cash/vouchers/:id': { module: 'cash-management', page: 'petty-cash-vouchers', action: 'view' },
  '/treasury/petty-cash/vouchers/:id/edit': { module: 'cash-management', page: 'petty-cash-vouchers', action: 'edit' },
  '/treasury/petty-cash/vouchers/new': { module: 'cash-management', page: 'petty-cash-vouchers', action: 'create' },
};

/**
 * Dev-mode self-check: warn if any ROUTE_TO_PAGE entry references a module:page
 * that doesn't actually exist in PAGE_REGISTRY_MAP (catches typos since this
 * file is large and hand/script-assembled).
 */
if (process.env.NODE_ENV !== 'production') {
  for (const [routePath, mapping] of Object.entries(ROUTE_TO_PAGE)) {
    const key = `${mapping.module}:${mapping.page}`;
    if (!PAGE_REGISTRY_MAP[key]) {
      // eslint-disable-next-line no-console
      console.warn(
        `[routeToPageMap] Route "${routePath}" references unknown module:page "${key}" ` +
        `— check permissionRegistry.ts for a typo or missing PermPage entry.`
      );
    }
  }
}
