# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('start_date', models.DateField(help_text='When delegation becomes active')),
                ('end_date', models.DateField(help_text='When delegation ends')),
                ('is_active', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for delegation (e.g., vacation, sick leave)')),
                ('workflow_types', models.JSONField(blank=True, default=list, help_text='Specific workflow types to delegate. Empty means all workflows')),
                ('approval_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount delegate can approve. Null means no limit', max_digits=18, null=True)),
            ],
            options={
                'verbose_name': 'Approval Delegation',
                'verbose_name_plural': 'Approval Delegations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(help_text='Form field definitions and validation rules')),
                ('trigger_event_name', models.CharField(default='form-submission', help_text='Event name triggered when form is submitted', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata including calculated variables')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Form Schema',
                'verbose_name_plural': 'Form Schemas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('submission_reference', models.CharField(editable=False, max_length=100, unique=True)),
                ('data', models.JSONField(default=dict)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('schema_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StepExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_id', models.CharField(max_length=100)),
                ('step_type', models.CharField(max_length=50)),
                ('step_name', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('variables_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'step_executions',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('step_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('approval_message', models.TextField()),
                ('context_data', models.JSONField(default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('timeout_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_level', models.IntegerField(default=0, help_text='How many times this approval has been escalated')),
                ('escalated_at', models.DateTimeField(blank=True, help_text='When this approval was escalated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters passed to workflow execution. Examples: target_account_id, target_account_name, contra_account_id')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority bindings execute first')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this binding is active')),
                ('execution_count', models.IntegerField(default=0, help_text='Number of times this binding has been executed')),
                ('last_executed_at', models.DateTimeField(blank=True, help_text='Last execution timestamp', null=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('entity_type', models.CharField(help_text='Entity type: INCOME, EXPENSE, ASSET, LIABILITY, LOAN, SAVINGS, etc.', max_length=50)),
                ('entity_model', models.CharField(help_text='Django model path: accounts.Account, products.Product, etc.', max_length=100)),
            ],
            options={
                'verbose_name': 'Workflow Default',
                'verbose_name_plural': 'Workflow Defaults',
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('run_reference', models.CharField(editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('awaiting_approval', 'Awaiting Approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('depth', models.IntegerField(default=0)),
                ('workflow_version', models.IntegerField(default=1)),
                ('current_step_id', models.CharField(blank=True, max_length=100, null=True)),
                ('context', models.JSONField(default=dict)),
                ('execution_log', models.JSONField(default=list)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('error_step_id', models.CharField(blank=True, max_length=100)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('workflow_type', models.CharField(choices=[('system', 'System'), ('template', 'Template'), ('master_template', 'Master Template'), ('standard', 'Standard'), ('custom', 'Custom')], default='standard', max_length=20)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted'), ('private', 'Private')], default='private', max_length=20)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_atomic', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('required_inputs', models.JSONField(default=list)),
                ('outputs', models.JSONField(default=list)),
                ('trigger_type', models.CharField(choices=[('event', 'Event Trigger'), ('schedule', 'Scheduled'), ('manual', 'Manual')], max_length=20)),
                ('trigger_config', models.JSONField(default=dict)),
                ('workflow_definition', models.JSONField(default=dict)),
                ('max_execution_time_seconds', models.IntegerField(default=300)),
                ('max_depth', models.IntegerField(default=3)),
                ('max_steps', models.IntegerField(default=15)),
                ('requires_approval', models.BooleanField(default=False)),
                ('approval_config', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('average_duration_ms', models.IntegerField(blank=True, null=True)),
                ('run_sequence', models.CharField(blank=True, editable=False, help_text='Unique identifier for this workflow template', max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('definition', models.JSONField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('testing', 'Testing'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('deprecated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_versions',
                'ordering': ['-version'],
            },
        ),
    ]
