# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('batch_size', models.IntegerField(default=100, help_text='Number to send per batch')),
                ('delay_between_batches', models.IntegerField(default=60, help_text='Seconds to wait between batches')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('sent_count', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(help_text="Provider name (e.g., 'twilio', 'sendgrid', 'termii')", max_length=50)),
                ('provider_config', models.JSONField(default=dict, help_text="\n        Provider-specific configuration:\n        {\n            'api_key': 'encrypted_key',\n            'sender_id': 'YourBrand',\n            'endpoint': 'https://api.provider.com',\n            'rate_limit': 100  // per minute\n        }\n        ")),
                ('cost_per_unit', models.DecimalField(decimal_places=4, default=0, help_text='Cost per notification (for budgeting)', max_digits=10)),
                ('rate_limit_per_minute', models.IntegerField(default=60)),
                ('rate_limit_per_hour', models.IntegerField(default=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('category_preferences', models.JSONField(default=dict, help_text="\n        Per-category channel preferences:\n        {\n            'transactions': ['sms', 'email', 'in_app'],\n            'marketing': ['email'],\n            'alerts': ['sms', 'push', 'in_app']\n        }\n        ")),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('max_per_day', models.IntegerField(blank=True, help_text='Maximum notifications per day (null = unlimited)', null=True)),
                ('max_per_category_per_day', models.JSONField(blank=True, default=dict, help_text="{'transactions': 10, 'marketing': 2}")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, help_text="Category for organization (e.g., 'transactions', 'alerts')", max_length=50)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('send_conditions', models.JSONField(blank=True, default=dict, help_text="\n        Conditions that must be met to send:\n        {\n            'all_of': [\n                {'field': 'amount', 'operator': '>', 'value': 1000},\n                {'field': 'client.status', 'operator': '==', 'value': 'active'}\n            ],\n            'any_of': [\n                {'field': 'client.communication_preference', 'operator': 'in', 'values': ['sms', 'email']}\n            ]\n        }\n        ")),
                ('schedule_config', models.JSONField(blank=True, default=dict, help_text="\n        {\n            'delay_seconds': 0,  // Immediate by default\n            'send_at_time': '09:00',  // Specific time of day\n            'business_hours_only': True,\n            'timezone': 'Africa/Lagos'\n        }\n        ")),
                ('retry_config', models.JSONField(blank=True, default=dict, help_text="\n        {\n            'max_attempts': 3,\n            'retry_delays': [60, 300, 900],  // seconds\n            'retry_on_failure_types': ['network_error', 'provider_error']\n        }\n        ")),
                ('template_variables', models.JSONField(default=list, help_text="\n        Variables available in templates:\n        [\n            {\n                'name': 'client_name',\n                'source': 'client.full_name',\n                'required': True\n            },\n            {\n                'name': 'amount',\n                'source': 'transaction.amount',\n                'format': 'currency',\n                'required': True\n            },\n            {\n                'name': 'balance',\n                'source': 'account.balance',\n                'format': 'currency',\n                'default': '0.00'\n            }\n        ]\n        ")),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of successful deliveries', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateChannelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_template', models.CharField(blank=True, help_text='Subject line (for email) or title (for push)', max_length=255)),
                ('body_template', models.TextField(help_text='Message body with {{variable}} placeholders')),
                ('html_template', models.TextField(blank=True, help_text='HTML version for email')),
                ('attachments_config', models.JSONField(blank=True, default=list, help_text="\n        [\n            {\n                'type': 'pdf',\n                'source': 'generate_receipt',\n                'filename': 'receipt_{{reference_number}}.pdf'\n            }\n        ]\n        ")),
                ('channel_settings', models.JSONField(blank=True, default=dict, help_text="\n        Channel-specific options:\n        {\n            'sms': {'sender_name': 'MyCompany'},\n            'email': {'reply_to': 'support@company.com'},\n            'whatsapp': {'template_id': 'welcome_template'}\n        }\n        ")),
                ('priority', models.IntegerField(default=0, help_text='Send order (0 = first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('recipient_contact', models.CharField(blank=True, help_text='Email address or phone number', max_length=255)),
                ('recipient_name', models.CharField(blank=True, help_text='Recipient display name', max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('html_message', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('read', 'Read')], db_index=True, default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='When to send (null = immediate)', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('context_data', models.JSONField(default=dict, help_text='Data used to render this notification')),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text='Response from the notification provider')),
                ('provider_message_id', models.CharField(blank=True, help_text="Provider's tracking ID", max_length=255)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('cost', models.DecimalField(decimal_places=4, default=0, help_text='Actual cost of sending', max_digits=10)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
