# Generated by Django 5.2.4 on 2026-01-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('query', models.TextField(help_text='SQL query template')),
                ('parameters', models.JSONField(default=dict, help_text='Parameters schema for the query')),
            ],
            options={
                'verbose_name': 'Saved Query',
                'verbose_name_plural': 'Saved Queries',
                'ordering': ['-created_at'],
            },
        ),
    ]
