# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('automations', '0002_initial'),
        ('branches', '0002_initial'),
        ('clients', '0002_initial'),
        ('incomes', '0001_initial'),
        ('inventory', '0001_initial'),
        ('receivables', '0001_initial'),
        ('transactions', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicterm',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='incomes.academicyear'),
        ),
        migrations.AddField(
            model_name='applieddiscount',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='applieddiscount',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applieddiscount',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry created when discount was posted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_entries', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='applieddiscount',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applieddiscount',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applieddiscount',
            name='receivable',
            field=models.ForeignKey(help_text='The receivable being discounted', on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='receivables.customerreceivable'),
        ),
        migrations.AddField(
            model_name='applieddiscount',
            name='reversal_entry',
            field=models.ForeignKey(blank=True, help_text='Journal entry created when discount was reversed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_reversals', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='applieddiscount',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applieddiscount',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='discountapplication',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='discountapplication',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discount_applications', to='clients.client'),
        ),
        migrations.AddField(
            model_name='discountapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountapplication',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_applications_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountapplication',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='applieddiscount',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_discounts', to='incomes.discountapplication'),
        ),
        migrations.AddField(
            model_name='discountprogram',
            name='approval_workflow',
            field=models.ForeignKey(blank=True, help_text='Optional workflow for approval process (runs after discount is calculated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_approval_programs', to='automations.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='discountprogram',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='discountprogram',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountprogram',
            name='discount_account',
            field=models.ForeignKey(help_text='Account for posting discounts (Contra-Revenue or Expense)', on_delete=django.db.models.deletion.PROTECT, related_name='discount_programs', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='discountprogram',
            name='eligibility_workflow',
            field=models.ForeignKey(blank=True, help_text='Optional workflow for advanced eligibility checks (query/calculate only, no transactions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_eligibility_programs', to='automations.workflowtemplate'),
        ),
        migrations.AddField(
            model_name='discountprogram',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discountprogram',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='discountapplication',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='incomes.discountprogram'),
        ),
        migrations.AddField(
            model_name='entitlementpaymentlog',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='entitlementpaymentlog',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitlementpaymentlog',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitlementpaymentlog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='entitlementpaymentlog',
            name='transaction_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlement_payments', to='transactions.transactionentry'),
        ),
        migrations.AddField(
            model_name='entitlementstatuslog',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='entitlementstatuslog',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitlementstatuslog',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitlementstatuslog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='entitlementusagelog',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='entitlementusagelog',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitlementusagelog',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitlementusagelog',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='feeentitlement',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='feeentitlement',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_entitlements', to='clients.client'),
        ),
        migrations.AddField(
            model_name='feeentitlement',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeentitlement',
            name='inventory_allocation',
            field=models.ForeignKey(blank=True, help_text='Link to inventory allocation for physical items included with this entitlement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_entitlements', to='inventory.inventoryallocation'),
        ),
        migrations.AddField(
            model_name='feeentitlement',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feeentitlement',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='entitlementusagelog',
            name='entitlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='incomes.feeentitlement'),
        ),
        migrations.AddField(
            model_name='entitlementstatuslog',
            name='entitlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='incomes.feeentitlement'),
        ),
        migrations.AddField(
            model_name='entitlementpaymentlog',
            name='entitlement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='incomes.feeentitlement'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='feeentitlement',
            name='fee_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='incomes.feestructure'),
        ),
        migrations.AddField(
            model_name='income',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='income',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Client/Customer this income is from', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='clients.client'),
        ),
        migrations.AddField(
            model_name='income',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='inventory_allocation',
            field=models.ForeignKey(blank=True, help_text='Link to inventory allocation if this income includes physical items/vouchers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='inventory.inventoryallocation'),
        ),
        migrations.AddField(
            model_name='income',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='income',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='incomeaccountingconfig',
            name='bad_debt_account',
            field=models.ForeignKey(blank=True, help_text='Expense account for writing off bad debts', limit_choices_to={'account_type': 'expense'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_bad_debt_configs', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='incomeaccountingconfig',
            name='bank_transfer_account',
            field=models.ForeignKey(blank=True, help_text='Bank account for electronic transfers', limit_choices_to={'account_type__in': ['current_asset', 'bank']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_bank_transfer_configs', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='incomeaccountingconfig',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='incomeaccountingconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomeaccountingconfig',
            name='credit_card_account',
            field=models.ForeignKey(blank=True, help_text='Account for credit card payments', limit_choices_to={'account_type__in': ['current_asset', 'bank']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_credit_card_configs', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='incomeaccountingconfig',
            name='default_ar_account',
            field=models.ForeignKey(help_text='Default Accounts Receivable account for invoices', limit_choices_to={'account_type': 'current_asset'}, on_delete=django.db.models.deletion.PROTECT, related_name='income_ar_configs', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='incomeaccountingconfig',
            name='default_cash_account',
            field=models.ForeignKey(help_text='Default cash/bank account for cash receipts', limit_choices_to={'account_type__in': ['current_asset', 'bank']}, on_delete=django.db.models.deletion.PROTECT, related_name='income_cash_configs', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='incomeaccountingconfig',
            name='discount_allowed_account',
            field=models.ForeignKey(blank=True, help_text='Expense account for discounts given to customers', limit_choices_to={'account_type': 'expense'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_discount_configs', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='incomeaccountingconfig',
            name='mobile_money_account',
            field=models.ForeignKey(blank=True, help_text='Account for mobile money payments (M-Pesa, etc.)', limit_choices_to={'account_type__in': ['current_asset', 'bank']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_mobile_money_configs', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='incomeaccountingconfig',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomeaccountingconfig',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='income_account',
            field=models.ForeignKey(help_text='GL account for this income category (must be INCOME type)', on_delete=django.db.models.deletion.PROTECT, related_name='income_categories', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='incomes.incomecategory'),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(help_text='Income category (determines GL account)', on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='incomes.incomecategory'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='category',
            field=models.ForeignKey(help_text='Income category for this fee structure', on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='incomes.incomecategory'),
        ),
        migrations.AddField(
            model_name='incomecategoryaccountoverride',
            name='ar_account',
            field=models.ForeignKey(blank=True, help_text='Override AR account for this income category', limit_choices_to={'account_type': 'current_asset'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_ar_overrides', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='incomecategoryaccountoverride',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='incomecategoryaccountoverride',
            name='cash_account',
            field=models.ForeignKey(blank=True, help_text='Override cash account for this income category', limit_choices_to={'account_type__in': ['current_asset', 'bank']}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_cash_overrides', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='incomecategoryaccountoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomecategoryaccountoverride',
            name='income_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_override', to='incomes.incomecategory'),
        ),
        migrations.AddField(
            model_name='incomecategoryaccountoverride',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomecategoryaccountoverride',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='incomes.feestructure'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='inventory_allocation',
            field=models.ForeignKey(blank=True, help_text='Link to inventory allocation if invoice includes physical items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='inventory.inventoryallocation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='income',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='incomes.invoice'),
        ),
        migrations.AddField(
            model_name='feeentitlement',
            name='invoice',
            field=models.ForeignKey(help_text='Invoice that created this entitlement', on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='incomes.invoice'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='entitlement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='incomes.feeentitlement'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='paymentplaninstallment',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='paymentplaninstallment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentplaninstallment',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentplaninstallment',
            name='payment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='incomes.paymentplan'),
        ),
        migrations.AddField(
            model_name='paymentplaninstallment',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['is_active'], name='incomes_aca_is_acti_5adb1c_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['start_date', 'end_date'], name='incomes_aca_start_d_52c60b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('owner', 'code')},
        ),
        migrations.AddIndex(
            model_name='academicterm',
            index=models.Index(fields=['is_active'], name='incomes_aca_is_acti_549966_idx'),
        ),
        migrations.AddIndex(
            model_name='academicterm',
            index=models.Index(fields=['start_date', 'end_date'], name='incomes_aca_start_d_cb320f_idx'),
        ),
        migrations.AddIndex(
            model_name='academicterm',
            index=models.Index(fields=['invoice_generation_date'], name='incomes_aca_invoice_24933d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='academicterm',
            unique_together={('academic_year', 'term_number')},
        ),
        migrations.AddIndex(
            model_name='applieddiscount',
            index=models.Index(fields=['application', 'is_posted'], name='incomes_app_applica_85c5ba_idx'),
        ),
        migrations.AddIndex(
            model_name='applieddiscount',
            index=models.Index(fields=['receivable', 'is_posted'], name='incomes_app_receiva_4fb2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='applieddiscount',
            index=models.Index(fields=['is_reversed'], name='incomes_app_is_reve_7bd903_idx'),
        ),
        migrations.AddIndex(
            model_name='discountprogram',
            index=models.Index(fields=['program_type', 'is_active'], name='incomes_dis_program_dd1a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='discountprogram',
            index=models.Index(fields=['start_date', 'end_date'], name='incomes_dis_start_d_6babfa_idx'),
        ),
        migrations.AddIndex(
            model_name='discountprogram',
            index=models.Index(fields=['branch', 'is_active'], name='incomes_dis_branch__2f5448_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='discountprogram',
            unique_together={('owner', 'branch', 'program_code')},
        ),
        migrations.AddIndex(
            model_name='discountapplication',
            index=models.Index(fields=['client', 'status'], name='incomes_dis_client__aeba55_idx'),
        ),
        migrations.AddIndex(
            model_name='discountapplication',
            index=models.Index(fields=['program', 'status'], name='incomes_dis_program_21c670_idx'),
        ),
        migrations.AddIndex(
            model_name='discountapplication',
            index=models.Index(fields=['application_number'], name='incomes_dis_applica_11a078_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlementusagelog',
            index=models.Index(fields=['entitlement', 'usage_date'], name='incomes_ent_entitle_a5322a_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlementusagelog',
            index=models.Index(fields=['service_code'], name='incomes_ent_service_838ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlementstatuslog',
            index=models.Index(fields=['entitlement', 'changed_at'], name='incomes_ent_entitle_8f7846_idx'),
        ),
        migrations.AddIndex(
            model_name='entitlementpaymentlog',
            index=models.Index(fields=['entitlement', 'payment_date'], name='incomes_ent_entitle_420bf3_idx'),
        ),
        migrations.AddIndex(
            model_name='incomeaccountingconfig',
            index=models.Index(fields=['owner', 'branch'], name='income_acco_owner_i_fe38a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incomeaccountingconfig',
            unique_together={('owner', 'branch')},
        ),
        migrations.AddIndex(
            model_name='incomecategory',
            index=models.Index(fields=['code'], name='incomes_inc_code_b6f8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='incomecategory',
            index=models.Index(fields=['is_active'], name='incomes_inc_is_acti_5e48f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incomecategory',
            unique_together={('owner', 'branch', 'code')},
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['code'], name='incomes_fee_code_efc0bc_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['is_active', 'effective_from'], name='incomes_fee_is_acti_dfc701_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('owner', 'branch', 'code')},
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='incomes_inv_invoice_e03bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='incomes_inv_client__1edf95_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'status'], name='incomes_inv_due_dat_67f1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['reference_number'], name='incomes_inc_referen_ac035b_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['income_date'], name='incomes_inc_income__294581_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['client', 'income_date'], name='incomes_inc_client__ba2387_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['status'], name='incomes_inc_status_4c3b58_idx'),
        ),
        migrations.AddIndex(
            model_name='feeentitlement',
            index=models.Index(fields=['client', 'status'], name='incomes_fee_client__2273aa_idx'),
        ),
        migrations.AddIndex(
            model_name='feeentitlement',
            index=models.Index(fields=['invoice'], name='incomes_fee_invoice_3aee5e_idx'),
        ),
        migrations.AddIndex(
            model_name='feeentitlement',
            index=models.Index(fields=['fee_structure', 'status'], name='incomes_fee_fee_str_e8242f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['status'], name='incomes_pay_status_b42eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplaninstallment',
            index=models.Index(fields=['payment_plan', 'status'], name='incomes_pay_payment_8ca76c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplaninstallment',
            index=models.Index(fields=['due_date', 'status'], name='incomes_pay_due_dat_6f0010_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentplaninstallment',
            unique_together={('payment_plan', 'installment_number')},
        ),
    ]
