# Generated by Django 5.2.4 on 2026-02-01 07:27

import django.db.models.deletion
import incomes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='approval_notes',
            field=models.TextField(blank=True, help_text='Notes from approver or reason for rejection'),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved by Principal/Board'), ('rejected', 'Rejected')], default='draft', help_text='Approval status - fee structures must be approved before activation', max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When this fee structure was approved', null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Principal/Board member who approved this fee structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fee_structures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feeentitlement',
            name='valid_from',
            field=models.DateField(default=incomes.models.get_current_date),
        ),
    ]
