# Generated by Django 5.2.4 on 2026-02-20 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_latitude_branch_longitude'),
        ('clients', '0003_add_student_fields'),
        ('incomes', '0003_add_fee_structure_approval_workflow'),
        ('inventory', '0005_physicalcount_physicalcountline_and_more'),
        ('users', '0003_role_permission_codes_user_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('service', 'Service/Fee'), ('inventory', 'Inventory Item'), ('custom', 'Custom Item')], default='custom', help_text='Type of line item', max_length=20)),
                ('description', models.TextField(help_text='Item description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Quantity of items', max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount for this line item', max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax for this line item', max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total for this line (calculated)', max_digits=18)),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity of stock reserved for this invoice item', max_digits=18)),
                ('is_stock_reduced', models.BooleanField(default=False, help_text='Whether stock has been reduced for this item')),
                ('creates_entitlement', models.BooleanField(default=False, help_text='Whether this item creates a FeeEntitlement')),
                ('metadata', models.JSONField(default=dict, help_text='Item-specific metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='feestructure',
            name='included_inventory_items',
            field=models.JSONField(blank=True, default=list, help_text='List of inventory items included with this fee structure (e.g., textbooks, uniforms, supplies)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total invoice-level discount', max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_posted',
            field=models.BooleanField(default=False, help_text='Whether invoice has been posted to accounting'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='posted_by',
            field=models.ForeignKey(blank=True, help_text='User who posted this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all line items before discounts and tax', max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount', max_digits=18),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final amount after discounts and tax', max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DEPRECATED: Use total_amount for new invoices', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid so far', max_digits=18),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fee_structure',
            field=models.ForeignKey(blank=True, help_text='Primary fee structure (for bulk generation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='incomes.feestructure'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['is_posted'], name='incomes_inv_is_post_d03586_idx'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='entitlement',
            field=models.ForeignKey(blank=True, help_text='Entitlement created by this invoice item (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_invoice_items', to='incomes.feeentitlement'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='fee_structure',
            field=models.ForeignKey(blank=True, help_text='Fee structure (for service items that create entitlements)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='incomes.feestructure'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Inventory item (for physical goods)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_invoice_items', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(help_text='Parent invoice', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='incomes.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='reserved_from_location',
            field=models.ForeignKey(blank=True, help_text='Location where stock is reserved from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_invoice_reserved_items', to='inventory.location'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice', 'item_type'], name='incomes_inv_invoice_acb722_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['fee_structure'], name='incomes_inv_fee_str_3dda56_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['inventory_item'], name='incomes_inv_invento_c26407_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['is_deleted'], name='incomes_inv_is_dele_d05a96_idx'),
        ),
    ]
