# Generated by Django 5.2.4 on 2026-02-22 08:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_latitude_branch_longitude'),
        ('clients', '0005_client_lga_client_previous_school_name_and_more'),
        ('incomes', '0004_unified_invoice_line_items'),
        ('inventory', '0005_physicalcount_physicalcountline_and_more'),
        ('users', '0003_role_permission_codes_user_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructureComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('component_type', models.CharField(choices=[('service', 'Service'), ('inventory', 'Inventory Item')], help_text='Whether this component is a service or a physical inventory item', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantity included in this component', max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Price override for this fee structure. If 0, falls back to service_item.default_price or inventory_item.unit_price.', max_digits=18)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Mandatory components are always included; optional ones can be waived per client')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display / processing order within the fee structure')),
            ],
            options={
                'verbose_name': 'Fee Structure Component',
                'verbose_name_plural': 'Fee Structure Components',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('default_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default selling price; can be overridden at the fee structure level', max_digits=18)),
                ('creates_entitlement', models.BooleanField(default=True, help_text='When True, paying for this service via an invoice automatically creates a FeeEntitlement giving the client trackable access to the service.')),
                ('entitlement_config', models.JSONField(blank=True, default=dict, help_text='\n        Default entitlement rules for this service:\n        {\n            "payment_term_type": "minimum_deposit",\n            "minimum_required_percent": 50,\n            "full_access_at_percent": 100,\n            "grace_period_days": 30,\n            "allowed_services": [],\n            "restricted_services": []\n        }\n        ')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Service Items',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='invoiceitem',
            name='incomes_inv_fee_str_3dda56_idx',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='included_inventory_items',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='fee_structure',
        ),
        migrations.AlterField(
            model_name='feeentitlement',
            name='fee_structure',
            field=models.ForeignKey(blank=True, help_text='Fee structure template this entitlement was generated from (for reporting)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='incomes.feestructure'),
        ),
        migrations.AddField(
            model_name='feestructurecomponent',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='feestructurecomponent',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructurecomponent',
            name='fee_structure',
            field=models.ForeignKey(help_text='Parent fee structure template', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='incomes.feestructure'),
        ),
        migrations.AddField(
            model_name='feestructurecomponent',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text="Required when component_type='inventory'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_fee_structure_components', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='feestructurecomponent',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feestructurecomponent',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='category',
            field=models.ForeignKey(help_text='Income category that determines the GL account for revenue recognition', on_delete=django.db.models.deletion.PROTECT, related_name='service_items', to='incomes.incomecategory'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='feestructurecomponent',
            name='service_item',
            field=models.ForeignKey(blank=True, help_text="Required when component_type='service'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structure_components', to='incomes.serviceitem'),
        ),
        migrations.AddField(
            model_name='feeentitlement',
            name='service_item',
            field=models.ForeignKey(blank=True, help_text='The specific service this entitlement grants access to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='incomes.serviceitem'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='service_item',
            field=models.ForeignKey(blank=True, help_text="Service item from the service catalog (required for item_type='service')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='incomes.serviceitem'),
        ),
        migrations.AddIndex(
            model_name='feeentitlement',
            index=models.Index(fields=['service_item', 'status'], name='incomes_fee_service_1dfeb7_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['service_item'], name='incomes_inv_service_4696d4_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceitem',
            index=models.Index(fields=['code'], name='incomes_ser_code_712db9_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceitem',
            index=models.Index(fields=['is_active'], name='incomes_ser_is_acti_ffaa5d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceitem',
            unique_together={('owner', 'branch', 'code')},
        ),
        migrations.AddIndex(
            model_name='feestructurecomponent',
            index=models.Index(fields=['fee_structure', 'component_type'], name='incomes_fee_fee_str_c8e731_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructurecomponent',
            index=models.Index(fields=['service_item'], name='incomes_fee_service_792b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructurecomponent',
            index=models.Index(fields=['inventory_item'], name='incomes_fee_invento_c72d95_idx'),
        ),
    ]
