# Generated by Django 5.2.4 on 2026-03-01 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0006_add_invoice_journal_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='allows_material_requests',
            field=models.BooleanField(default=False, help_text='When True, paying for this service allows the client to make material requests'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='material_request_config',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Configuration for material requests:\n        {\n            "allowed_categories": ["CAT-001", "CAT-002"],  # Inventory categories allowed\n            "requires_approval": true,\n            "max_requests_per_term": 5,\n            "cost_tracking_method": "actual_cost" | "standard_cost"\n        }\n        '),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='material_request_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum value of inventory items that can be requested (null = unlimited)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service_type',
            field=models.CharField(choices=[('standard', 'Standard Service'), ('inventory_access', 'Inventory Access Service'), ('hybrid', 'Hybrid Service')], db_index=True, default='standard', help_text='Standard: Regular service without inventory access. Inventory Access: Allows client to request inventory items via material requests. Hybrid: Combination of both.', max_length=20),
        ),
    ]
