# Generated by Django 5.2.4 on 2026-04-24 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_add_contact_fields_and_invoice_bank_flag'),
        ('incomes', '0009_rename_incomes_iip_invoice_date_idx_incomes_inv_invoice_f02252_idx_and_more'),
        ('transactions', '0006_fix_empty_sequence_names'),
        ('users', '0008_role_excluded_permission_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReversalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_reference', models.CharField(db_index=True, help_text='journal_entry_reference of the payment transaction to reverse', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount being reversed', max_digits=18)),
                ('reason', models.TextField(help_text='Reason for the reversal request')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved or rejected the request', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_reversal_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('draft_journal_entry', models.ForeignKey(blank=True, help_text='Draft GL reversal entry pending approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reversal_request', to='transactions.transaction')),
                ('invoice', models.ForeignKey(help_text='Invoice whose payment is being reversed', on_delete=django.db.models.deletion.CASCADE, related_name='reversal_requests', to='incomes.invoice')),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns/manages this record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(help_text='User who submitted the reversal request', on_delete=django.db.models.deletion.PROTECT, related_name='payment_reversal_requests_made', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Payment Reversal Request',
                'verbose_name_plural': 'Payment Reversal Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice', 'status'], name='incomes_pay_invoice_d1cc48_idx'), models.Index(fields=['payment_reference', 'status'], name='incomes_pay_payment_83a5ed_idx')],
            },
        ),
    ]
