# Generated by Django 5.2.4 on 2026-02-04 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_add_default_ordering'),
        ('branches', '0002_initial'),
        ('users', '0002_setup_default_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text="e.g., 'FY 2025-2026' or 'Q1 2026'", max_length=100)),
                ('start_date', models.DateField(help_text='Budget period start date')),
                ('end_date', models.DateField(help_text='Budget period end date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('active', 'Active'), ('closed', 'Closed')], default='draft', help_text='Budget status workflow', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the budget was approved', null=True)),
                ('notes', models.TextField(blank=True, help_text='Budget notes and assumptions')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved the budget', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Budget Period',
                'verbose_name_plural': 'Budget Periods',
                'db_table': 'budgets_budget_period',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Budgeted amount for the period', max_digits=18)),
                ('notes', models.TextField(blank=True, help_text='Line item notes and justification')),
                ('account', models.ForeignKey(help_text='Account this budget applies to (typically expense accounts)', on_delete=django.db.models.deletion.PROTECT, related_name='budget_allocations', to='accounts.account')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Tenant (organization) this record belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='users.tenant')),
                ('budget_period', models.ForeignKey(help_text='Parent budget period', on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='budgets.budgetperiod')),
            ],
            options={
                'verbose_name': 'Budget Line',
                'verbose_name_plural': 'Budget Lines',
                'db_table': 'budgets_budget_line',
                'ordering': ['budget_period', 'account__code'],
            },
        ),
        migrations.AddIndex(
            model_name='budgetperiod',
            index=models.Index(fields=['owner', 'status', 'start_date'], name='budgets_bud_owner_i_7f481d_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetperiod',
            index=models.Index(fields=['start_date', 'end_date'], name='budgets_bud_start_d_6335ad_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['budget_period', 'account'], name='budgets_bud_budget__f13813_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['owner', 'budget_period'], name='budgets_bud_owner_i_d22207_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetline',
            unique_together={('budget_period', 'account')},
        ),
    ]
