# Generated by Django 5.2.4 on 2026-01-20 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('product_class', models.CharField(choices=[('PHYSICAL', 'Physical Product'), ('SERVICE', 'Service'), ('FINANCIAL', 'Financial Product'), ('DIGITAL', 'Digital Product')], max_length=50)),
                ('product_type', models.CharField(blank=True, choices=[('SAVINGS', 'Savings Product'), ('LOAN', 'Loan Product'), ('EXPENSE', 'Expense Product'), ('INVESTMENT', 'Investment Product'), ('INSURANCE', 'Insurance Product')], help_text='For financial products (SAVINGS/LOAN), specify the type', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('standard_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('min_transaction_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum amount per transaction', max_digits=18)),
                ('max_transaction_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount per transaction', max_digits=18, null=True)),
                ('daily_transaction_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Total transaction limit per day', max_digits=18, null=True)),
                ('monthly_transaction_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Total transaction limit per month', max_digits=18, null=True)),
                ('validation_scope', models.CharField(choices=[('category', 'Per Category'), ('account', 'Per Account'), ('user', 'Per User')], default='category', help_text='Scope for applying transaction limits', max_length=20)),
                ('track_inventory', models.BooleanField(default=False)),
                ('allow_credit_sales', models.BooleanField(default=False)),
                ('allow_reservations', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('interest_posting_method', models.CharField(choices=[('auto_journal', 'Automatic Journal Entry'), ('pending_approval', 'Pending Approval'), ('accrual', 'Accrual Only')], default='accrual', help_text='How interest should be posted', max_length=20)),
                ('interest_posting_cron', models.CharField(blank=True, help_text="Cron expression for scheduled interest posting (e.g., '0 0 1 * *' for monthly)", max_length=100)),
                ('auto_debit_fees', models.BooleanField(default=False, help_text='Automatically debit fees based on fee_structure')),
                ('fee_structure', models.JSONField(default=dict, help_text='Fee configuration for the product (maintenance_fee, transaction_fee, etc.)')),
                ('calculation_method', models.JSONField(default=dict, help_text='Rules for interest/fee calculation')),
                ('repayment_config', models.JSONField(default=dict, help_text='Configurable repayment rules')),
                ('validation_rules', models.JSONField(default=dict, help_text='Custom validation rules for this product (e.g., min_balance, withdrawal_frequency)')),
                ('custom_attributes', models.JSONField(default=dict, help_text='Industry-specific attributes')),
                ('metadata_schema', models.JSONField(default=dict, help_text='Schema for required metadata')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('attributes', models.JSONField(default=dict, help_text='Dynamic attributes for this category')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
                'ordering': ['industry', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ProductRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('document_type', models.CharField(blank=True, choices=[('id', 'Identification'), ('address', 'Address Proof'), ('income', 'Income Proof'), ('photo', 'Photograph'), ('other', 'Other')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('fee_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Amount'), ('hybrid', 'Hybrid (Fixed + Percentage)')], max_length=20)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('maximum_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
