# Generated by Django 5.2.4 on 2026-05-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contribution_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default contribution amount per cycle for savings products.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='contribution_cycle',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], help_text='Contribution frequency for savings products. Null = normal (no fixed cycle).', max_length=10, null=True),
        ),
    ]
